Freescale/meta-freescale

conf/machine/imx8mmevk.conf
conf/machine/imx8mqevk.conf
conf/machine/imx8qmmek.conf
conf/machine/imx8qxpmek.conf
conf/machine/include/imx-base.inc
recipes-kernel/linux/linux-imx-headers_4.9.123.bb
recipes-kernel/linux/linux-imx_4.9.123.bb

Only a PR for https://patchwork.openembedded.org/series/15548/

improvements for mx8

---

recipes-bsp/mxsldr/mxsldr_git.bb
recipes-devtools/imx-usb-loader/imx-usb-loader_git.bb

Move libusb receipes to use libusb1

---

conf/machine/imx8mmevk.conf
conf/machine/imx8mqevk.conf
conf/machine/include/imx-base.inc
recipes-bsp/imx-mkimage/imx-boot_0.2.bb
recipes-bsp/imx-mkimage/imx-mkimage_git.bb
wic/imx-imx-boot-bootpart.wks.in

This PR includes the patches from the following series:
https://patchwork.openembedded.org/series/15847/
https://patchwork.openembedded.org/series/15775/

Imx8 improves m4demos drop

---

recipes-bsp/atf/atf_git.bb

*Add FUSE DISTRO_FEATURES
*Add chassistype and ddrphyopt
*Install srk.pri and srk.pub
Signed-off-by: Chunrong Guo <chunrong.guo@nxp.com>

atf: Reorganize

---

conf/machine/imx8mqevk.conf
recipes-graphics/wayland/weston_4.0.0.imx.bb

[master] white-space compliant append

---

conf/machine/imx8mqevk.conf
recipes-graphics/wayland/weston_4.0.0.imx.bb

[thud] white-space compliant append

---

dynamic-layers/qt5-layer/recipes-qt/qt5/qtbase_%.bbappend
recipes-bsp/u-boot/u-boot-imx_2017.03.bb

[rocko] white-space compliant append

---

dynamic-layers/qt5-layer/recipes-qt/qt5/qtbase_%.bbappend
recipes-graphics/wayland/weston_4.0.0.imx.bb

[sumo] white-space compliant append

---

dynamic-layers/qt5-layer/recipes-qt/qt5/qtbase_%.bbappend
recipes-devtools/qemu/qemu-qoriq_git.bb
recipes-graphics/wayland/weston_1.11.1.bb

```
sed -i  -e "s/\(.*_append.* = \"\)\([^ $,+-]\)/\1 \2/""
```

[pyro] white-space compliant append

---

dynamic-layers/qt5-layer/recipes-qt/qt5/qtbase_%.bbappend
recipes-devtools/qemu/qemu-qoriq_git.bb

[morty] white-space compliant append

---

conf/machine/include/imx-base.inc
wic/imx-uboot-bootpart.wks.in

Some boards expects a specific binary name.
Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>
Signed-off-by: Joris Offouga <offougajoris@gmail.com>

wic: Fix image generation for i.MX

---

recipes-bsp/imx-vpu-hantro/imx-vpu-hantro_1.11.0.bb
recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_1.14.imx.bb
recipes-multimedia/gstreamer/gstreamer1.0-plugins-base-1.14.imx/0001-Makefile.am-don-t-hardcode-libtool-name-when-running.patch
recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_1.14.imx.bb
recipes-multimedia/gstreamer/gstreamer1.0-plugins-good_1.14.imx.bb
recipes-multimedia/gstreamer/gstreamer1.0_1.14.imx.bb
recipes-multimedia/gstreamer/imx-gst1.0-plugin_4.4.5.bb
recipes-multimedia/imx-codec/imx-codec_4.4.5.bb
recipes-multimedia/imx-parser/imx-parser_4.4.5.bb
recipes-multimedia/imx-vpuwrap/imx-vpuwrap_4.4.5.bb

Upstream Multimedia patches for 4.14.98-2.0.0_ga Release

L4.14.98 2.0.0 ga v1

---

recipes-bsp/imx-atf/imx-atf_2.0.bb
recipes-bsp/imx-sc-firmware/imx-sc-firmware_1.2.bb

imx-sc-firmware: Upgrade version from 0.9 to 1.2
imx-atf: Upgrade version from 1.5 to 2.0

bsp version upgrades

---

conf/machine/imx8mmevk.conf
conf/machine/include/imx-base.inc

This backports PR #112 from master to warrior branch.
--andrey

warrior: backport #112 from master

---

conf/machine/imx6sllevk.conf
conf/machine/imx6ulevk.conf
conf/machine/imx6ullevk.conf
conf/machine/imx7ulpevk.conf
conf/machine/imx8mmevk.conf
conf/machine/imx8mqevk.conf
conf/machine/imx8qmmek.conf
conf/machine/imx8qxpmek.conf

Allign with dtb changes from latest version of linux-imx.
Signed-off-by: Alexandru Palalau <ioan-alexandru.palalau@nxp.com>

Update dtb list for iMX machines.

---

recipes-kernel/linux/linux-fslc-lts-4.19.bb

linux-fslc-lts: upgrade 4.19.56 -> 4.19.66

---

recipes-bsp/imx-vpu-hantro/imx-vpu-hantro_1.11.0.bb
recipes-graphics/imx-gpu-viv/imx-gpu-viv-6.inc
recipes-graphics/mesa/mesa_%.bbappend

Fix QA issue: SRC_URI uses PN not BPN [src-uri-bad]

recipes: Use BPN instead of PN in SRC_URIs

---

recipes-bsp/atf/atf_git.bb

Backport of pull #161 to warrior.

Fix atf package architecture

---

recipes-bsp/imx-mkimage/imx-boot_0.2.bb
recipes-graphics/imx-gpu-viv/imx-gpu-viv-6.inc

Apply changes from PR #85 to the warrior branch

Build fixes

---

recipes-graphics/imx-gpu-viv/imx-gpu-viv-6.inc

Please also compare with [this thread](https://lists.yoctoproject.org/pipermail/meta-freescale/2019-October/024078.html).
Note that this makes the build compile, I did not yet runtime test it.

imx-gpu-viv: fix build with libvulkan

---

recipes-graphics/xorg-xserver/xserver-xorg_%.bbappend

xserver-xorg: Fix missing space in SRC_URI_append assignment

---

recipes-kernel/linux/linux-fslc-lts-4.19.bb

linux-fslc-lts-4.19: upgrade 4.19.66 -> 4.19.78 (master)

---

recipes-kernel/linux/linux-fslc-lts-4.19.bb

linux-fslc-lts-4.19: upgrade 4.19.66 -> 4.19.78 (warrior)

---

recipes-extended/vpp-core/vpp-core.bb

* fix missing startup.conf
Signed-off-by: Chunrong Guo <chunrong.guo@nxp.com>

vpp-core: install startup.conf

---

classes/qoriq_build_64bit_kernel.bbclass
recipes-graphics/imx-gpu-viv/imx-gpu-viv-6.inc
recipes-graphics/wayland/weston_5.0.0.imx.bb

distro_features_check is now deprecated

recipes: Use features_check instead of distro_features_check

---

conf/machine/ls1028ardb.conf

*set default rcw to rcw_1500_gpu600
Signed-off-by: Chunrong Guo <chunrong.guo@nxp.com>

ls1028ardb: update machine config

---

recipes-bsp/imx-sc-firmware/imx-sc-firmware_1.2.7.1.bb

imx-sc-firmware: Correct the License type and upgrade to 1.2.7 version

---

recipes-bsp/imx-atf/imx-atf_2.0.bb

imx-atf_2.0.bb: Update branch and revision for 4.19.35_1.1.0

---

recipes-bsp/imx-uuc/imx-uuc_git.bb

imx-uuc: Update SRCREV to ebb7d34

---

recipes-bsp/rcw/rcw_git.bb
recipes-dpaa2/management-complex/management-complex_10.18.0.bb

Improve support of available machines - reference and derived ones

Allow machine adoption

---

recipes-bsp/imx-mkimage/imx-mkimage_git.inc

imx-mkimage_git.inc: Update to 4.19.35_1.1.0

---

conf/machine/imx8mnevk.conf
conf/machine/include/imx-base.inc
recipes-bsp/imx-atf/imx-atf_2.0.bb
recipes-bsp/imx-mkimage/imx-boot_0.2.bb
recipes-graphics/wayland/weston-init.bbappend
recipes-security/optee-imx/optee-client_3.2.0.imx.bb
recipes-security/optee-imx/optee-os_3.2.0.imx.bb
recipes-security/optee-imx/optee-test_3.2.0.imx.bb

This series of patches introduces support for i.MX8M Nano SoC and corresponding EVK from NXP.
In order for a new SoC to be supported, several components are upgraded to the latest revisions, which contains the source code for newly added SoC.
Please note, that this PR is actually a WIP since there exists an issue with booting the EVK built off this configuration. Therefore, this PR should be considered as RFC and I would really appreciate if someone from NXP can have a look at it.
-- andrey

i.mx8m nano machine description

---

recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_1.16.imx.bb
recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_1.16.imx.bb
recipes-multimedia/gstreamer/gstreamer1.0-plugins-good_1.16.imx.bb
recipes-multimedia/gstreamer/gstreamer1.0-plugins-imx_git.bb
recipes-multimedia/gstreamer/gstreamer1.0-plugins-ugly_1.16.0.bb
recipes-multimedia/gstreamer/gstreamer1.0-rtsp-server_1.16.0.bb

gstreamer: Adapt to meson changes from oe-core

---

recipes-devtools/devregs/devregs_git.bb
recipes-devtools/devregs/files/0001-devregs-add-support-for-imx8mn-soc.patch

Update the package to the latest version available upstream, and
add patch which introduces support for i.MX8M Nano SoC.

devregs: update to latest version and add imx8mn support

---

recipes-bsp/firmware-imx/firmware-imx_8.1.1.bb

This files is already provide by linux-firmware
Signed-off-by: Joris Offouga <offougajoris@gmail.com>

firmware-imx: remove sdma-imx6q.bin and sdma-imx7d.bin

---

wic/imx-imx-boot-bootpart.wks.in

Can we cherry-pick to zeus as well?

Fix i.MX 8 partition overlap

---

classes/fsl-eula-unpack.bbclass

[zeus] fsl-eula-unpack.bbclass: Facilitate downstream EULA update

---

classes/fsl-eula-unpack.bbclass

Reverts Freescale/meta-freescale#295
Merged by mistake. Reverting it for now.

Revert "[zeus] fsl-eula-unpack.bbclass: Facilitate downstream EULA update"

---

classes/fsl-eula-unpack.bbclass

fsl-eula-unpack.bbclass: Facilitate downstream EULA update

---

recipes-bsp/atf/atf_git.bb
recipes-bsp/mc-utils/mc-utils_git.bb
recipes-bsp/rcw/rcw_git.bb
recipes-dpaa2/management-complex/management-complex_10.20.4.bb

Updating atf, rcw, mc-utils & mc -> LSDK-20.04

Lsdk 20.04 update

---

recipes-connectivity/openssl/openssl-qoriq/0001-eng_devcrypto-add-support-for-TLS-algorithms-offload.patch
recipes-connectivity/openssl/openssl-qoriq/0002-eng_devcrypto-add-support-for-TLS1.2-algorithms-offl.patch
recipes-connectivity/openssl/openssl-qoriq_1.1.1f.bb
recipes-dpaa2/restool/restool_git.bb
recipes-extended/dpdk/dpdk.inc
recipes-extended/dpdk/dpdk/0001-Add-RTE_KERNELDIR_OUT.patch
recipes-extended/dpdk/dpdk/0001-add-Wno-cast-function-type.patch
recipes-extended/dpdk/dpdk/0004-update-WERROR_FLAGS.patch
recipes-extended/dpdk/dpdk_18.11.bb
recipes-extended/dpdk/dpdk_19.11-20.04.bb
recipes-extended/ovs-dpdk/ovs-dpdk_2.13.0.bb
recipes-extended/vpp-core/dpdkvpp.bb
recipes-extended/vpp-core/dpdkvpp/0001-Add-RTE_KERNELDIR_OUT.patch
recipes-extended/vpp-core/dpdkvpp/0001-add-Wno-cast-function-type.patch
recipes-extended/vpp-core/dpdkvpp/0004-update-WERROR_FLAGS.patch
recipes-kernel/linux/linux-qoriq.inc
recipes-kernel/linux/linux-qoriq/0001-Makfefile-linux-5.4-add-warning-cflags-on-LSDK-20.04.patch
recipes-kernel/linux/linux-qoriq_4.14.bb
recipes-kernel/linux/linux-qoriq_4.19.bb
recipes-kernel/linux/linux-qoriq_5.4.bb

Some more LSDK-20.04 updates 
- VPP seems in progress and not prepared for LSDK-20.04
- dpdk/dpdkvpp should probably be merged (later)

LSDK 20.04 update II

---

conf/machine/include/imx-base.inc
recipes-bsp/libimxdmabuffer/libimxdmabuffer_1.0.1.bb
recipes-security/optee-imx/optee-test/0001-use-python3-instead-of-python.patch
recipes-security/optee-imx/optee-test_3.2.0.imx.bb

* imx-base.inc fixes to be able to set custom default BSPs
* libimxdmabuffer upgrade from 1.0.0 to 1.0.1 (for Python 3 support)

imx-base.inc fixes and libimxdmabuffer upgrade

---

recipes-bsp/imx-vpu-hantro/imx-vpu-hantro_1.16.0.bb
recipes-bsp/imx-vpu/imx-vpu_5.4.39.2.bb
recipes-multimedia/imx-codec/imx-codec_4.5.3.bb
recipes-multimedia/imx-parser/imx-parser_4.5.3.bb
recipes-multimedia/imx-vpuwrap/imx-vpuwrap_4.5.3.bb

Do imx vpu cnm/hantro, imx codec/parser/vpuwrap upstream for 5.4.3-1.0.0

Carol zhu yuqing/upstream multimedia

---

recipes-bsp/imx-kobs/imx-kobs_git.bb

Signed-off-by: Alexandru Palalau <ioan-alexandru.palalau@nxp.com>

imx-kobs: Update SRCREV to cee66d

---

conf/machine/include/imx-base.inc
recipes-graphics/mesa/mesa_%.bbappend

@agners @texierp @thochstein @zandrey @fbertux 
Please take a look.

mainline BSP small improvements

---

recipes-security/optee-imx/optee-os_3.2.0.imx.bb

Fix incorrect install path for optee-os .bin files

---

recipes-security/optee-imx/optee-client/0001-flags-do-not-override-CFLAGS-from-host.patch
recipes-security/optee-imx/optee-client_3.2.0.imx.bb

This PR addresses few issues that causes `optee-client` component build to fails.
-- andrey

optee-client build fixes

---

recipes-graphics/waffle/waffle/0001-meson-Add-missing-wayland-dependency-on-EGL.patch
recipes-graphics/waffle/waffle/0002-meson-Separate-surfaceless-option-from-x11.patch

Fix patch fuzz QA warning reported by build, use devtool to correct
patches.

waffle: fix patch fuzz QA warning

---

conf/machine/include/qoriq-base.inc
recipes-extended/dpdk/dpdk/0001-examples-ipsec-gw-fix-gcc-10-maybe-uninitialized-war.patch
recipes-extended/dpdk/dpdk_19.11-20.04.bb

Fixing two issues popping up while extending meta-freescale-distro with QorIQ support

Qor iq fixes

---

SCR/SCR-5.4.24_2.1.0.txt

Update the Software Content Register for the 5.4.24_2.1.0
NXP release.

SCR-5.4.24_2.1.0.txt: Update SCR for latest NXP release

---

recipes-kernel/linux/linux-qoriq/0001-libtraceevent-Fix-build-with-binutils-2.35.patch
recipes-kernel/linux/linux-qoriq/0001-perf-bench-Share-some-global-variables-to-fix-build-.patch
recipes-kernel/linux/linux-qoriq/0001-perf-cs-etm-Move-definition-of-traceid_list-global-v.patch
recipes-kernel/linux/linux-qoriq/0001-perf-tests-bp_account-Make-global-variable-static.patch
recipes-kernel/linux/linux-qoriq_5.4.bb

linux-qoriq: backport to fix perf compilation issue

---

conf/machine/imx6sllevk.conf

The list of DTB files and the virtual/bootloader leads to error during build

Updating imx6sllevk

---

recipes-extended/jailhouse/jailhouse_0.12.bb

Jailhouse upgrade to 0.12
Fix userspace missing tools

Jailhouse012

---

recipes-bsp/u-boot/u-boot-imx-common.inc

u-boot-imx: upgrade to imx_v2020.04_5.4.47_2.2.0

---

recipes-bsp/imx-sc-firmware/imx-sc-firmware_1.6.0.bb

imx-sc-firmware: Upgrade to 1.6.0 version

---

recipes-kernel/cryptodev/cryptodev-qoriq-1.11.inc

Only one new commit:
Fix build for Linux 5.9-rc1

cryptodev-qoriq: update to fabe598

---

recipes-bsp/atf/atf_git.bb

using append and += together is undefined behavior in bitbake

atf: Use space instead of +=

---

recipes-extended/secure-obj/secure-obj.inc

1. update to 71a6eb3
2. DEPENDS on python3-pycryptodome-native

secure-obj: update DEPENDS and commit

---

recipes-dpaa2/gpp-aioptool/gpp-aioptool/0001-add-fcommon-to-fix-gcc-10-build-issue.patch
recipes-dpaa2/gpp-aioptool/gpp-aioptool_git.bb

1. fix build failure with gcc10
2. fix host user contaminated issue

fix gpp-aioptool issues

---

recipes-devtools/qemu/qemu-qoriq_4.1.0.bb

Enable it to test KVM vhost-net feature.

qemu-qoriq: enable vhost PACKAGECONFIG

---

recipes-extended/tsntool/tsntool_git.bb

add vlan id with interactive input.

tsntool: update to 1d1686e

---

conf/machine/imx6qdlsabreauto.conf
conf/machine/imx6qdlsabresd.conf
conf/machine/include/imx-base.inc

machines: imx-base.inc: fix failing u-boot builds

---

recipes-bsp/imx-sc-firmware/imx-sc-firmware_1.7.1.bb

imx-sc-firmware: Upgrade to 1.7.1

---

recipes-bsp/alsa-state/alsa-state/imx/asound.state

@zandrey , please have a look. I don't understand how this works and note that my commit here for `wm8960audio4` has the same justification and content as your recent commit for `sofwm8960audio`. For that matter each of the `*wm8960audio*` blocks have identical content.

alsa-state sound card updates

---

conf/machine/include/imx-base.inc
recipes-support/opencv/opencv/0001-3rdparty-ippicv-Use-pre-downloaded-ipp.patch
recipes-support/opencv/opencv/0001-Add-smaller-version-of-download_models.py.patch
recipes-support/opencv/opencv/0001-Dont-use-isystem.patch
recipes-support/opencv/opencv/0001-Make-ts-module-external.patch
recipes-support/opencv/opencv/0001-Temporarliy-work-around-deprecated-ffmpeg-RAW-functi.patch
recipes-support/opencv/opencv/0001-Use-Os-to-compile-tinyxml2.cpp.patch
recipes-support/opencv/opencv/0003-To-fix-errors-as-following.patch
recipes-support/opencv/opencv/OpenCV_DNN_examples.patch
recipes-support/opencv/opencv/download.patch
recipes-support/opencv/opencv_4.4.0.imx.bb

Add recipe to support additional machine learning demos and tiny dnn.

opencv_4.4.0.imx: add recipe

---

recipes-security/optee-imx/optee-os_3.10.0.imx.bb

- Move log level variables to EXTRA_OEMAKE to simplify overriding
- Set LDFLAGS and CFLAGS globally, like normal
- Set -C in EXTRA_OEMAKE
- Drop do_compile after all of the above
- Drop un-necessary override of B variable
- Simplify creation of tee.bin link in DEPLOYDIR

optee-os: Cleanup build options

---

recipes-graphics/mesa/mesa_%.bbappend
recipes-graphics/xorg-xserver/xserver-xorg/0001-MGS-5186-Per-Specification-EGL_NATIVE_PIXMAP_KHR-req.patch
recipes-graphics/xorg-xserver/xserver-xorg/0001-glamor-glamor_egl.c-EGL_NATIVE_PIXMAP_KHR-do-not-req.patch
recipes-graphics/xorg-xserver/xserver-xorg/0001-hw-xwayland-Makefile.am-fix-build-without-glx.patch
recipes-graphics/xorg-xserver/xserver-xorg/0001-prefer-to-use-GLES2-for-glamor-EGL-config.patch
recipes-graphics/xorg-xserver/xserver-xorg_%.bbappend

Fix mesa and xserver-xorg

---

recipes-bsp/rcw/rcw_git.bb

Fix RCW binary decoding with Python3.

rcw: update to 1caebba

---

recipes-bsp/imx-atf/imx-atf_2.4.bb

imx-atf: Upgrade to 2.4

---

dynamic-layers/qt5-layer/recipes-qt/qt5/qtbase/0001-egl.prf-Fix-build-error-when-egl-headers-need-platfo.patch

Note the Qt ticket for the pending patch.

qtbase: Add reference for pending patch

---

recipes-graphics/wayland/weston-init.bbappend

effects the following SoCs
mx6q
mx6dl
mx6sx
mx6sl
mx7ulp
mx8qm
mx8mm
mx8mp
mx8qxp

weston-init: backport to gatesgarth - Do not exit with error if uncomment function fail

---

recipes-multimedia/libimxvpuapi/libimxvpuapi2_2.1.0.bb
recipes-multimedia/libimxvpuapi/libimxvpuapi2_2.1.2.bb

5adb84d7 libimxvpuapi2: Update to version 2.1.2
e0896264 libimxvpuapi2: Update to version 2.1.0

libimxvpuapi2: Adds version 2.1.2 on dunfell 

---

recipes-multimedia/libimxvpuapi/libimxvpuapi2_2.1.0.bb
recipes-multimedia/libimxvpuapi/libimxvpuapi2_2.1.2.bb

libimxvpuapi2: Update to version 2.1.0
libimxvpuapi2: Update to version 2.1.2

libimxvpuapi2: Adds version 2.1.2 

---

.github/workflows/backport.yaml

The new release allow the use of pull request comments
to trigger the backport process.

cicd: backport: update workflow based on new 0.0.4

---

conf/machine/include/imx-base.inc
conf/machine/include/imx8mm-evk.inc
conf/machine/include/imx8mp-evk.inc

It seems to me that backfill is improper for the jailhouse feature.

Jailhouse enablement rework

---

recipes-graphics/waffle/waffle/0001-meson-Add-missing-wayland-dependency-on-EGL.patch

waffle: Forward port the patch to latest waffle

---

recipes-graphics/waffle/waffle/0002-meson-Separate-surfaceless-option-from-x11.patch

waffle: Forward port Separate-surfaceless-option-from-x11 patch as well

---

recipes-bsp/u-boot/u-boot-fslc_2021.07.bb

u-boot-fslc: Add lzop as dependency

---

conf/machine/imx8dxl-ddr3l-evk.conf

imx8dxl-ddr3l-evk: Fix BOARD_TYPE

---

recipes-fsl/packagegroups/packagegroup-fsl-isp.bb

Fixes non fatal error with latest openembedded-core master branch.

packagegroup-fsl-isp: Mark as TUNE_PKGARCH specific

---

recipes-security/optee/optee-client.nxp.inc
recipes-security/optee/optee-os.nxp.inc

I was reviewing some other optee recipes and found this variables.
I would like to make sure if this is a typo or not.
Could you please, review? @otavio @ting-liu ?

[RFC] optee: Fix typo on override syntax

---

conf/machine/include/imx-base.inc
recipes-kernel/kernel-modules/kernel-module-nxp89xx_git.bb

This PR adds the recipe to pull the kernel module from code aurora (git version), and install it as MACHINE_FIRMWARE when MACHINE_FEATURE is present.

Add nxp89xx

---

recipes-security/optee-imx/optee-test_3.10.0.imx.bb
recipes-security/optee/optee-client.nxp.inc
recipes-security/optee/optee-os.nxp.inc

Correct forgotten changes when switching to the new override syntax.

optee: fix override syntax

---

recipes-bsp/imx-vpu-hantro/imx-vpu-hantro-daemon_1.1.0.bb
recipes-bsp/imx-vpu-hantro/imx-vpu-hantro_1.23.0.bb

Revert imx-vpu-hantro and imx-vpu-hantro-daemon due to package fetch failure

---

recipes-bsp/imx-vpu-hantro/imx-vpu-hantro-daemon_1.1.1.bb
recipes-bsp/imx-vpu-hantro/imx-vpu-hantro_1.24.0.bb

The archive is fixed (see #959), so upgrade imx-vpu-hantro again.

Upgrade imx-vpu-hantro

---

conf/machine/include/imx-base.inc

imx-base.inc: Add support to include extra data for NIP devices

---

dynamic-layers/chromium-browser-layer/recipes-browser/chromium/chromium-imx.inc
dynamic-layers/openembedded-layer/recipes-benchmark/glmark2/glmark2_%.bbappend
dynamic-layers/qt4-layer/recipes-qt4/qt4/qt4-imx-support.inc
dynamic-layers/qt5-layer/recipes-qt/qt5/qtbase_%.bbappend
dynamic-layers/qt5-layer/recipes-qt/qt5/qtwayland_%.bbappend

Fix dynamic layer overrides missed by the script.

dynamic-layers: Update SOC overrides

---

README

Signed-off-by: Luan Rafael Carneiro <luan.rafael@ossystems.com.br>

README: Fix readme to refers kirkstone release

---

recipes-bsp/firmware-imx/firmware-imx_8.15.bb

Create symbolic links in ${nonarch_base_libdir}/firmware for CODA VPU
firmwares, otherwise CODA driver could not load them directly in probe
function and hence fallback firmware loading being triggered, which is
usually 40-60 seconds later after system boots up.
Signed-off-by: Ming Liu <liu.ming50@gmail.com>

firmware-imx: create symbolic links for CODA VPU firmwares

---

conf/machine/imx8dx-mek.conf
conf/machine/imx8dxl-ddr3l-evk.conf
conf/machine/imx8dxl-lpddr4-evk.conf
conf/machine/imx8qm-mek.conf
conf/machine/imx8qxp-mek.conf
conf/machine/mpc8548cds.conf

Add SoC information in machines where it is missing

---

recipes-kernel/linux/linux-fslc-imx_5.15.bb

Signed-off-by: Daiane Angolini <daiane.angolini@foundries.io>

linux-fslc-imx: update to v5.15.60

---

recipes-graphics/wayland/weston/0001-g2d-renderer.c-Include-sys-stat.h.patch
recipes-graphics/wayland/weston_10.0.0.imx.bb
recipes-multimedia/gstreamer/gstreamer1.0-plugins-base/0001-gstallocatorphymem.c-Typecast-result-of-gst_phymem_g.patch
recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_1.20.0.imx.bb

gstreamer1.0-plugins-base: Fix build with clang

---

dynamic-layers/qt4-layer/recipes-qt4/qt4/qt4-imx-support.inc
dynamic-layers/qt4-layer/recipes-qt4/qt4/qt4/0001-config.tests-add-DEFINES-to-compile-egl-test-with-im.patch
dynamic-layers/qt4-layer/recipes-qt4/qt4/qt4/0002-config.tests-add-DEFINES-to-compile-egl4gles1-test-w.patch
dynamic-layers/qt4-layer/recipes-qt4/qt4/qt4/egl-pro-add-defines-to-compile-with-viv-fb.patch
dynamic-layers/qt4-layer/recipes-qt4/qt4/qt4/egl4gles1-pro-add-defines-to-compile-with-viv-fb.patch

Patches are the same but now are in git format ad have Signed-off-by and From fields as required. Also add Signed-off-by to commit message.
Signed-off-by: Mauro Salvini <m.salvini@koansoftware.com>

qt4-imx-support: change format of patches added by commit 4aed4a5

---

recipes-bsp/imx-uuc/imx-uuc_git.bb

Changes:
```
61f258f Create SCR-imx-uuc.txt
69029e7 Change to sleep 5s when no UDC available.
15cb53e Remove old mfgtool deamon support and old msc support
```

imx-uuc: Update to latest

---

conf/machine/imx53qsb.conf

imx53qsb: update maintainer email

---

conf/machine/include/imx-base.inc
recipes-graphics/imx-g2d/imx-dpu-g2d_2.1.2.bb
recipes-graphics/imx-g2d/imx-g2d-samples_git.bb
recipes-graphics/imx-g2d/imx-gpu-g2d_6.4.3.p4.4.bb
recipes-graphics/imx-gpu-viv/imx-gpu-viv-6.inc
recipes-graphics/imx-gpu-viv/imx-gpu-viv_6.4.3.p4.4-aarch32.bb
recipes-graphics/imx-gpu-viv/imx-gpu-viv_6.4.3.p4.4-aarch64.bb
recipes-graphics/wayland/weston_10.0.1.imx.bb

Resolves #1265
I built core-image-weston for imx6qdlsabresd imx6ullevk imx8mm-lpddr4-evk imx8qm-mek and tested on  imx8qm-mek.

Upgrade Graphics Packages to lf5.15.52_2.1.0

---

recipes-kernel/kernel-modules/kernel-module-imx-gpu-viv_6.4.3.p4.2.bb
recipes-kernel/linux/linux-fslc-imx_5.15.bb

I missed the Kernel Module with the graphical updates. :-(

Fix the kernel for i.MX8QM and Update the Galcore Kernel Module

---

recipes-extended/jailhouse/jailhouse_0.12.bb

Update jailhouse to the NXP lf-5.15.52_2.1.0 release, and clean up the packaging logic to align with the latest release.
Packaging changes:
- Drop build instructions for tools as that is now built as part of the
main Makefile
- Drop JH_CONFIG and related tools variables as they are not required
- Change do_compile and do_install to prepend to allow the logic from
setuptools3 to be executed (and package pyjailhouse properly)
- Drop kernel from PACKAGE_BEFORE_PN, as it wasn't really used in the
end, and doesn't work correctly with usrmerge. Prefer removing libdir
that gets appended by setuptools3 for module split to work correctly
with and without usrmerge.
- Update FILES for pyjailhouse to include all the python related files
produced by the build
Signed-off-by: Ricardo Salveti …

jailhouse: update to lf-5.15.52_2.1.0

---

conf/machine/include/imx-base.inc
recipes-bsp/u-boot/u-boot-fslc-common_2022.10.inc

Apply following changes:
cbd7eb17ac1 imx8mn-venice-u-boot: Fix broken boot
f463aeddbbf imx8mn-ddr4-evk-u-boot: Fix broken boot
d1920093874 imx6qdl-sabresd: Pass mmc alias
047ac33f481 wandboard: Pass mmc aliases
Fixes: #1324, #1267

u-boot-fslc: Bump revision to cbd7eb17ac1

---

recipes-bsp/mc-utils/mc-utils_git.bb
recipes-dpaa2/management-complex/management-complex_10.35.0.bb
recipes-dpaa2/restool/restool_git.bb

- Upgrade MC and related Utils API to 10.35.0
- Upgrade restool to pick the latest fix

Upgrade MC/mc-util and restool

---

recipes-bsp/uefi/uefi_git.bb
recipes-dpaa/fm-ucode/fm-ucode_git.bb
recipes-graphics/wayland/weston-init.bbappend

Update uefi and fm-ucode to new revision; Fix the weston-init issue

---

recipes-bsp/imx-seco/imx-seco-libs/0001-Fix-return-value-of-void-functions.patch
recipes-bsp/imx-seco/imx-seco-libs_git.bb
recipes-bsp/imx-seco/imx-seco_5.9.0.bb

Part of https://github.com/Freescale/meta-freescale/issues/1343

imx-seco Update from lf-5.15.52-2.1.0 to lf-5.15.71-2.2.0

---

recipes-security/optee-imx/optee-os/0001-core-Define-section-attributes-for-clang.patch
recipes-security/optee-imx/optee-os/0006-allow-setting-sysroot-for-libgcc-lookup.patch
recipes-security/optee-imx/optee-os/0007-allow-setting-sysroot-for-clang.patch
recipes-security/optee-imx/optee-os/0010-add-note-GNU-stack-section.patch
recipes-security/optee-imx/optee-os_3.19.0.imx.bb

Bring in the needed patches from meta-arm

optee-os: Fix build with clang

---

recipes-support/opencv/opencv/0001-Add-missing-header-for-LIBAVCODEC_VERSION_INT.patch
recipes-support/opencv/opencv_4.6.0.imx.bb

Also fix the variable ordering for the SRC_URI overrides.

opencv: Update copied recipe to latest

---

recipes-bsp/firmware-imx/firmware-nxp-wifi_1.0.bb

- 982bb10 FwImage: update firmware to mxm5x17366.p3
- aeba88d FwImage: update firmware to mxm5x17362

firmware-nxp-wifi: Update lf-5.15.52-2.1.0 to lf-5.15.71-2.2.0

---

recipes-bsp/firmware-imx/firmware-sof-imx_2.3.0.bb

firmware-sof-imx: Upgrade 2.2.0 -> 2.3.0

---

recipes-kernel/kernel-modules/kernel-module-imx-gpu-viv_6.4.3.p4.6+fslc.bb
recipes-multimedia/gstreamer/gstreamer1.0-plugins-base/0001-Fix-types-to-match-callback-functions.patch
recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_1.20.3.imx.bb

kernel-module-imx-gpu-viv: Fix build with gcc13

---

recipes-kernel/linux/linux-fslc-imx_5.15.bb

Signed-off-by: Daiane Angolini <daiane.angolini@foundries.io>

linux-fslc-imx: Bump kernel to fix lpuart

---

dynamic-layers/qt4-layer/recipes-qt4/qt4/qt4-imx-support.inc

Change the "+=" in "=", we are using the :append
Signed-off-by: Mauro Salvini <m.salvini@koansoftware.com>

qt4-imx-support.inc: fix append syntax

---

SCR/SCR-5.10.72-2.2.0.txt
dynamic-layers/openembedded-layer/recipes-dpaa/fmc/fmc_git.bb
recipes-bsp/atf/qoriq-atf-2.3.inc
recipes-bsp/atf/qoriq-atf_1.5.bb
recipes-bsp/mc-utils/mc-utils_git.bb
recipes-bsp/rcw/rcw_git.bb
recipes-bsp/u-boot/u-boot-qoriq_2020.04.bb
recipes-devtools/cst/cst_git.bb
recipes-devtools/qemu/qemu-qoriq_4.1.0.bb
recipes-dpaa/eth-config/eth-config_git.bb
recipes-dpaa/flib/flib_git.bb
recipes-dpaa/fmlib/fmlib_git.bb
recipes-dpaa2/aiopsl/aiopsl_git.bb
recipes-dpaa2/dce/dce_git.bb
recipes-dpaa2/gpp-aioptool/gpp-aioptool_git.bb
recipes-dpaa2/restool/restool_git.bb
recipes-dpaa2/spc/spc_git.bb
recipes-extended/dpdk/dpdk_19.11-20.12.bb
recipes-extended/libpkcs11/libpkcs11_git.bb
recipes-extended/odp/odp.inc
recipes-extended/ofp/ofp_git.bb
recipes-extended/ovs-dpdk/ovs-dpdk_2.13.0.bb
recipes-extended/secure-obj/secure-obj.inc
recipes-extended/tsntool/tsntool_git.bb
recipes-kernel/ceetm/ceetm_git.bb
recipes-kernel/linux/linux-qoriq_5.4.bb
recipes-security/optee/optee-os-qoriq_3.8.0.bb

There seem to have happened a small mishap when moving to github.
This fixes our CI/CD builds.

meta-freescale: fix broken IMX migration from codeaurora to github

---

recipes-kernel/linux/linux-fslc-lts_5.15.bb
recipes-kernel/linux/linux-fslc_6.1.bb

Tested building for imx8mm-lpddr-evk.

Upgrade linux-fslc and linux-fslc-lts

---

recipes-bsp/imx-atf/imx-atf_1.5.0.bb
recipes-bsp/imx-lib/imx-lib_git.bb
recipes-bsp/imx-mkimage/imx-mkimage_git.inc
recipes-bsp/imx-test/imx-test_git.bb
recipes-bsp/u-boot/u-boot-imx_2018.03.bb
recipes-graphics/drm/libdrm_2.4.91.imx.bb
recipes-graphics/imx-gpu-apitrace/imx-gpu-apitrace_7.1.0.bb
recipes-graphics/wayland/weston_4.0.0.imx.bb
recipes-graphics/xorg-driver/xf86-video-imx-vivante_6.2.4.p1.8.bb
recipes-kernel/kernel-modules/kernel-module-imx-gpu-viv_6.2.4.p1.8.bb
recipes-kernel/kernel-modules/kernel-module-qcacld-lea.inc
recipes-kernel/linux/linux-imx-headers_4.9.123.bb
recipes-kernel/linux/linux-imx.inc
recipes-multimedia/alsa/imx-alsa-plugins_1.0.26.bb
recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_1.14.imx.bb
recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_1.14.imx.bb
recipes-multimedia/gstreamer/gstreamer1.0-plugins-good_1.14.imx.bb
recipes-multimedia/gstreamer/gstreamer1.0_1.14.imx.bb
recipes-multimedia/gstreamer/imx-gst1.0-plugin_4.4.2.bb

codeaurora.org has now been archived

[warrior] meta-freescale: migrate IMX repos from codeaurora to github

---

recipes-graphics/wayland/weston-init.bbappend

The main recipe now sets xwayland=true in weston.ini, but xwayland does not really work for mainline BSPs, the following error was observed on both imx6/imx7 machines, as follows:
```
| # gst-play-1.0 testvideo_h264_360p.mp4
| Press 'k' to see a list of keyboard shortcuts.
| Now playing testvideo_h264_360p.mp4
| X connection to :0.0 broken (explicit kill or server shutdown).
```
after removing "xwayland=true" from weston.ini, it works again.
This patch mainly aims to resolve this problem by introducing a variable INI_COMMENT_ASSIGNMENTS that the end users could set to comment a line in weston.ini.

weston-init: comment in xwayland=true for mainline BSPs

---

recipes-kernel/linux/linux-fslc_6.1.bb

Bump the kernel revision to keep in sync with master branch

linux-fslc: Bump to revision 9dd7c6bd8a02e

---

recipes-bsp/u-boot/u-boot-fslc-common_2023.04.inc

mx6sabresd: Fix extra environment settings

u-boot-fslc: bump to revision 7341fbb

---

conf/machine/include/imx-base.inc
recipes-downgrade/vulkan/vulkan-validation-layers_1.2.182.0.imx.bb

PR fixes
https://errors.yoctoproject.org/Errors/Details/707981/

add vulkan-validation-layers support

---

recipes-multimedia/imx-dsp/imx-dsp-codec-ext_2.0.5.bb
recipes-multimedia/imx-vpuwrap/imx-vpuwrap_git.bb

It now at least builds for an i.MX8QM.

Fix Build for i.MX8 Series

---

recipes-dpaa2/dce/dce_git.bb
recipes-extended/odp/odp.inc

Add SRCREV_FORMAT for dce and odp recipes

Set SRCREV_FORMAT as multiple SCMs are used

---

recipes-kernel/kernel-modules/kernel-module-imx-gpu-viv_6.4.11.p2.0+fslc.bb
recipes-kernel/kernel-modules/kernel-module-imx-gpu-viv_6.4.11.p2.0.bb

kernel-module-imx-gpu-viv: Upgrade 6.4.11.p1.0 -> 6.4.11.p2.0

---

recipes-multimedia/alsa/imx-alsa-plugins_git.bb
recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_1.22.0.imx.bb
recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_1.22.0.imx.bb
recipes-multimedia/gstreamer/gstreamer1.0-plugins-good_1.22.0.imx.bb
recipes-multimedia/gstreamer/gstreamer1.0_1.22.0.imx.bb
recipes-multimedia/gstreamer/imx-gst1.0-plugin_git.bb
recipes-multimedia/imx-codec/imx-codec_4.8.1.bb
recipes-multimedia/imx-dsp/imx-dsp-codec-ext_2.1.5.bb
recipes-multimedia/imx-dsp/imx-dsp_2.1.5.bb
recipes-multimedia/imx-parser/imx-parser_4.8.1.bb
recipes-multimedia/imx-vpuwrap/imx-vpuwrap_git.bb
recipes-multimedia/pulseaudio/pulseaudio_%.bbappend

Multimedia Update for NXP release 6.1.36-2.1.0

---

conf/machine/imx8mq-lpddr4-wevk.conf

It is based on 6.1.36_2.1.0 NXP BSP release.

imx8mq-lpddr4-wevk: Add i.MX 8 MQ LPDDR4 WEVK machine

---

recipes-bsp/imx-atf/imx-atf_2.8.bb

Update SRCREV to include lf-6.1.55-2.2.0 release changes

imx-atf: Update to lf-6.1.55-2.2.0

---

recipes-extended/jailhouse/jailhouse-imx_git.bb

Update the recipe to the BSP 6.1.55_2.2.0.

jailhouse-imx: Update the recipe to align to the NXP BSP LF6.1.55_2.2.0

---

recipes-bsp/uefi/uefi_git.bb

to point to latest commit in default branch (integration). Solves https://github.com/Freescale/meta-freescale/issues/1774

Updating uefi_git.bb SRC_URI to correct repo and changing REV 

---

recipes-bsp/firmware-imx/firmware-imx_8.23.bb

Sync firmware-imx_8.23 recipe with meta-imx-bsp layer.

Sync firmware-imx_8.23.bb with meta-imx-bsp layer

---

dynamic-layers/virtualization-layer/recipes-extended/libvirt/libvirt_%.bbappend
recipes-bsp/imx-test/imx-test_git.bb
recipes-bsp/libimxdmabuffer/libimxdmabuffer_1.1.3.bb
recipes-core/udev/udev-rules-qoriq.bb
recipes-devtools/uuu/uuu-bin_1.5.165.bb
recipes-extended/merge-files/merge-files_1.0.bb
recipes-extended/testfloat/testfloat_2a.bb
recipes-graphics/mesa/mesa-etnaviv-env_0.1.bb
recipes-graphics/wayland/weston-init.bbappend
recipes-graphics/wayland/weston_10.0.5.imx.bb
recipes-graphics/wayland/weston_12.0.3.imx.bb
recipes-multimedia/pulseaudio/pulseaudio_%.bbappend
recipes-security/optee-imx/optee-client-fslc.inc
recipes-security/optee-qoriq/optee-client.nxp.inc

This is being enforced in master oe-core

recipes: Switch WORKDIR use with UNPACKDIR

---

conf/machine/include/imx-base.inc
dynamic-layers/chromium-browser-layer/recipes-browser/chromium/chromium/chromium.patch
dynamic-layers/openembedded-layer/recipes-devtools/luajit/luajit/ppc-fixplt.patch
dynamic-layers/openembedded-layer/recipes-dpaa/fmc/fmc/0001-FMCCFGReader-improve-parameter-definition-of-functio.patch
dynamic-layers/openembedded-layer/recipes-dpaa/fmc/fmc_git.bb
dynamic-layers/qt4-layer/recipes-qt4/qt4/qt4/0001-Add-support-for-i.MX-codecs-to-phonon.patch
dynamic-layers/qt4-layer/recipes-qt4/qt4/qt4/0001-config.tests-add-DEFINES-to-compile-egl-test-with-im.patch
dynamic-layers/qt4-layer/recipes-qt4/qt4/qt4/0002-config.tests-add-DEFINES-to-compile-egl4gles1-test-w.patch
dynamic-layers/qt4-layer/recipes-qt4/qt4/qt4/0002-i.MX-video-renderer-Allow-v4l-device-from-environmen.patch
dynamic-layers/qt5-layer/recipes-qt/qt5/qtbase/0014-Add-IMX-GPU-support.patch
recipes-bsp/imx-vpu-hantro-vc/imx-vpu-hantro-vc_1.9.1.bb
recipes-bsp/imx-vpu-hantro/imx-vpu-hantro-daemon_1.1.9.bb
recipes-bsp/imx-vpu-hantro/imx-vpu-hantro_1.32.0.bb
recipes-core/udev/udev-rules-imx.bb
recipes-kernel/linux/linux-fslc_6.6.bb
recipes-multimedia/gstreamer/gst-devtools_1.22.5.imx.bb
recipes-multimedia/gstreamer/gstreamer1.0-libav_1.22.5.imx.bb
recipes-multimedia/gstreamer/gstreamer1.0-omx_%.bbappend
recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_1.22.5.imx.bb
recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_1.22.5.imx.bb
recipes-multimedia/gstreamer/gstreamer1.0-plugins-good_1.22.5.imx.bb
recipes-multimedia/gstreamer/gstreamer1.0-plugins-ugly_1.22.5.imx.bb
recipes-multimedia/gstreamer/gstreamer1.0-python_1.22.5.imx.bb
recipes-multimedia/gstreamer/gstreamer1.0-rtsp-server_1.22.5.imx.bb
recipes-multimedia/gstreamer/gstreamer1.0-vaapi_1.22.5.imx.bb
recipes-multimedia/gstreamer/imx-gst1.0-plugin_git.bb
recipes-multimedia/imx-opencl-converter/imx-opencl-converter/0001-src-ocl.c-fix-wrong-integer-type.patch
recipes-multimedia/imx-opencl-converter/imx-opencl-converter_0.2.0.bb
recipes-multimedia/imx-vpuwrap/imx-vpuwrap/0001-vpu_wrapper_hantro_encoder-add-sys-time.h-for-gettim.patch
recipes-multimedia/imx-vpuwrap/imx-vpuwrap_git.bb

Backport fixes from master to scarthgap

---

recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_1.22.5.imx.bb
recipes-multimedia/gstreamer/imx-gst1.0-plugin_git.bb

[Scarthgap] Revert backports which don't compile with GCC-13

---

recipes-bsp/imx-mkimage/imx-boot_1.0.bb

imx-boot update and fix

---

recipes-security/optee-imx/optee-client-fslc-imx.inc
recipes-security/optee-imx/optee-client-fslc.inc
recipes-security/optee-imx/optee-client_4.2.0.imx.bb
recipes-security/optee-imx/optee-os_4.2.0.imx.bb
recipes-security/optee-imx/optee-test_4.2.0.imx.bb

optee: Upgrade optee recipes from 4.0.0.imx to 4.2.0.imx

---

recipes-graphics/wayland/weston/0001-libweston-tools-Include-libgen.h-for-basename-signat.patch
recipes-graphics/wayland/weston_12.0.4.imx.bb

weston: Fix build with musl

---

recipes-kernel/linux/linux-fslc_6.11.bb

- Update linux-fslc to v6.11.3 kernel

linux-fslc: 6.11.0 -> 6.11.3

---

recipes-bsp/imx-atf/imx-atf_2.10.bb

recipes-bsp: imx-atf: Upgrade to new NXP BSP LF6.6.36_2.1.0

---

recipes-graphics/imx-gpu-viv/imx-gpu-viv-6.inc

Fixup for: #2001
Partially revert 01ce79a2

fixup! Upgrade NXP BSP to LF6.6.36_2.1.0

---

recipes-kernel/linux/linux-fslc_6.11.bb

- Update linux-fslc to v6.11.7 kernel

linux-fslc: 6.11.4 -> 6.11.7

---

recipes-kernel/linux/linux-fslc_6.12.bb

- Update linux-fslc to v6.12.1 kernel

linux-fslc: 6.11.7 -> 6.12.1

---

recipes-kernel/linux/linux-fslc-imx_6.6.bb

Please backport on Scarthgap as well

linux-fslc-imx: Fix fuse_write on imx-ocotp-fsb-s400

---

.github/workflows/update-license-file.yml
scripts/generate-license-file

Originally from meta-freescale-3rdparty.

Add workflow to automatically update LICENSE file with recipe licenses

---

recipes-kernel/linux/linux-fslc_6.12.bb

- Update linux-fslc to v6.12.4 kernel

linux-fslc: 6.12.1 -> 6.12.4

---

recipes-kernel/linux/linux-fslc_6.12.bb

- Update linux-fslc to v6.12.6 kernel

linux-fslc: 6.12.4 -> 6.12.6

---

recipes-bsp/firmware-upower/firmware-upower_1.3.1.bb

firmware-upower: SRC_URI uses PN not BPN

---

recipes-kernel/linux/linux-fslc_6.12.bb

- Update linux-fslc to v6.12.13 kernel

linux-fslc: 6.12.6 -> 6.12.13

---

recipes-bsp/firmware-imx/firmware-nxp-wifi_1.1.bb

Cherry-picks from https://github.com/Freescale/meta-freescale/pull/2135 (the bot failed because of the LICENSE file)

Forward ports to Scarthgap

---

recipes-kernel/linux/linux-fslc_6.12.bb

- Update linux-fslc to v6.12.20 kernel

linux-fslc: 6.12.13 -> 6.12.20

---

recipes-bsp/u-boot/u-boot-imx-common_2024.04.inc
recipes-bsp/u-boot/u-boot-imx_2024.04.bb

This commit update the u-boot-imx source revision and modify the recipe.

u-boot-imx: Update source revision

---

recipes-support/opencv/opencv_4.6.0.imx.bb

- don't install sample files if `PACKAGECONFIG:samples` is disabled

fix(opencv): do not try to install sample files

---

recipes-bsp/imx-vpu-hantro/imx-vpu-hantro-daemon_1.5.0.bb
recipes-bsp/imx-vpu-hantro/imx-vpu-hantro_1.36.0.bb

Update recipes  imx-vpu-hantro and  imx-vpu-hantro-daemon to latest version of rel_imx_6.12.3_1.0.0.

bump imx-vpu-hantro to rel_imx_6.12.3_1.0.0.

---

recipes-kernel/linux/linux-fslc-imx_6.6.bb

It also updates the list of commits of interest

linux-fslc-imx: Bump stable vertion up to 6.6.84

---

recipes-bsp/imx-uuc/imx-uuc_git.bb

25f65e1 ufb: fix nitpick regarding format argument 4e7a99a ufb: fix some compiler warnings
b4c1af3 ufb: pretty format source file
affb8ad .gitignore: add ufb binary
6cffbc4 Add license and copyright

imx-uuc: Bump revision to 25f65e1

---

conf/machine/imx93-14x14-lpddr4x-evk.conf

- imx93-14x14-evk-lvds-it6263.dtb
- imx93-14x14-evk-mqs.dtb

imx93-14x14-lpddr4x-evk.conf: Add 2 new DTB files to KERNEL_DEVICETREE

---

recipes-multimedia/imx-vpuwrap/imx-vpuwrap_git.bb

d8703ee Fix one coverity issue about invalid type in print 
392a152 Update LICENSE.txt to v58 according to imx-release-info 
b9b590d [configurea.ac] Update version to 4.9.3 for next release

imx-vpuwrap: Change the source branch to L6.12.y and update revision

---

recipes-kernel/kernel-modules/kernel-module-imx-gpu-viv_6.4.11.p3.2.bb
recipes-kernel/kernel-modules/kernel-module-isp-vvcam_4.2.2.25.2.bb
recipes-kernel/kernel-modules/kernel-module-nxp-wlan_git.bb
recipes-kernel/linux/linux-imx-headers_6.12.bb
recipes-kernel/linux/linux-imx_6.12.bb

Upgrade Linux kernel and headers (i.MX variants) to 6.12.20
Upgrade Linux kernel Modules to 6.12.20

Upgrade Linux kernel and headers and Modules to 6.12.20

---

recipes-bsp/imx-test/imx-test_git.bb

imx-test: upgrade to NXP 6.12.20-2.0.0 release

---

conf/machine/imx95-19x19-verdin.conf
conf/machine/include/imx-base.inc
dynamic-layers/arm-toolchain/recipes-bsp/imx-oei/imx-oei_1.0.0.bb

The Work done on Scarthgap related to iMX95 and imx-oei was only merged there, let's also synchronize it with master.

[master] Cherry-pick commits from scarthgap on imx-oei

---

conf/machine/imx95-19x19-verdin.conf
conf/machine/include/imx-base.inc
dynamic-layers/arm-toolchain/recipes-bsp/imx-oei/imx-oei_1.0.0.bb

The Work done on Scarthgap related to iMX95 and imx-oei was only merged there, let's also synchronize it with walnascar.

[WALNASCAR] Cherry-pick commits from scarthgap on imx-oei
