Freescale/meta-freescale

recipes-bsp/u-boot/u-boot-fslc_2017.07.bb
This includes the following changes:
65a6a14c mx6cuboxi: Revert "mx6cuboxi: Move CONFIG_CMD_SATA to Kconfig"
Signed-off-by: Denis Pynkin <denis.pynkin@collabora.com>
=> u-boot-fslc: Bump revision to 65a6a14c

dynamic-layers/qt5-layer/recipes-qt/qt5/qtbase_%.bbappend
* For distros enabling x11 and wayland it breaks X11 images (xfce/lxqt) for ALL
machines
* It is a setting which can be done at runtime. E.g KDE plasma does so.
* Settings like these do NOT belong into BSP layers
=> qtbase: Do not modify QT_CONFIG_FLAGS

recipes-bsp/qe-ucode/qe-ucode_git.bb
Fixes parsing warnings e.g.
qe-ucode_git.bb: python should use 4 spaces indentation, but found tabs in qe-ucode_git.bb, line 14
=> qe-ucode: Fix python indentation as per OE-Core style guidelines

conf/machine/include/imx-base.inc, recipes-bsp/imx-mkimage/imx-boot_0.2.bb, wic/imx-imx-boot-bootpart.wks
imx8 family boards use u-boot as boot loader in addition to some other
binaries. The final bootloader binary is gathered by mkimage into a file
called imx-boot.
Add the wks file to create the wic image tailored for imx8 family.
Fix the symbolic link file create to point to imx-boot (so it works for
all the imx8 flavors).
Set the wks file as default for all imx8.
Signed-off-by: Daiane Angolini <daiane.angolini@nxp.com>
=> wic:mx8: Fix the image creation

recipes-extended/vpp-core/vpp-core.bb
It depends on dpdk which is also qoriq specific
Fixes
ERROR: Nothing PROVIDES 'dpdk' (but /mnt/jenkins/workspace/yocto-world-glibc/sources/meta-freescale/recipes-extended/vpp-core/vpp-core.bb DEPENDS on or otherwise requires it)
03:58:38 dpdk was skipped: incompatible with machine qemumips (not in COMPATIBLE_MACHINE)
ERROR: Nothing RPROVIDES 'vpp-core' (but /mnt/jenkins/workspace/yocto-world-glibc/sources/meta-freescale/recipes-extended/vpp-core/vpp-core.bb RDEPENDS on or otherwise requires it)
=> vpp-core: Pin to qoriq socs

classes/fsl-dynamic-packagearch.bbclass, classes/fsl-eula-unpack.bbclass, classes/machine-overrides-extender.bbclass, classes/qoriq_build_64bit_kernel.bbclass, dynamic-layers/qt4-layer/recipes-qt4/qt4/qt4-imx-support.inc, recipes-bsp/qe-ucode/qe-ucode_git.bb, recipes-bsp/rcw/rcw_git.bb, recipes-bsp/u-boot/u-boot-qoriq_2018.09.bb, recipes-connectivity/openssl/openssl-qoriq_1.1.0g.bb, recipes-daemons/ptpd/ptpd-qoriq.bb, recipes-devtools/qemu/qemu-qoriq_git.bb, recipes-graphics/imx-gpu-viv/imx-gpu-viv-6.inc, recipes-graphics/mesa/mesa_%.bbappend, recipes-kernel/cryptodev/cryptodev-qoriq_1.9.inc, recipes-multimedia/imx-codec/imx-codec_4.4.2.bb, recipes-multimedia/imx-parser/imx-parser_4.4.2.bb
getVar() has been defaulting to expanding by default for
a long time (2016), thus remove the True option from
getVar() calls with a regex search and replace.
Search & replace made using the following command:
sed -e 's|\(d\.getVar \?\)( \?\([^,()]*\), \?True)|\1(\2)|g' \
-i $(git grep -E 'getVar ?\( ?([^,()]*), ?True\)' \
| cut -d':' -f1 \
| sort -u)
Signed-off-by: André Draszik <andre.draszik@jci.com>
=> remove True option to getVar calls

recipes-bsp/u-boot/u-boot-imx_2017.03.bb
Fix the error:
er/build/tmp/work/imx8mqevk-fslc-linux/imx-boot/0.2-r0/git/iMX8M
| cp: cannot stat '/media/daiane/TRIFORCE/yocto/master/build/tmp/deploy/images/imx8mqevk/imx-boot-tools/u-boot-nodtb.bin': No such file or directory
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_compile (log file is located at /media/daiane/TRIFORCE/yocto/master/build/tmp/work/imx8mqevk-fslc-linux/imx-boot/0.2-r0/temp/log.do_compile.27338)
Signed-off-by: Daiane Angolini <daiane.angolini@nxp.com>
=> u-boot-imx: Fix filename at install

conf/machine/imx6qdlsabreauto.conf, conf/machine/imx6qdlsabresd.conf, conf/machine/imx6ulevk.conf, conf/machine/include/imx-base.inc
The fsl distro was broken for the following machine files
because they set u-boot configuration to fslc configuration:
- imx6qdlsabreauto
- imx6qdlsabresd
- imx6ulevk
=> u-boot.imx: Add u-boot configuration for fsl

recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad/0002-opencv-Fix-build-with-opencv-3.4.5.patch, recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_1.14.imx.bb
This commit fixes the compilation of gstreamer1.0-plugins-bad which failed with :
from ../../../git/ext/opencv/gstgrabcut.cpp:90: [...]
error: conflicting declaration of C function 'CvMoments cvMoments(const cv::Moments&)
The added patch is similar to 0001-opencv-fix-build-for-opencv-3-4-2.patch but for
gstgrabcut.cpp.
=> recipes-multimedia/gstreamer: Fix compilation with OpenCV 3.4.5

conf/layer.conf
If you want to use theses branches, use the respective platform.
=> conf/layer.conf: Drop sumo and thud support

recipes-bsp/u-boot/u-boot-fslc-common_2019.04.inc, recipes-bsp/u-boot/u-boot-fslc_2019.04.bb
- Add bc-native dependency
- This commit merges remote-tracking branch 'imx/master' into 2019.04+fslc
=> u-boot-fslc-common: Bump revision to 015ff874b4

recipes-kernel/linux/linux-fslc_5.0.bb
This commit merges tag 'v5.0.5' into 5.0.x+fslc
=> linux-fslc: Bump revision to ff5bc7e34910

recipes-bsp/firmware-qca/qca-tools_2.0.1.bb
The firmware ends up in stripping errors on non-arm arches
rightly so since the binaries are arm arch specific.
=> qca-tools: Limit to arm/arm64 hosts alone

wic/imx-imx-boot-bootpart.wks.in
The i.MX8 / i.MX8X kernel's size is about 22MB.
Increase the boot partitions minimum size to have space for two kernel
images and have a constant partition size.
=> imx-imx-boot-bootpart.wks.in: increase boot partition to 64m

conf/machine/include/imx-base.inc
UBOOT_SUFFIX is already set in machine configuration files and
we can use this variable to set u-boot suffix for UBOOT_BINARY.
(cherry picked from commit 739cab987341d48e3654374ea4bbda77c72bfbe9)
Signed-off-by: Joris Offouga <offougajoris@gmail.com>
=> imx-base.inc: Use UBOOT_SUFFIX in UBOOT_BINARY variable

conf/machine/include/utilities.inc
Split alldtbs by any number of whitespace instead of just one to fix machines
with dtbs listed on multiple lines of KERNEL_DEVICETREE variable.
Signed-off-by: Diego Rondini <diego.rondini@kynetics.com>
=> utilities.inc: split by any number of whitespaces

conf/machine/include/imx-base.inc
Image container generation of imx-boot requires sha384sum also
when building for i.MX 8 targets (e.g. i.MX 8QM). Make sure it
is available for all i.MX 8 families.
Signed-off-by: Stefan Agner <stefan.agner@toradex.com>
=> imx-base: make sure sha384sum is available for all i.MX 8 variants

conf/machine/include/utilities.inc
Function make_dtb_boot_files now always returns and raises an error if a
KERNEL_DEVICETREE entry filename extension is not .dtb or .dtbo.
=> utilities.inc: fix return None type error

recipes-devtools/imx-usb-loader/imx-usb-loader_git.bb
Following changes are included:
29fa8ab imx_usb: use device found by find_imx_device
abe7f5d add support for relocatable installs
3d36c83 Fixed build for Visual Studio 2015 Express.
fe50624 imx_usb.config: add mx8mm_usb_sdp_spl.conf/mx8mm_usb_work.conf lines
f7752f4 mx8mq_usb_work.conf: use bl31-iMX8MQ-2g.bin to match branch boundary-imx_4.9.123_imx8mm_ga of imx-mkimage
8c9eee7 add mx8mm config files
4aa9809 imx_uart: fix type on help
95fe112 imx_usb: fix type on imx_usb help
eed0280 portable: use __builtin_bswap16 for BE16 if >= 4.8 GNUC
e99a093 portable: fix typo s/&&/&/ in BE16 fix
f000130 mx6ull_usb_work.conf: fix copy/paste error in comment
1041959 correct commit "portable.h: fix build with gcc older than 4.8"
bf25425 add mx6ull_usb_work.conf
9a88413 portable.h: fix build with gcc …
=> imx-usb-loader: Update to 29fa8ab revision

recipes-bsp/imx-mkimage/imx-boot_0.2.bb
The recipe do_compile task depends on virtual/bootloader which makes
sure the necessary dependencies are available once imx-boot do_compile
is executed.
Signed-off-by: Stefan Agner <stefan.agner@toradex.com>
=> imx-boot: drop dependency to u-boot

recipes-bsp/u-boot/u-boot-imx/0001-tools-allow-to-override-python.patch, recipes-bsp/u-boot/u-boot-imx_2017.03.bb
This fixes the compiler error:
| unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
| error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
=> u-boot-imx: Fix x86_64-linux-gnu-gcc compilation error

recipes-bsp/firmware-qca/qca-tools_2.0.1.bb, recipes-fsl/packagegroups/packagegroup-fsl-qca6174.bb, recipes-fsl/packagegroups/packagegroup-fsl-qca9377.bb
The prebuilt tools are for glibc based targets
no point in building for musl
=> qca-tools: Disable for musl hosts

conf/machine/include/imx-base.inc, recipes-graphics/wayland/wayland-protocols/0001-unstable-Add-alpha-compositing-protocol.patch, recipes-graphics/wayland/wayland-protocols/0002-unstable-Add-hdr10-metadata-protocol.patch, recipes-graphics/wayland/wayland-protocols_1.17.imx.bb
This is needed for GStreamer 1.16 Wayland support
=> wayland-protocols-imx: Upgrade to version 1.17

recipes-fsl/packagegroups/packagegroup-fsl-qca6174.bb, recipes-fsl/packagegroups/packagegroup-fsl-qca9377.bb, recipes-kernel/kernel-modules/kernel-module-qcacld-lea.inc
These modules rdepends on qca-tools which is currently arm/aarch64 and
glibc specific, therefore mark the recipes depending on qca-tools so as
well.
=> qca-modules: Mark arm/aarch64 specific

conf/machine/imx8mmevk.conf, conf/machine/include/imx-base.inc
Current implementation of i.MX8M Mini is utilizing generic aarch64 tune
(arch-arm64) provided from OE meta layer.
According to IMX8MMRM [1] this CPU contains Cortex-A53 cores, so this commit
sets a default tune to cortexa53-crypto.
Note, that according to [1] ARM Crypto extensions are supported, therefore it
is beneficial to set the tune to -crypto, as this also enables NEON and VFP
support in GCC (via -march and -mcpu feature modifiers, see [2]).
[1]: https://www.nxp.com/webapp/Download?colCode=IMX8MMRM
[2]: https://gcc.gnu.org/onlinedocs/gcc/AArch64-Options.html#aarch64-feature-modifiers
=> mx8mm: use cortexa53-crypto tune for imx8m mini per default

recipes-graphics/xorg-xserver/xserver-xorg/0003-Remove-check-for-useSIGIO-option.patch, recipes-graphics/xorg-xserver/xserver-xorg_%.bbappend
Addresses issue #93.
I've seen the issue with master and thud, I expect warrior to be also affected.
=> xserver-xorg: Fix X server 1.20.1 crash [YOCIMX-3280]

recipes-kernel/linux/linux-fslc_5.1.bb
This commit merge tag v5.1.15 into 5.1.x+fslc branch and apply
the following commits on top of it:
- cd1d083333e7 ARM: imx_v6_v7_defconfig: Select the OV5645 camera driver
- 4e89febe05f6 ARM: dts: imx6qdl-pico: Add OV5645 camera support
- 2af073f8b465 ARM: dts: imx6qdl-pico: Add touchscreen support
- ef23d262b6e2 drm/panel: simple: Pass flags/bus_format/bus_flags fields
- 51226c7485b6 ARM: dts: imx6qdl-pico: Add parallel LCD support
=> linux-fslc: Bump revision to cd1d08333

recipes-bsp/atf/atf_git.bb
The uefi package silently build nothing on machines that are not
supported. On machines without UEFI support this lead to a build
failure in atf as it always try to build fip_uefi.bin. Fix the
compile step to only build fip_uefi.bin if there is an UEFI image.
Signed-off-by: Alban Bedel <alban.bedel@avionic-design.de>
=> atf: Fix the build on machines that don't support UEFI

recipes-bsp/u-boot/u-boot-fslc-common_2019.07.inc
This commit merges tag v2019.07 and add the following change on top:
- 86ce1a1351 pico-imx7d: Define BOOTMENU_ENV
=> u-boot-fslc: Bump revision to 86ce1a1351

wic/imx-uboot-spl-bootpart.wks.in, wic/imx-uboot-spl.wks.in
Some boards expects a specific binary name.
Example : Pico i.MX7D required the u-boot-dtb.img file (instead of u-boot.img).
Signed-off-by: Joris Offouga <offougajoris@gmail.com>
=> wic: Fix image generation for i.MX with SPL and U-Boot

recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_1.14.imx.bb
It has been deprecated for few years and finally now
removed from oe-core
=> gstreamer1.0-plugins-bad: Drop using bluetooth bbclass

recipes-extended/dpdk/dpdk.inc, recipes-extended/vpp-core/dpdkvpp.bb, recipes-kernel/kernel-modules/kernel-module-qcacld-lea.inc
It tries to build for qemuarm and qemuarm64 as well and
fails to build e.g.
https://errors.yoctoproject.org/Errors/Details/251571/
=> kernel-module-qcacld-lea: Mark imx soc specific

recipes-kernel/linux/linux-imx-4.14.98/0001-compiler-attributes-add-support-for-copy-gcc-9.patch, recipes-kernel/linux/linux-imx-4.14.98/0002-include-linux-module.h-copy-init-exit-attrs-to-.patch, recipes-kernel/linux/linux-imx_4.14.98.bb
I have faced build error when trying master for imx8mmevk, after searching for similar issues I found issue #136 
The issue is reported by issue #136 from @dv1 
I can build my image with the patches.
Please, review the commit and let me know in case of any change.
=> linux-imx_4.14.98: Backport patches to fix building with gcc 9

conf/machine/imx6qdlsabreauto.conf, conf/machine/imx6qdlsabresd.conf, conf/machine/imx6ulevk.conf
meta-freescale commit 6be9d197386b5c3bd72023981df805d42f87684c
renamed imx-uboot-spl-bootpart.wks to imx-uboot-spl-bootpart.wks.in
The .in extension in wks files allows bitbake variables to be used in
kickstarter files. Set WKS_FILES for all machines to match this new
filename.
(cherry picked from commit da4d8a203c173f8719229df5cb525b6ed644a7c6)
=> Fix WKS_FILE to use files with .in extension

conf/machine/imx6sllevk.conf, conf/machine/imx7dsabresd.conf, conf/machine/imx7ulpevk.conf
The Broadcom support was removed by
d94f748d14d89fd2c62f03ddf181706626b0de91 so we do not need to install it
on images any more.
Signed-off-by: Daiane Angolini <daiane.angolini@nxp.com>
=> imx6sllevk:imx7dsabresd:imx7ulpevk: Remove firmware-imx-brcm dependency

conf/machine/ls1012afrwy.conf, conf/machine/ls1012ardb.conf, conf/machine/ls1021atwr.conf, conf/machine/ls1043ardb.conf, conf/machine/ls1046afrwy.conf, conf/machine/ls1046ardb.conf, conf/machine/ls1088ardb-pb.conf, conf/machine/ls1088ardb.conf, conf/machine/ls2088ardb.conf, conf/machine/lx2160ardb.conf, recipes-bsp/atf/atf_git.bb
Currently optee-os is always added as a dependency of atf on qoriq-arm64, even if atf is built without optee support. This make the build of atf impossible on board that are not supported by optee-os.
This series add the `optee` machine feature and then use it in the atf recipe to only depend on optee-os when the distro and machines support it.
=> Fix atf build on board not supported by optee-os

recipes-bsp/atf/atf-tools_git.bb, recipes-bsp/atf/atf_git.bb, recipes-bsp/ddr-phy/ddr-phy_git.bb
atf and ddr-phy recipes compile native tools from atf repository to use them during their own build process. These native builds should use Yocto's native toolchain settings. This allows `DEPENDS = "openssl-native"` to work, instead of silently using the host's openssl (which may not even be available).
For ddr-phy, it seemed most useful to split the fiptool build into a new, separate recipe: atf-tools-native.
For atf, I'm less sure whether that's possible or even useful, so for now I've just overridden HOSTCC there.
This fixes #141
=> Fix unexpected host dependencies of native tools during atf/ddr-phy builds

recipes-bsp/u-boot/u-boot-fslc-common_2019.07.inc
This commit includes the following change:
ca0ab15271 pico-imx7d: Sync all defconfigs with pico-imx7d_defconfig
=> u-boot-fslc-common: Bump revision to ca0ab15271

recipes-bsp/u-boot/u-boot-imx-mfgtool_2017.03.bb
u-boot-imx_2017.03.bb SRC_URI entry 0001-tools-allow-to-override-python.patch
cannot be found by u-boot-imx-mfgtool_2017.03.bb, which requires the first
recipe.
Add 'u-boot-imx' folder to the recipe search path so it is also able to find
the file under that folder.
Signed-off-by: Gonzalo Ruiz <Gonzalo.Ruiz@digi.com>
=> u-boot-imx-mfgtool: Add u-boot-imx to search path

recipes-bsp/atf/atf_git.bb
The atf package has the wrong architecture and a redundant definition of COMPATIBLE_MACHINE.
This series fix both problems.
=> Fix atf package architecture

recipes-graphics/mesa/mesa_%.bbappend
This allows a Weston build with swrast enabled to
successfully build and boot on imx8m-evk board.
=> mesa_%.bbappend: enable for all imx8 SoCs

recipes-devtools/cst/cst_git.bb, recipes-extended/dpdk/dpdk.inc, recipes-extended/vpp-core/dpdkvpp.bb
gen_keys when cross-built can not execute on build host
so better to depend on native version and call out native gen_keys
binary
Fixes
TOPDIR/build/tmp/work/mips32r2-yoe-linux/cst/git-r0/temp/run.do_install.29171: line 111: ./gen_keys: cannot execute binary file: Exec format error
WARNING: TOPDIR/build/tmp/work/mips32r2-yoe-linux/cst/git-r0/temp/run.do_install.29171:1 exit 126 from './gen_keys 1024'
=> cst: Fix build for target recipe and limit dpdk to imx alone

conf/machine/imx7ulpevk.conf
Setting the SOC family and the SOC in MACHINEOVERRIDES after
tune-cortexa7.inc has updated MACHINEOVERRIDES causes the tuning
overrides to have higher priority than the SOC overrides, which
is wrong.
=> imx7ulpevk.conf: Fix MACHINEOVERRIDES order

recipes-graphics/wayland/weston_5.0.0.imx.bb
Fix the variable test condition, wich is used during inclusion of
weston.ini file in the agl and non-agl builds.
Since for non-agl build there is no algprofilegraphics in the
collection, variable expands to an empty string and test condition
evaluates to true for both agl and non-agl builds.
This causes the weston.ini file to be installed regardless of whether
the agl is found or not.
Usage of a different condition check (lenght instead of empty) eliminates
this issue.
=> weston: fix the test condition for agl builds

conf/layer.conf, dynamic-layers/aglprofilegraphical/recipes-graphics/wayland/weston_5.0.0.imx.bbappend, dynamic-layers/ivi/recipes-graphics/wayland/weston_5.0.0.imx.bbappend, recipes-graphics/wayland/weston_5.0.0.imx.bb
Add a variable WESTON_INI_INSTALL_FILE to make it easy to customize
the selection of the weston.ini file.
The main recipe now performs only a generic install of the selected file.
For AGL and IVI, we use the BBFILES_DYNAMIC mechanism to specify no
file and an IVI-specific file respectively.
=> weston: Improve weston.ini selection logic

conf/machine/include/imx-base.inc, recipes-bsp/imx-atf/imx-atf_2.0.bb, recipes-bsp/imx-mkimage/imx-boot_0.2.bb, recipes-security/optee-imx/optee-client/0001-libteec-refactor-_dprintf.patch, recipes-security/optee-imx/optee-client/tee-supplicant.service, recipes-security/optee-imx/optee-client_3.2.0.imx.bb, recipes-security/optee-imx/optee-os_3.2.0.imx.bb, recipes-security/optee-imx/optee-test/0001-regression-4011-correct-potential-overflow.patch, recipes-security/optee-imx/optee-test/0001-xtest-prevent-unexpected-build-warning-with-strncpy.patch, recipes-security/optee-imx/optee-test_3.2.0.imx.bb
This pull request adds the optee iMX forks. This has been done using the PREFERRED_VERSION method for enabling the fork, similar to what is done already for Weston and Wayland imx forks. This means it can co-exist nicely in builds that include multiple bsp layers that also have optee rather than having a different package name.
Tested on iMX8M-evk board. op-tee Xtest test suite reports
+-----------------------------------------------------
16103 subtests of which 3 failed
75 test cases of which 1 failed
0 test case was skipped
TEE test application done!
=> optee imx8 support

recipes-security/optee-imx/optee-os_3.2.0.imx.bb
Fails to build on qemu
| core/arch/arm/plat-imx/conf.mk:112: *** Unsupported PLATFORM_FLAVOR "emuarm".  Stop.
=> optee-imx: Make it imx specific

recipes-kernel/linux/linux-fslc-imx/0001-compiler-attributes-add-support-for-copy-gcc-9.patch, recipes-kernel/linux/linux-fslc-imx/0002-include-linux-module.h-copy-init-exit-attrs-to-.patch, recipes-kernel/linux/linux-fslc-imx_4.9-1.0.x.bb
=> linux-fslc-imx_4.9-1.0.x: Backport patches to fix building with gcc 9

recipes-graphics/wayland/weston-init.bbappend
This logic does not work across multiple layers even OE-Core machines
dont build with it. For now its best to keep this confined to
meta-freescale machines
Idea is good but it needs to align with OE-core's methods where
currently in OE-Core we expect machines to override weston.ini
completely per machine, this logic sort of goes against it. However it
has some goodness to it, eg. adding options based on DISTRO_FEATURES
which OE-Core could have too but maybe implemented differently.
=> weston-init: Keep the logic to edit weston.ini to meta-freescale

recipes-security/optee-imx/optee-os_3.2.0.imx.bb
The platform flavor 'mx6ulzevk' has been added to Optee-OS.
Signed-off-by: Clement Faure <clement.faure@nxp.com>
=> optee-os_3.2.0: change PLATFORM_FLAVOR for imx6ulz14x14evk

recipes-security/optee-imx/optee-os_3.2.0.imx.bb
The platform flavor 'mx6ulzevk' has been added to Optee-OS.
Signed-off-by: Clement Faure <clement.faure@nxp.com>
(cherry picked from commit 0812b771626eda0ac8854b0d2bfe7e92045ffe39)
=> optee-os_3.2.0: change PLATFORM_FLAVOR for imx6ulz14x14evk [ZEUS]

recipes-kernel/kernel-modules/kernel-module-imx-gpu-viv_6.4.0.p1.0.bb, recipes-kernel/linux/linux-imx-headers_4.19.35.bb
Since the kernel update, there has been few build errors that this PR is addressing:
- Vivante Kernel module was left from kernel version 4.14.y which caused compilation error, this is solved by updating to the version available in 4.19.y kernel source tree from NXP;
- Linux header recipe had an old MD5 checksum of License file, this has been updated to match the License available in 4.19.y tree.
-- andrey
=> Finalize linux kernel update, resolve outstanding build errors

recipes-bsp/imx-test/imx-test/0001-mxc_v4l2_test-fix-compilation-error-produced-by-gcc9.patch, recipes-bsp/imx-test/imx-test_git.bb
Update the imx-test package branch to imx_4.19.35_1.1.0 which matches
the latest linux-imx kernel release (uses same branch naming).
Additionally, introduce the patch that solves trivial compilation issue
under gcc9.
=> imx-test: update test package version to imx_4.19.35_1.1.0

recipes-multimedia/alsa/imx-alsa-plugins_1.0.26.bb
With the change to linux-imx-headers 4.19.35 the build of imx-alsa-plugins
fails. Likely "linux/mxc_asrc.h" would require an include.
In the latest sources this is done in the source file which includes it.
| /workdir/oe/tmp/work/aarch64-mx8-tdx-linux/imx-alsa-plugins/1.0.26-r0/recipe-sysroot/usr/include/imx/linux/mxc_asrc.h:125:2: error: unknown type name 'snd_pcm_format_t'
|   125 |  snd_pcm_format_t input_format;
ff.
From the imx-alsa-plugins commit:
Include latest asrc_pair change for k4.14 build [YOCIMX-3558]
asrc_pair: update according to latest mxc_asrc.h
The mxc_asrc.h is updated for supporting new module on 815.
The main change is the xxx_word_width is replaced by xxx_format.
As we've switched to use git fork build, change recipe PV to 'git'.
Will upstream this recipe to …
=> imx-alsa-plugins: update to commit cde60d6

recipes-kernel/linux/linux-qoriq-rt_4.14.bb, recipes-kernel/linux/linux-qoriq_4.14.bb, recipes-kernel/linux/linux-qoriq_4.19.bb
I've tried build linux-variscite where the maintainers seem to have
copied the 'merge_delta_config' task from the linux-qoriq recipe from
meta-freescale.
When i tried to use that task to add some linux kernel config flags it
did not work. It seems like the 'do_preconfigure' task inherited by the
'fsl-kernel-localversion' class deletes all content of the '.config'
file AFTER it has been merged by the 'merge_delta_config' task.
I reordered the tasks so that merge_delta_config is run after
preconfigure:
addtask merge_delta_config before do_configure after do_patch
do_preconfigure
which solved the problem for me. The flags were then added and compiled
into the kernel.
Signed-off-by: Florian Voit <voit@zuhause-plattform.de>
=> linux-qoriq recipes: reorder merge_delta_config task

recipes-bsp/imx-mkimage/imx-boot_0.2.bb
Account for imx-seco split from firmware-imx.
Signed-off-by: Mihai Lindner <mihai.lindner@nxp.com>
=> imx-boot: Use imx-seco firmware

recipes-kernel/linux/linux-qoriq-rt_4.14.bb, recipes-kernel/linux/linux-qoriq_4.14.bb, recipes-kernel/linux/linux-qoriq_4.19.bb
This reverts commit 6e0b6f295fa7f62484b7a448fb729fbd32191a6b,
which unfortunately causes a blank build for e.g. ls2088ardb fail as that
This closes https://github.com/Freescale/meta-freescale/issues/229
=> Revert "linux-qoriq recipes: reorder merge_delta_config task"

recipes-multimedia/imx-codec/imx-codec_4.5.1.bb
- Fix issue libfslac3/ddpaudiocodec.pc conflicts
- ac3d_wrapper/src: Fix some streams cause ac3 codec hang
- common/fdlibm/: Add function pow and sqrt
- test/ua_wrapper: Add to test AAC, BSAC AudFormat
- codec_wrapper/src: Fix bug that one clip can't play
- release/lib Update oggvorbis codec for all platform
=> imx-codec: Upgrade to 4.5.1

classes/kernel-itbimage.bbclass
Signed-off-by: Darko Komljenovic <dkomljenovic@zoho.com>
=> kernel-itbimage.bbclass: Align the usage to spaces for indentation, as spaces raise the warning

README
The current link returns a 404 error.
Update the mailing list link to:
https://lists.yoctoproject.org/g/meta-freescale
Signed-off-by: Mattijs Korpershoek <mattijs.korpershoek@gmail.com>
=> readme: update mailing list url

recipes-bsp/imx-seco/imx-seco_2.3.1.bb, recipes-graphics/imx-gpu-viv/imx-gpu-viv-6.inc, recipes-graphics/imx-gpu-viv/imx-gpu-viv_6.2.4.p4.0-aarch64.bb, recipes-graphics/imx-gpu-viv/imx-gpu-viv_6.4.0.p1.0-aarch32.bb, recipes-graphics/imx-gpu-viv/imx-gpu-viv_6.4.0.p1.0-aarch64.bb, recipes-graphics/mesa/mesa_%.bbappend
1375d11c imx-seco: Fix warning SRC_URI uses PN not BPN
6465b88d mesa: Fix glcorearb.h collision with imx-gpu-viv
c352abf2 imx-gpu-viv: Upgrade to 6.4.0.p1.0
Fix for #242
=> imx-gpu-viv upgrade and some fixing

conf/machine/include/imx-base.inc
=> imx-base.inc: Do not pin weston's version when using mainline-bsp

recipes-multimedia/gstreamer/gstreamer1.0-plugins-imx_git.bb, recipes-multimedia/libimxvpuapi/libimxvpuapi_git.bb
The upstream projects were converted to use python3. Update to use that.
Fixes #243
=> Gstreamer1.0 plugins imx python3

recipes-graphics/xorg-driver/xf86-video-imx-vivante_6.4.0.p0.0.bb
Using the current HEAD fixes the following compile error:
| vivante_gal/vivante_gal_surface.c:493:38: error: 'gcvPOOL_CONTIGUOUS' undeclared (first use in this function); did you mean 'gcvSURF_CONTIGUOUS'?
|   493 |             surf->mVideoNode.mPool = gcvPOOL_CONTIGUOUS;
|       |                                      ^~~~~~~~~~~~~~~~~~
meta-fsl-bsp-release sets version to 6.4.0.p0.0 for this git hash,
follow that here.
Changelog:
MGS-4783 [#ccc] Integrate EXA patches for 6.4.0 beta
=> xf86-video-imx-vivante: fix compile by updating to 6.4.0

recipes-security/optee-imx/optee-test/0003-sock_server-fix-compilation-against-musl-sys-errno.h.patch, recipes-security/optee-imx/optee-test/0004-build-ignore-declaration-after-statement-warnings.patch, recipes-security/optee-imx/optee-test/0005-benchmark_1000-fix-compilation-against-musl-uint.patch, recipes-security/optee-imx/optee-test/0006-regression_8100-use-null-terminated-strings-with-fil.patch, recipes-security/optee-imx/optee-test_3.2.0.imx.bb
See the individual patches - all patches are simply
backports from optee upstream releases.
Signed-off-by: André Draszik <andre.draszik@jci.com>
=> optee-imx: add (backported) patches for GCC 9 & musl

recipes-graphics/drm/libdrm/0001-meson-add-libdrm-vivante-to-the-meson-meta-data.patch, recipes-graphics/drm/libdrm_2.4.99.imx.bb
The recipe updates pulled in from  upstream now builds with meson but
the libdrm imx fork does not provide meson build information. Patch the
imx fork to get the ability to build with meson.
Change the recipe to actually configure libdrm-vivante and to deploy
it into its own package.
=> libdrm imx: fix building libdrm-vivante

conf/machine/include/imx-base.inc
On mx8,
`WKS_FILE_DEPENDS_mx8 += "imx-boot"`
overrides the content of `WKS_FILE_DEPENDS` instead
of appending, causing `do_image_wic` to complain about
missing dependencies for `wic-tools`.
=> imx-base: non-overriding append for WKS_FILE_DEPENDS

recipes-extended/ovs-dpdk/ovs-dpdk_2.11.bb, recipes-extended/secure-obj/secure-obj.inc, recipes-extended/vpp-core/vpp-core.bb, recipes-graphics/imx-gpu-apitrace/imx-gpu-apitrace/0001-switch-from-python2-to-python3.patch, recipes-graphics/imx-gpu-apitrace/imx-gpu-apitrace/0002-specs-Tie-Python-2-3-conversion-loose-ends.patch, recipes-graphics/imx-gpu-apitrace/imx-gpu-apitrace/0003-scripts-Tie-Python-2-3-conversion-loose-ends.patch, recipes-graphics/imx-gpu-apitrace/imx-gpu-apitrace/0004-scripts-Tie-a-few-more-Python-2-to-3-conversion-loos.patch, recipes-graphics/imx-gpu-apitrace/imx-gpu-apitrace_7.1.0.bb, recipes-security/optee-imx/optee-client_3.2.0.imx.bb, recipes-security/optee-imx/optee-os/0001-scripts-update-scripts-to-use-python3.patch, recipes-security/optee-imx/optee-os_3.2.0.imx.bb, recipes-security/optee-imx/optee-test_3.2.0.imx.bb, recipes-security/optee/optee-client-qoriq.bb, recipes-security/optee/optee-os-qoriq_git.bb, recipes-security/optee/optee-test-qoriq_git.bb
Python2 support has been recently dropped from OE-Core due to it's effective EOL, therefore some recipes and corresponding source code packages should be updated to use Python3 BitBake classes.
@otavio @thochstein:
`optee-imx` and `imx-gpu-apitrace` has source code patches included in order to be able to use Python3 and should be applied at the source. Can you please forward them so they could be removed from the layer afterwards?
Thanks a lot!
-- andrey
=> Python3 update for meta-freescale layer

recipes-security/optee-imx/optee-test_3.2.0.imx.bb
As python2 packages are now dropped in oe-core.
=> optee-test: update to python3-pycrypto-native dependency

recipes-devtools/imx-usb-loader/imx-usb-loader_git.bb
Following changes are included:
f009770 imx_sdp: don't try to load hdmi firmware
c5c4d28 add SPDS protocol support, imx8mn(nano)
15dbbd7 tests: add pid 0x1001
353791c tests: add pids 0x0134/0x1000
06fb581 tests: pid=0x0080 is for mx6ull
6b07a0a mx8mm_usb_sdp_spl.conf/ mx8mm_usb_work.conf: s/imx-mkimage/u-boot-imx6/
b00b0e2 mx8mq_usb_work.conf: load flash.bin from u-boot-imx6 directory
bda7ab6 add mx8mq_usb_sdp_spl.conf
7984efc Moving libusb_free_device_list to get imx_usb to work on Windows.
Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>
=> imx-usb-loader: bump to revision f009770

recipes-bsp/u-boot/u-boot-fslc-common_2019.07.inc, recipes-bsp/u-boot/u-boot-qoriq-common_2019.09.inc
In upstream openembedded-core, the definition for the B variable moved from
u-boot.inc to u-boot-common.inc. None of the recipes in this layer use
upstream's u-boot-common.inc, so add the B to the *common* include files here
so u-boot continues to build. See:
http://cgit.openembedded.org/openembedded-core/commit/meta/recipes-bsp/u-boot?h=master-next&id=26023b6b0f897842fd98b3e10a8acd5b3ad8f418
This was build-tested with all the imx and ls* lx* MACHINES:
$ MACHINE=<machine> bitbake virtual/bootloader -c compile
=> fix u-boot builds

recipes-bsp/u-boot/u-boot-fslc_2019.07.bb
Currently imx6qdlsabreauto is configured to generate an lzop-compressed u-boot
fit image, therefore a lzop-native is required on the host. Add this
dependency generically since more MACHINEs might switch over in time.
=> u-boot-fslc: add lzop-native dependency

recipes-bsp/u-boot/u-boot-fslc-mxsboot_2019.07.bb
MACHINEs such as the imx23evk and imx28evk (i.e. the mxs MACHINEs)
failed to build because the recipe for u-boot-fslc-mxsboot-native wasn't
instrumented to support ${B} != ${S}, which is used as a result of inheriting
u-boot-fslc-common. In other words, the inherit was setting up ${B} != ${S},
but then u-boot-fslc-mxsboot didn't know what to do in this scenario.
=> u-boot-fslc-mxsboot-native: B!=S fix

recipes-graphics/mesa/mesa_%.bbappend
**Change 1 (cosmetic):**
We don't need to manipulate the GALLIUMDRIVERS variable. Setting the
correct PACKAGECONFIG options is enough as the main recipe handles
the rest.
**Change 2 (support Etnaviv for i.MX8)**
Currently the settings for i.MX8 are fixed to only allow to use
OSMesa for offscreen rendering. Actually etnaviv is usable on
i.MX8MM an it should therefore be possible to let Gallium be
enabled instead of unconditionally disabling it.
Therefore we introduce the USE_OSMESA_ONLY variable, that can be
set to "no" for i.MX8 if etnaviv should be used just like for i.MX6.
=> Allow to enable Etnaviv and Gallium for i.MX8

recipes-graphics/mesa/mesa_%.bbappend
This is a backport PR for https://github.com/Freescale/meta-freescale/pull/287.
Change 1 (cosmetic):
We don't need to manipulate the GALLIUMDRIVERS variable. Setting the
correct PACKAGECONFIG options is enough as the main recipe handles
the rest.
Change 2 (support Etnaviv for i.MX8)
Currently the settings for i.MX8 are fixed to only allow to use
OSMesa for offscreen rendering. Actually etnaviv is usable on
i.MX8MM an it should therefore be possible to let Gallium be
enabled instead of unconditionally disabling it.
Therefore we introduce the USE_OSMESA_ONLY variable, that can be
set to "no" for i.MX8 if etnaviv should be used just like for i.MX6.
=> Backport (Zeus): Allow to enable Etnaviv and Gallium for i.MX8

conf/machine/imx8qmmek.conf, conf/machine/include/imx-base.inc
Use the cortexa72-cortexa53-crypto tune for IMX.8 QuadMax devices
instead of the more generic aarch64. Update the QuadMax MEK machine to
require the file that provides this tune.
Signed-off-by: Joshua Watt <Joshua.Watt@garmin.com>
=> mx8qm: Use cortexa72-cortexa53 tune by default

recipes-kernel/linux/linux-imx-4.19.35/0001-perf-Make-perf-able-to-build-with-latest-libbfd.patch, recipes-kernel/linux/linux-imx_4.19.35.bb
Backport upstream patch, which solves the perf build issue when new
binutils are included.
=> linux-imx: backport patch to fix perf build with latest binutils

recipes-kernel/linux/linux-fslc-lts-4.19.bb
This upgrade includes the merge of v4.19.107 tag and backport of
upstream patch [0ada120c883d4f1f6aafd01cf0fbb10d8bbba015], which
addresses the perf build issue when latest binutils are used.
=> linux-fslc-lts-4.19: upgrade to 4.19.107

dynamic-layers/openembedded-layer/recipes-benchmark/glmark2/glmark2_%.bbappend
The default PACKAGECONFIG for glmark2 builds just fine on imxgpu3d
platforms, and doing so enables support for the drm based tests.
Signed-off-by: Joshua Watt <Joshua.Watt@garmin.com>
=> glmark2: Remove imxgpu3d PACKAGECONFIG override

dynamic-layers/openembedded-layer/recipes-benchmark/glmark2/glmark2_%.bbappend
Note that commit 7801868f is already slated for a backport to zeus #301. Thus this fix will also need to be cherry-picked into zeus.
imx-gpu-viv_6.4.0.p1.0-aarch32 does not provide virtual/libgbm and thus
a build with drm* in PACKAGECONFIG does fail.
Thus remove drm* from PACKAGECONFIG for those machines.
| ERROR: Nothing PROVIDES 'virtual/libgbm' (but .../glmark2_git.bb DEPENDS on or otherwise requires it)
| gpulib PROVIDES virtual/libgbm but was skipped: incompatible with machine
fixes: 7801868f glmark2: Remove bbappend
=> glmark2: don't build drm flavours for machines not supporting it

conf/machine/include/imx-base.inc
See similar commit fb753d427add595d9c425fab9d4720a041db1b6d:
imx-base: Enable wic.bmap image generation as default
Bmaptool is a generic tool for creating the block map (bmap) for a
file and copying files using the block map. Is faster than use dd
to flash images to SD Cards. More info about bmap here [1].
Signed-off-by: Nicola Lunghi <nick83ola@gmail.com>
=> imx-base: Enable wic.bmap image generation for mxs

recipes-bsp/u-boot/u-boot-fslc-common_2020.01.inc, recipes-bsp/u-boot/u-boot-fslc_2020.01.bb
If build dir is set in u-boot-fslc-common_2020.01.inc file,
u-boot-fslc-fw-utils can't find defconfig files.
=> u-boot-fslc: Set build dir only for u-boot recipe

recipes-kernel/linux/linux-fslc-lts-4.19.bb
This upgrade includes the merge of v4.19.107 tag and backport of
upstream patch [0ada120c883d4f1f6aafd01cf0fbb10d8bbba015], which
addresses the perf build issue when latest binutils are used.
(cherry picked from commit 61aeaa3da4251f62d4414217abb2126734c7066b)
=> zeus: linux-fslc-lts-4.19: upgrade to 4.19.107

recipes-kernel/linux/linux-fslc-lts-4.19.bb
This upgrade includes the merge of v4.19.107 tag and backport of
upstream patch [0ada120c883d4f1f6aafd01cf0fbb10d8bbba015], which
addresses the perf build issue when latest binutils are used.
(cherry picked from commit 61aeaa3da4251f62d4414217abb2126734c7066b)
=> warrior: linux-fslc-lts-4.19: upgrade to 4.19.107

recipes-graphics/imx-gpu-apitrace/imx-gpu-apitrace/0005-scripts-Tie-a-few-more-Python-2-to-3-conversion-loos.patch, recipes-graphics/imx-gpu-apitrace/imx-gpu-apitrace_7.1.0.bb
When building for fslc-x11 python code generation still fails, e.g.:
| File ".../imx-gpu-apitrace/7.1.0-r0/git/wrappers/glxtrace.py", line 70
|   print '    if(_glXGetCurrentDisplay == &glXGetCurrentDisplay ){'
Convert python2 print statements to python3.
=> imx-gpu-apitrace: x11: make python3 compatible

conf/machine/include/imx-base.inc, recipes-bsp/imx-mkimage/imx-boot_0.2.bb, recipes-bsp/u-boot/u-boot-imx-common.inc, recipes-bsp/u-boot/u-boot-imx-tools_2019.04.bb, recipes-bsp/u-boot/u-boot-imx_2019.04.bb
Splits out the IMX u-boot tools build to it's own recipe. This is
required because these are native tools and thus need to be in a -native
recipe to be properly relocated (instead of being built as part of the
target u-boot-imx recipe). If the tools aren't built in a -native
recipe, then the mkimage tool will contain a hard coded path to the
uninative program loader from the sandbox where it was first built and
this will not get corrected when restored from sstate. The result is
that the mkimage_uboot executable can't run because it's looking for a
hard coded program loader that does not exist, resulting in strange
build errors like:
./mkimage_uboot: Command not found
even though the executable is obviously in the correct location.
Signed-off-by: Joshua Watt <Joshua.Watt@garmin.com>
=> u-boot: Split out u-boot tools

conf/machine/include/imx-base.inc
The providers were incorrectly set to the -native recipe instead of the
nativesdk- recipe
=> imx-base: Fix nativesdk u-boot-tools providers

recipes-bsp/u-boot/u-boot-fslc-common_2020.01.inc, recipes-bsp/u-boot/u-boot-fslc-fw-utils_2020.01.bb
This partially revert commit 4e5c7e0d4959b027698e15565df7d3286e6860fa:
u-boot-fslc: Set build dir only for u-boot recipe
Not setting the build dir in u-boot-fslc-common is breaking the build of
u-boot-fslc-mxsboot.
Instead of unsetting ${B}, set correctly the output and source dir in make
Signed-off-by: Nicola Lunghi <nick83ola@gmail.com>
=> u-boot-fslc-fw-utils: set correctly make source build dir

recipes-bsp/u-boot/u-boot-imx-tools_2019.04.bb
When building an image for a external meta-freescale machine,
e.g. raspberrypi3, and with meta-freescale in bblayer.conf we get:
NOTE: Multiple providers are available for u-boot-mkimage-native
(u-boot-imx-tools-native, u-boot-tools-native) Consider defining
a PREFERRED_PROVIDER entry to match u-boot-mkimage-native
Set COMPATIBLE_MACHINE to reduce visibility only for mx6, mx7 and
mx8 machines.
=> u-boot-imx-tools: Make recipe visible only for mx6, mx7 and mx8 machines

recipes-bsp/u-boot/u-boot-imx-mfgtool_2019.04.bb, recipes-bsp/u-boot/u-boot-imx/0001-Add-target-to-generate-initial-environment.patch, recipes-bsp/u-boot/u-boot-imx_2019.04.bb
Since the replacement of u-boot-fw-utils with libubootenv in OE-Core,
U-Boot recipe requires an additional target to be built, which contains
the default environment.
This target has been introduced in U-Boot with version 2019.07 and is
missing in NXP fork of U-Boot source tree, therefore one patch from the
U-Boot source tree is backported in order to introduce a missing build
target.
=> u-boot-imx: resolve build issue with missing target

recipes-kernel/linux/linux-fslc_5.4.bb
tested on`warp7`:
```
root@imx7s-warp:~# uname -a
Linux imx7s-warp 5.4.30-fslc+g49dbf49dd37d #1 SMP Fri Apr 3 16:46:40 UTC 2020 armv7l GNU/Linux
```
Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>
=> linux-fslc: bump to Linux version 5.4.30

classes/fsl-eula-unpack.bbclass
Each new version of the EULA is meant to be a click
through that includes any existing packages with an
older EULA. The latest EULA is also copied in the
layer.
Capture this model in the class by listing the
known EULAs and checking that any package
has a known EULA. The new model also allows
extensibility, so new EULAs can be introduced
separately.
=> fsl-eula-unpack.bbclass: Enhance EULA model

conf/machine/imx8mqevk.conf, conf/machine/include/imx-base.inc
Like other i.MX 8M SOCs, the 8M Quad has Cortex-A53 cores
and supports ARM Crypto extensions. Enable them by default.
=> imx8mq: Add tuning for cortexa53+crypto+crc

conf/machine/imx8mqevk.conf, conf/machine/include/imx-base.inc
Like other i.MX 8M SOCs, the 8M Quad has Cortex-A53 cores
and supports ARM Crypto extensions. Enable them by default.
(cherry picked from commit 5e62f2fb476405e77388da0f2963163173e0c090)
=> [zeus] imx8mq: Add tuning for cortexa53+crypto+crc

recipes-graphics/xorg-xserver/xserver-xorg/0003-Remove-check-for-useSIGIO-option.patch, recipes-graphics/xorg-xserver/xserver-xorg_%.bbappend
Fix a crash of X server based on [b504c0](https://github.com/Freescale/meta-freescale/commit/b504c047698c4b74a859c5f23d654f348449c179).
=> xserver-xorg: Backport to fix X server 1.20.1 crash [YOCIMX-3280]

conf/machine/imx8qxpmek.conf, conf/machine/include/imx-base.inc
The i.MX 8QXP has Cortex-A35 cores plus Crypto
extensions, so enable them by default.
=> mx8qxp: Use cortexa35-crypto tuning for i.MX 8 QXP default

conf/machine/imx6qdlsabresd.conf, conf/machine/imx6sxsabreauto.conf, conf/machine/imx6ulevk.conf, conf/machine/imx6ullevk.conf, conf/machine/imx7dsabresd.conf, conf/machine/imx7ulpevk.conf, conf/machine/imx8mqevk.conf, conf/machine/imx8qmmek.conf, conf/machine/imx8qxpmek.conf
Updated kernel has some DTS files added and some dropped for various
i.MX derivatives. Those should be aligned with respective machines in
order to deliver proper DTB files, and do not fail the build for those
are missing.
Device tree files listed in respective machines are those only present
in updated 5.4 kernel release from NXP. Derivatives, which relied on
those device trees that are discarded from the new kernel release should
backport their respective files onto that update.
In other words: if after this update the DTS file used for the HW happens
to be missing - it should be manually added for that HW, since the default
version is no longer provided by NXP in their updated kernel tree.
=> machine: imx[6,7,8]: update dtb references for 5.4 kernel

classes/use-imx-headers.bbclass, recipes-bsp/imx-test/imx-test_git.bb, recipes-kernel/linux/linux-imx-headers_5.4.3.bb
Certain packages are using linux-imx-headers, which enforces them to use
NXP BSP since headers are provided from the NXP kernel tree.
Those recipes, which requires NXP kernel headers, are now including the
use-imx-headers class to make sure the correct headers package is used.
Since the introduction of separation between NXP and Mainline BSP for
certain machines, recipes which are NXP-dependent are getting their
COMPATIBLE_HOST to be marked as (null) effectively making them
incompatible with mainline BSP which is expected behavior.
By extending this restriction into the use-imx-headers class, all
recipes which inherits is (because it is required) are getting
automatically restricted to NXP BSP, hence making package NXP-dependent
much easier.
linux-imx-headers is marked as "NXP-only" but …
=> recipes-*: refine restrictions for NXP BSP

conf/machine/imx8qmmek.conf, conf/machine/include/imx-base.inc
Support for cortexa72-cortexa53 tuning is not available on zeus.
This reverts commit 9d6833f8a2e743c9907e20c8e0a0d46be9f65fd3.
=> Revert "mx8qm: Use cortexa72-cortexa53 tune by default"

recipes-security/optee-imx/optee-test/0001-use-python3-instead-of-python.patch, recipes-security/optee-imx/optee-test_3.2.0.imx.bb
This avoids build errors such as
optee-test/3.2.0.imx-r0/git/out/ta/crypt//mid_crt.c] Error 127
| /usr/bin/env: ‘python’: No such file or directory
=> optee-test_3.2.0.imx: add patch to use python3, backported from v3.8.0

recipes-graphics/imx-dpu-g2d/imx-dpu-g2d_1.8.3.bb
c27d26b MGS-5479 remove g2d_multiblit_test
9730281 MGS-5435 [QNX] G2D - child and parent window can not rotate correctly
73354dc MGS-5103 add YUV mode for BT.601 and BT.709
43ff464 MA-16215 Avoid change input parameter value in g2d_blitEx
807cf04 MGS-5403 enable G2D tile-status feature
=> imx-dpu-g2d: Upgrade to 1.8.3

recipes-multimedia/libimxvpuapi/libimxvpuapi2_2.0.1.bb
* imx6: replace mxcfb.h check with i.MX6 specific imx header check
the mcxfb.h check only makes sense with i.MX6 devices, so requiring
those for others like i.MX8 led to build errors
* update waf to 2.0.12 and switch wscript to use Python 3
* imx6: fix encoder pointer usage in vpu_EncGiveCommand() call
=> libimxvpuapi2: Update to version 2.0.1

recipes-bsp/dp-firmware-cadence/dp-firmware-cadence_git.bb
LICENSE should be "Proprieraty", not "NXP-Binary-EULA", otherwise fetch
with fsl-eula-unpack will fail.
Fixes #360
Signed-off-by: Matthias Schiffer <matthias.schiffer@tq-group.com>
=> dp-firmware-cadence: fix LICENSE

recipes-security/optee-imx/optee-test_3.2.0.imx.bb
DEFAULTTUNE is no longer aarch64 which means optee-test
build fails. Update to use the same mechanism as optee-os
recipe for setting arch.
Build now passes on imx8mq-evk and optee xtest suite
passes
+-----------------------------------------------------
16078 subtests of which 3 failed
74 test cases of which 3 failed
0 test case was skipped
TEE test application done!
=> optee-test_3.2.0.imx: fix TA_DEV_KIT_DIR is not correctly defined error

recipes-security/optee-imx/optee-test_3.2.0.imx.bb
This reverts commit 5fdac18a1f4daed214e07af014d068b7b6196f5c.
op-tee os and optee-client were reverted already. This fixes
a build failure with optee-test as one of the patches doesn't
apply to 4.19 branch.
=> Zeus optee-test fix

recipes-bsp/libimxdmabuffer/files/run-ptest, recipes-bsp/libimxdmabuffer/libimxdmabuffer_1.0.1.bb, recipes-multimedia/gstreamer/gstreamer1.0-plugins-imx_0.13.1.bb
The libximdmabuffer fix corrects the way ptest is handled.
The gstreamer1.0-plugins-imx upgrade is mainly there to have the latest features and fixes of the 0.13.x series in a properly versioned release (instead of having to rely on some git revision). After this, development focus is on the 2.x series, which supports iMX6/7/8.
=> Fix for libximdmabuffer and update for gstreamer1.0-plugins-imx

recipes-graphics/xorg-xserver/xserver-xf86-config/mx6ull/xorg.conf
The 6ULL does not have a hardware-accelerated framebuffer
device, so switch to the kernel framebuffer device.
=> xserver-xf86-config: Fix xorg.conf for 6ULL

recipes-bsp/imx-mkimage/imx-boot_0.2.bb
In imx-boot's Makefile, it downloads a native tool mkimage_uboot and
executes it, but this native tool requires libssl.so.1.1, which is in
${STAGING_LIBDIR_NATIVE}, we need set LD_LIBRARY_PATH to include it, or
it might run into following errors:
| ./mkimage_uboot -E -p 0x3000 -f u-boot.its u-boot.itb
| ./mkimage_uboot: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
Signed-off-by: Ming Liu <ming.liu@toradex.com>
=> imx-boot: fix mkimage_uboot linking issue

dynamic-layers/qt5-layer/recipes-qt/qt5/qtbase_%.bbappend
This reverts commit 1cf9efd20fd94afdd2f7484b0570c570a21b8b65.
The qtbase configure fail to find any suitable GL library, so it fails
with:
,----
| WARNING: No QPA platform plugin enabled! This will produce a Qt that
| cannot run GUI applications.  See "Platform backends" in the output of
| --help.
|
| ERROR: Feature 'opengl-desktop' was enabled, but the pre-condition
| '(config.win32 && !config.winrt && !features.opengles2
|     && (config.msvc || libs.opengl))
|  || (!config.watchos && !config.win32 && !config.wasm && libs.opengl)' failed.
|
| ERROR: Feature 'eglfs' was enabled, but the pre-condition
|   '!config.android && !config.darwin && !config.win32 && !config.wasm
|   && features.egl' failed.
`----
Fixed: #378
=> Revert "qtbase: Do not pin gles2 when using open source graphic stack"

dynamic-layers/qt5-layer/recipes-qt/qt5/qtbase/0015-Add-eglfs-to-IMX-GPU.patch
The current version of the patch causes a fuzz because of context
change.
=> qtbase: Fix patch fuzz for mkspecs/linux-oe-g++/qmake.conf

recipes-kernel/linux/linux-imx-5.4.3/0001-perf-Make-perf-able-to-build-with-latest-libbfd.patch, recipes-kernel/linux/linux-qoriq/0001-perf-Make-perf-able-to-build-with-latest-libbfd.patch, recipes-kernel/linux/linux-qoriq_5.4.bb
As it has been noted in #376, initial commit of the `perf` patch for `linux-imx` has `Upstream-Status:` tag missing, which made it hard to trace. Tag is introduced by this PR, and `linux-imx` patch is refreshed.
The same patch is also required for `linux-qoriq` kernel package, therefore a copy of the same patch is added to `linux-qoriq` folder and recipe.
This PR supersedes the PR #376 
@otavio @rehsack Let's keep the discussion started in #376 in this PR as it reflects the proposal closer to the point.
-- andrey
=> Update kernel perf patch for linux-imx and linux-qoriq packages

recipes-graphics/wayland/weston_8.0.0.imx.bb
The clients configuration for fbdev was recently removed from
meta-freescale [1] because of the following error:
```
| Run-time dependency gbm found: NO (tried pkgconfig and cmake)
|
| clients/meson.build:134:4: ERROR: Problem encountered: weston-simple-dmabuf-egl requires gbm which was not found. If you rather not build this, drop "dmabuf-egl" from simple-clients option.
```
[1] eda44e49618610c13ebe4c026cd4981b404a1543
It was also removed for non-Wayland from OE-core [2] because of the
following error in the same client dmabuf-egl:
```
clients/meson.build:141:4: ERROR: Problem encountered: weston-simple-dmabuf-egl
requires option renderer-gl which is not enabled. If you rather not build this,
drop "dmabuf-egl" from simple-clients option.
```
[2] 9b1d30810eeecb46b977c8eed68be69aef891312 …
=> weston: Restore partial clients for i.MX 6 and 7

dynamic-layers/qt5-layer/recipes-qt/qt5/qtbase/0015-Add-eglfs-to-IMX-GPU.patch
Cherry pick from commit eaefe965615070e58438b868467f7a045289d8ec for zeus
=> [cherry-pick] qtbase: Fix patch fuzz for mkspecs/linux-oe-g++/qmake.conf

conf/machine/mpc8548cds.conf, conf/machine/p1020rdb.conf, conf/machine/p2020rdb.conf, conf/machine/p2041rdb.conf, conf/machine/p3041ds.conf, conf/machine/p4080ds.conf, conf/machine/p5040ds-64b.conf, conf/machine/p5040ds.conf, conf/machine/t1024rdb-64b.conf, conf/machine/t1024rdb.conf, conf/machine/t1042d4rdb-64b.conf, conf/machine/t1042d4rdb.conf, conf/machine/t2080rdb-64b.conf, conf/machine/t2080rdb.conf, conf/machine/t4240rdb-64b.conf, conf/machine/t4240rdb.conf
Fix below issue when compiling linux-qoriq:
make[2]: *** No rule to make target 'arch/powerpc/boot/dts/p4080ds.dtb'.
=> qoriq-ppc: add fsl/ prefix in KERNEL_DEVICETREE

recipes-devtools/qemu/qemu-qoriq_4.1.0.bb
aio is required for virtio-blk-dataplane and libusb for passthrough
of usb devices.
=> qemu-qoriq: enable aio/libusb PACKAGECONFIG

recipes-bsp/atf/atf_git.bb
When optee enabled in DISTRO_FEATURES, optee-os-qoriq is added as
DEPENDS, and atf tries to find optee binary under ${DEPLOY_DIR_IMAGE}.
This has issue when do_deploy task of optee-os-qoriq does not run
before atf's do_compile.
Switch to find optee binary under ${RECIPE_SYSROOT} instead of
${DEPLOY_DIR_IMAGE}.
Steps to reproduce the issue:
$ echo 'DISTRO_FEATURES_append = " optee"' >>conf/local.conf
$ bitbake -c cleansstate atf optee-os-qoriq
$ bitbake -c install optee-os-qoriq
$ bitbake -c compile atf
| Building lx2160ardb
| Makefile:633: *** 'BL32=.../tmp/deploy/images/lx2160ardb/optee/tee_lx2160ardb.bin'
| was specified, but '.../tmp/deploy/images/lx2160ardb/optee/tee_lx2160ardb.bin'
| does not exist.  Stop.
| make: *** Waiting for unfinished jobs....
Signed-off-by: Ting Liu …
=> atf: fix build failure due to optee binary not exist

conf/machine/include/qoriq-base.inc, conf/machine/ls1043ardb.conf, conf/machine/ls1046afrwy.conf, conf/machine/ls1046ardb.conf
To build with pure mainline kernel, update dtb in KERNEL_DEVICETREE
* usdpaa is an unsupported feature now, remove dtb for it.
* add QORIQ_DEFAULT_BSP definition to easily choose which BSP to use
* dtb with -sdk suffix only exist in kernel from NXP bsp, append them on NXP bsp only.
=> qoriq: remove usdpaa dtb and relocate sdk dtb

conf/machine/include/utilities.inc
Currently, if KERNEL_DEVICETREE isn't defined `make_dtb_boot_files` function will throw an error since the parameter is a `NoneType`.
DTB files can be added outside of the kernel build with devicetree.bbclass, like this:
https://github.com/Xilinx/meta-xilinx/blob/master/meta-xilinx-bsp/recipes-bsp/device-tree/device-tree.bb
=> fix: handle if KERNEL_DEVICETREE isn't defined

recipes-devtools/cst/cst/0001-tools-Mark-struct-input_field-file_field-extern.patch, recipes-devtools/cst/cst_git.bb
Fixes
create_hdr_common.c:42: multiple definition of `file_field'; parse_utils.o:/mnt/b/yoe/master/build/tmp/work/x86_64-linux/cst-native/git-r0/git/common/parse_utils.c:29: first defined here
| collect2: error: ld returned 1 exit status
| make: *** [Makefile:131: create_hdr_isbc] Error 1
=> cst: Fix build with gcc10

conf/machine/ls1046ardb.conf
fsl-ls1046a-rdb-sdk.dtb is listed twice and one is supposed to be
fsl-ls1046a-qds-sdk.dtb. This is due to a typo in previous commit:
41c93da5a ls1043a/ls1046a: append non-upstream dtb on NXP bsp only
Fix it with fsl-ls1046a-qds-sdk.dtb.
=> ls1046ardb: fix duplicate dtb issue

classes/use-imx-headers.bbclass, recipes-kernel/linux/linux-imx-headers_5.4.3.bb
i.MX-specific headers are missing in SDK once generated via:
`bitbake <image recipe> -c populate_sdk`
This was caused by dropped `ALLOW_EMPTY` package-controlling variable which is required for this recipe in order to indicate that package can have `RDEPENDS`.
Additional `RDEPENDS` are also required by packages using new mechanisms to include `linux-imx-headers`, this allows headers to be propagated to the SDK when dependent package is included.
Introduce `ALLOW_EMPTY` in recipe and `RDEPENDS` in `use-imx-headers.bbclass` to have imx headers to be populated in the SDK.
This solves the #405
=> linux-imx-headers: fix imx headers missing in sdk

conf/machine/ls1028ardb.conf, conf/machine/ls1043ardb.conf, conf/machine/ls1046afrwy.conf, conf/machine/ls1046ardb.conf
to obtain best performance from DPDK software, dedicated dtb files are needed for ls1043a/ls1046a/ls1028a. Build them on NXP bsp only.
=> ls1043a/ls1046a/ls1028a: build dedicated dtb for dpdk

conf/machine/t2080rdb-64b.conf, conf/machine/t2080rdb.conf
For the srio_pcie boot, the DM pcie driver does not support
this feature. Remove it.
=> t2080: remove srio_pcie boot UBOOT_CONFIG

recipes-kernel/linux/linux-fslc-qoriq_5.4.bb
Updating linux-fslc (QorIQ) to v5.4.43 stable
=> Linux fslc qoriq stable 5.4.43

recipes-kernel/linux/linux-fslc-lts-4.19.bb
This commit merges tag 'v4.19.125' into 4.19.x+fslc.
=> linux-fslc-lts: Update to version v4.19.125

recipes-bsp/atf/atf-tools_git.bb, recipes-bsp/atf/atf_git.bb, recipes-bsp/ddr-phy/ddr-phy_git.bb, recipes-bsp/rcw/rcw_git.bb, recipes-bsp/u-boot/u-boot-qoriq_2019.10.bb, recipes-kernel/linux/linux-fslc-qoriq_5.4.bb, recipes-kernel/linux/linux-qoriq_5.4.bb
Updating QorIQ BSP components to LSDK-20.04-update-290520.
Merging https://github.com/Freescale/meta-freescale/pull/417 first is recommended or superfluous :)
Merging https://github.com/Freescale/linux-fslc/pull/77 and https://github.com/Freescale/linux-fslc/pull/78 first is strongly encouraged
=> QorIQ: LSDK-20.04-update-290520

recipes-kernel/linux/linux-fslc-imx_5.4.bb
Kernel repository has been updated with v5.4.42 and v5.4.43 from stable
korg + following patches are cherry-picked from linux-5.5.y branch:
285869ec9087 ARM: dts: imx6ul-kontron-n6x1x-s: Remove an obsolete comment and fix indentation
f03791085754 ARM: dts: imx6ul-kontron-n6x1x-s: Add vbus-supply and overcurrent polarity to usb nodes
67e44952c670 ARM: dts: imx6ul-kontron-n6x1x: Add 'chosen' node with 'stdout-path'
d4b105f930e2 ARM: dts: Add support for two more Kontron evalkit boards 'N6311 S' and 'N6411 S'
e778467f65d0 ARM: dts: imx6ul-kontron-n6310-s: Move common nodes to a separate file
8b39f5e53831 ARM: dts: Add support for two more Kontron SoMs N6311 and N6411
3bee262233eb ARM: dts: imx6ul-kontron-n6310: Move common SoM nodes to a separate file
40a6a98b3f38 ARM: imx: Fix boot crash if …
=> linux-fslc-imx: update to v5.4.43 + patches from 5.5.y

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Kernel repository has been updated to *v5.4.44* on both branches.
Update both `linux-fslc` and `linux-fslc-imx` to include the latest patchlevel applied.
-- andrey
=> Upgrade linux-fslc* kernel recipes with v5.4.44

recipes-graphics/wayland/weston/0003-weston-touch-calibrator-Advertise-the-touchscreen-ca.patch
Fix a following QA warning:
| WARNING: weston-5.0.0.imx-r0 do_patch: Fuzz detected:
|
| Applying patch 0003-weston-touch-calibrator-Advertise-the-touchscreen-ca.patch
| patching file weston.ini.in
| Hunk #1 succeeded at 7 with fuzz 2 (offset 4 lines).
|
| The context lines in the patches can be updated with devtool:
|
|    devtool modify weston
|    devtool finish --force-patch-refresh weston <layer_path>
|
| Don't forget to review changes done by devtool!
Signed-off-by: Ming Liu <ming.liu@toradex.com>
=> weston: fix a patch fuzz issue

conf/machine/p2041rdb.conf, conf/machine/p3041ds.conf, conf/machine/p4080ds.conf, conf/machine/p5040ds-64b.conf, conf/machine/p5040ds.conf, conf/machine/t1024rdb-64b.conf, conf/machine/t1024rdb.conf, conf/machine/t1042d4rdb-64b.conf, conf/machine/t1042d4rdb.conf, conf/machine/t2080rdb-64b.conf, conf/machine/t2080rdb.conf
Secure boot does not have DM mode support for PPC, and driver
related changes are not tested due to bandwidth limitation.
Remove secure-boot u-boot configs from the build list.
=> qoriq-ppc: not build secure-boot u-boot configs

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Kernel repository has been updated to *v5.4.45* on both branches.
Update both `linux-fslc` and `linux-fslc-imx` to include the latest patch level applied.
-- andrey
=> Upgrade linux-fslc* kernel recipes with v5.4.45

conf/machine/imx6ullevk.conf
We should avoid overriding the U-Boot and Linux kernel to imx flavour as
we might use mainline or their forks; this fixes build errors when using
fslc distros as:
,----[ Build error ]
| ERROR: Nothing PROVIDES 'virtual/kernel'
| linux-fslc-lts-4.19 PROVIDES virtual/kernel but was skipped: PREFERRED_PROVIDER_virtual/kernel set to linux-imx, not linux-fslc-lts-4.19
| linux-fslc-imx PROVIDES virtual/kernel but was skipped: incompatible with machine imx6ullevk (not in COMPATIBLE_MACHINE)
| linux-qoriq PROVIDES virtual/kernel but was skipped: incompatible with machine imx6ullevk (not in COMPATIBLE_MACHINE)
| linux-fslc PROVIDES virtual/kernel but was skipped: PREFERRED_PROVIDER_virtual/kernel set to linux-imx, not linux-fslc
| linux-imx PROVIDES virtual/kernel but was skipped: incompatible …
=> imx6ullevk: Stop forcing the U-Boot and Linux kernel to imx flavour

recipes-dpaa2/management-complex/management-complex_10.14.1.bb, recipes-dpaa2/management-complex/management-complex_10.20.4.bb
when the deploy mc_app directory is already populated, a soft link
loop from mc.itb to mc.itb will be created.
Steps to reproduce:
$ bitbake -c cleansstate management-complex
$ bitbake management-complex
$ bitbake -c deploy -f management-complex
Use 'find -type f' to exclude links.
=> management-complex: avoid soft link loop in do_deploy

recipes-bsp/u-boot/u-boot-qoriq/0001-Remove-redundant-YYLOC-global-declaration.patch, recipes-bsp/u-boot/u-boot-qoriq_2019.10.bb
Newer buildhost distributions as Fedora 32 come with GCC10+, which causes:
gcc  -isystemtmp/work/lx2160acex7-poky-linux/u-boot-qoriq/2019.10+fslgit-r0/recipe-sysroot-native/usr/include -O2 -pipe -Ltmp/work/lx2160acex7-poky-linux/u-boot-qoriq/2019.10+fslgit-r0/recipe-sysroot-native/usr/lib                         -Ltmp/work/lx2160acex7-poky-linux/u-boot-qoriq/2019.10+fslgit-r0/recipe-sysroot-native/lib                         -Wl,--enable-new-dtags                         -Wl,-rpath-link,tmp/work/lx2160acex7-poky-linux/u-boot-qoriq/2019.10+fslgit-r0/recipe-sysroot-native/usr/lib                         -Wl,-rpath-link,tmp/work/lx2160acex7-poky-linux/u-boot-qoriq/2019.10+fslgit-r0/recipe-sysroot-native/lib                         -Wl,-rpath,tmp/work/lx2160acex7-poky-linux/u-boot-qoriq/2019.1 …
=> u-boot-qoriq: fix bug with gcc10

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Kernel repository has been updated to v5.4.46 on both branches.
Update both `linux-fslc` and `linux-fslc-imx` to include the patch level applied.
-- andrey
=> Upgrade linux-fslc* kernel recipes with v5.4.46

conf/machine/imx8mmevk.conf, conf/machine/imx8mnevk.conf, conf/machine/imx8mqevk.conf
Minor fix for UBOOT_DTB_NAME, which were not renamed along with the device trees.
Signed-off-by: Antonin Godard <agodard@witekio.com>
=> imx8*.conf: remove fsl- from UBOOT_DTB_NAME

recipes-kernel/linux/linux-fslc-qoriq_5.4.bb
Update fslc maintained branch for QorIQ platforms to recent stable LTS
v5.4.51, which contains since v5.4.43:
1c54d3c15afa (tag: v5.4.51, stable/linux-5.4.y) Linux 5.4.51
8ba1913cd6ba efi: Make it possible to disable efivar_ssdt entirely
43986c32ee00 dm zoned: assign max_io_len correctly
215e562251bb x86/resctrl: Fix memory bandwidth counter width for AMD
d827fe702e07 mm, compaction: make capture control handling safe wrt interrupts
64a94c550c44 mm, compaction: fully assume capture is not NULL in compact_zone_order()
2a9278ac9c55 irqchip/gic: Atomically update affinity
7ba23593cbc5 dma-buf: Move dma_buf_release() from fops to dentry_ops
4ae695a05516 drm/amdgpu/atomfirmware: fix vram_info fetching for renoir
2b8c0876bf71 drm/amdgpu: use %u rather than %d for sclk/mclk
94de85d16b0c …
=> linux-fslc-qoriq: update to 5.4.51

recipes-kernel/linux/linux-fslc-qoriq_5.4.bb
Fix merge error introduced while fixing conflict merging 5.4.48:
d1a00c9bb1c7 dpaa2-eth: fix return codes used in ndo_setup_tc
Signed-off-by: Jens Rehsack <sno@netbsd.org>
=> linux-fslc-qoriq: fix merge error

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Kernel branches are updated to *v5.4.51* from stable korg.
Update both `linux-fslc` and `linux-fslc-imx` recipes to include the latest patchlevel applied.
-- andrey
=> Upgrade linux-fslc* kernel recipes with v5.4.51

recipes-graphics/wayland/weston-init.bbappend
8M Nano does not have 2D acceleration.
This reverts commit b3f51ab82838a67146d5b6fcf8f19d36c5efeb37.
=> Revert "weston-init: use g2d for i.MX8M Nano SoC"

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Kernel branches are updated to *v5.4.55* from stable korg.
Update both `linux-fslc` and `linux-fslc-imx` recipes to include the latest patchlevel applied.
Both branches also has patch 39efdd94e314 cherry-picked from upstream, which solves the build issue with upcoming upgrade of `binutils` to version *2.35*.
-- andrey
=> Upgrade linux-fslc* kernel recipes with v5.4.55 + patch from v5.8

recipes-kernel/linux/linux-fslc-qoriq_5.4.bb
This updates QorIQ FSLC kernel to 5.4.58 which contains:
cad17feaf0d0 Linux 5.4.58
512570b17807 nfsd: Fix NFSv4 READ on RDMA when using readv
df6aeb5235e9 ima: move APPRAISE_BOOTPARAM dependency on ARCH_POLICY to runtime
fb264505b395 tcp: apply a floor of 1 for RTT samples from TCP timestamps
848e15a8c8f6 selftests/net: relax cpu affinity requirement in msg_zerocopy test
b8f2d34f6bb5 Revert "vxlan: fix tos value before xmit"
daff7f09f341 openvswitch: Prevent kernel-infoleak in ovs_ct_put_key()
ba729a97ae54 net: thunderx: use spin_lock_bh in nicvf_set_rx_mode_task()
786a9368be8c net: gre: recompute gre csum for sctp over gre tunnels
5d791d36a49b hv_netvsc: do not use VF device if link is down
3a82f4bfd20a dpaa2-eth: Fix passing zero to 'PTR_ERR' warning
5a963aa72107 appletalk: Fix …
=> As promised - Update linux-fslc-qoriq to v5.4.58

recipes-kernel/linux/linux-fslc-imx_5.4.bb
Kernel repository has been upgraded to the v5.4.56 tag from korg
Also includes a revert to the changes applied to pm-imx6 when
v5.4.52 was merged (fixing a build failure on iMX6-based devices).
Signed-off-by: Ricardo Salveti <ricardo@foundries.io>
=> linux-fslc-imx: update to v5.4.56

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Kernel branches are updated up to and including *v5.4.58* from stable korg.
Update both `linux-fslc` and `linux-fslc-imx` recipes to include the latest patchlevel applied.
-- andrey
=> Upgrade linux-fslc* kernel recipes with v5.4.58

recipes-kernel/kernel-modules/kernel-module-imx-gpu-viv_6.4.0.p2.0+fslc.bb, recipes-kernel/kernel-modules/kernel-module-imx-gpu-viv_6.4.0.p2.4+fslc.bb
This includes the following changes:
$ git log --oneline --no-decorate 8635400..bc26dac
bc26dac Merge tag 'upstream/6.4.0.p2.0'
dda8c30 Import 6.4.0.p2.0 original version
4cc1368 Merge tag 'upstream/6.4.0.p1.0'
7107f31 Merge tag 'upstream/6.2.4.p4.8'
d227cbd Merge tag 'upstream/6.2.4.p4.4'
40956c2 Merge tag 'upstream/6.2.4.p4.2'
5e6d5e1 Merge tag 'upstream/6.2.4.p4.0'
c7092f8 Merge tag 'upstream/6.2.4.p2.3'
b271b25 Import 6.4.0.p1.0 original version
34db06d Import 6.2.4.p4.8 original version
3d22560 Import 6.2.4.p4.4 original version
fc72ef3 Import 6.2.4.p4.2 original version
7a474fd Import 6.2.4.p4.0 original version
011ecb2 Import 6.2.4.p2.3 original version
40c717b Merge tag 'upstream/6.2.4.p1.8' into boundary/master
1477635 Import 6.2.4.p1.8 original version
ce51d6a Merge tag …
=> kernel-module-imx-gpu-viv+fslc: Update to version 6.4.0.p2.4-based

recipes-bsp/imx-uuc/imx-uuc_git.bb
This includes one commit from upstream:
d6afb27 Always use ipv6 address to mount rootfs
=> imx-uuc: bump up revision from upstream

recipes-bsp/imx-vpu-hantro/imx-vpu-hantro/0001-decoder_sw-resolve-compilation-error-with-fcommon.patch, recipes-bsp/imx-vpu-hantro/imx-vpu-hantro_1.18.0.bb
GCC 10.2 is recently configured to include -fcommon per default, which
results in compilation error with multiple definitions of enum names.
Intoduce a patch which corrects double-defined enum names and resolves
compilation of the component.
Cc: Tom Hochstein <tom.hochstein@nxp.com>
=> imx-vpu-hantro: fix compilation issues with -fcommon

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Kernel branches are updated to *v5.4.61* from stable korg.
Update both `linux-fslc` and `linux-fslc-imx` recipes to include the latest patchlevel applied.
This update also includes the cherry-picked commit to address `perf` build issues for both kernels.
Fixes: #465 
-- andrey
=> Upgrade linux-fslc* kernel recipes with v5.4.61 + fix for perf build

recipes-bsp/imx-atf/imx-atf/0001-imx-Fix-missing-inclusion-of-cdefs.h.patch, recipes-bsp/imx-atf/imx-atf/0001-imx-Fix-multiple-definition-of-ipc_handle.patch, recipes-bsp/imx-atf/imx-atf_2.2.bb
Backport fixes required to fix build with -fno-common. Build failure
found when building for a imx8qx based target.
Signed-off-by: Ricardo Salveti <ricardo@foundries.io>
=> imx-atf: fix build with -fno-common

recipes-kernel/linux/linux-fslc-imx_5.4.bb
Kernel repository had patch integrated that solves the perf build issue
with latest gcc settings in upstream.
Bump up the recipe version to pick up that patch.
Update tracking information to also include patch series which was
accidentially forgotten to be entered and are present in the repository.
=> linux-fslc-imx: add patch to fix perf build issues

recipes-kernel/linux/linux-fslc-imx_5.4.bb
Upstream repository had several cherry-picks from linux-5.8.y to address
missing node in dts files for imx8mn and imx8mp machines, causing the
SoC UUID to be reported all zeroes.
Add those patches to tracking information and update commit in this
recipe.
=> linux-fslc-imx: add mx8m[n,p] uuid patches from linux-5.8.y

recipes-kernel/linux/linux-fslc-imx_5.4.bb
Kernel repository has been upgraded up to and including v5.4.62 tag from
stable korg.
Tracking information is updated with the new stable tag.
=> linux-fslc-imx: update to v5.4.62

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated to *v5.4.62* from stable korg, recipe `SRCREV` are updated to point to that version now.
`linux-fslc-imx` also included 3 patches cherry-picked from upstream, which solves the UUID readout in `soc` driver for *imx8mnevk*.
-- andrey
=> Consolidated kernel update (v5.4.62)

recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_1.16.imx.bb
OpenCV is no longer required, so remove it from PACKAGECONFIG.
=> gstreamer1.0-plugins-bad: Remove un-necessary opencv dependency

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated to *v5.4.64* from stable korg, recipe `SRCREV` are updated to point to that version now.
-- andrey
=> Consolidated kernel update (v5.4.64)

dynamic-layers/openembedded-layer/recipes-support/opencv/opencv_4.%.bbappend
In the past, i.MX gstreamer camera didn't work well with OpenCV v4l,
so v4l was disabled. Now that i.MX gstreamer is no longer using
OpenCV, v4l support can be restored.
Fixes #475
=> opencv: Drop removal of v4l support

conf/machine/imx6sxsabreauto.conf
The virtual/bootloader for this board used to be u-boot-imx which does
not include the board in COMPATIBLE_MACHINE any more, so the choice is
migrate to u-boot-fslc.
The error message:
ERROR: Nothing PROVIDES 'virtual/bootloader' (but /media/daiane/TRIFORCE/yocto/dunfell/sources/poky/meta/recipes-core/images/core-image-minimal.bb DEPENDS on or otherwise requires it)
u-boot-imx PROVIDES virtual/bootloader but was skipped: incompatible with machine imx6sxsabreauto (not in COMPATIBLE_MACHINE)
Signed-off-by: Daiane Angolini <daiane.angolini@nxp.com>
=> imx6sxsabreauto: Switch virtual/bootloader to u-boot-fslc

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated to *v5.4.65* from stable korg, recipe `SRCREV` are updated to point to that version now.
`linux-fslc-imx` recipe contains additional fix to address the build issue due to `FBINFO_MISC_USEREVENT` define has been dropped upstream.
Fixes: #484 
@thochstein Please forward the patch [bffbf24c88a75f0e0979fbd6eca034e010230e57](https://github.com/Freescale/linux-fslc/commit/bffbf24c88a75f0e0979fbd6eca034e010230e57) to your kernel team, it would be required once you would advance past *v5.4.62* from upstream.
-- andrey
=> Consolidated kernel update (v5.4.65)

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated to *v5.4.66* from stable korg, recipe `SRCREV` are updated to point to that version now.
-- andrey
=> Consolidated kernel update (v5.4.66)

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated to *v5.4.67* from stable korg, recipe `SRCREV` are updated to point to that version now.
-- andrey
=> Consolidated Kernel update (v5.4.67)

recipes-kernel/linux/linux-fslc-imx_5.4.bb
Kernel repository has been upgraded upto and including v5.4.67 tag from
korg. Tracking information is updated with the new stable tag.
This revision also contains following patch to address build issues
related to changes in upstream:
- b3d088d2f8fa fbdev: fix fbinfo flag dropped upstream
=> linux-fslc-imx: update to v5.4.67 + fix fbdev build

conf/machine/imx8mpevk.conf, conf/machine/include/imx-base.inc, recipes-bsp/firmware-imx/firmware-sof-imx_1.5.0-1.bb, recipes-bsp/imx-vpu-hantro-vc/imx-vpu-hantro-vc_1.1.0.bb, recipes-graphics/wayland/weston-init.bbappend, recipes-multimedia/libimxvpuapi/libimxvpuapi2_2.0.1.bb
This PR introduced a support for new _i.MX8M Plus_ SoC, which is introduced as a part of NXP `5.4.24-2.1.0` release.
There are few recipes, which are required for _imx8mpevk_ machine and are ported from NXP release.
This is a continuation of the #456 
@thochstein Can you please take a look at this PR and give our feedback if there are no missing pieces, which are required for _i.MX8M Plus_?
-- andrey
=> Introduce imx8mpevk machine support

recipes-graphics/wayland/weston_8.0.0.imx.bb
Commit [5a5c5dd23ea0173ef16073c3c651aec89b5a67c1] removes x11 and
wayland from PACKAGECONFIG, but when wayland with X11 distro is used -
this leaves the xwayland package config option enabled.
Without x11 and wayland in PACKAGECONFIG, xwayland cannot be enabled so
remove this config option as well.
=> weston-imx: remove also xwayland from package config

recipes-graphics/waffle/waffle/0001-meson-Add-missing-wayland-dependency-on-EGL.patch, recipes-graphics/waffle/waffle/0002-meson-Separate-surfaceless-option-from-x11.patch
Current waffle release present on the dunfell branch in upstream is
1.6.0, while master upstream version is 1.6.1.
Due to this version mismatch, patches applied on master do not apply
clean on dunfell release.
Revert commit [81262efe6e9eb8ac0ed345abccbf80233707dcc3] which resolved
patch fuzz when waffle 1.6.1 is built, and keep the old versions of
patch files which are matching waffle 1.6.0.
=> [dunfell]: waffle: revert "waffle: fix patch fuzz QA warning"

recipes-graphics/wayland/weston_8.0.0.imx.bb
@otavio @zandrey 
Related to #502
I tested it on apalis-imx6.
xterm runs under weston, i.e. the xwayland plugin is working at runtime.
I currently have to enable g2d in weston.ini as egl seems to have an issue. Otherwise weston does not start.
No fix as of yet but this is unrelated to the xwayland build.
Max
=> weston: add libxcursor to depends for xwayland

recipes-bsp/imx-mkimage/imx-boot_1.0.bb
The current imx-boot recipe has hardcoded u-boot device-tree file names.
With this change the hardcoded value is overridden with whatever is set in
UBOOT_DTB_NAME.
=> imx-boot: allow for additional/different u-boot device-tree

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated to *v5.4.69* from stable korg, recipe `SRCREV` are updated to point to that version now.
-- andrey
=> Consolidated Kernel update (v5.4.69)

conf/machine/include/imx-base.inc
We need to install the SDMA firmware for mx8mm based boards so it can
properly enable the DMA support for the SoC.
Reported-by: Brian Hutchinson <b.hutchman@gmail.com>
Change-Id: I047164568e659a532307fdedab31cdbb521fdfa1
=> imx-base.inc: Add sdma-imx7d firmware for mx8mm based boards

recipes-graphics/imx-gpu-viv/imx-gpu-viv-6.inc
The imx-gpu-viv does a very bad work regarding the soname handling of
its libraries so we need to do a lot of hacks providing '.so' files for
use by the application.
This commit revers aa552127 "imx-gpu-viv: Fix packaging for various libraries"
and apply other packaging fixes. Refer to the commit for details.
Reported-by: Gary Bisson <gary.bisson@boundarydevices.com>
=> imx-gpu-viv: Fix regression when running some userspace applications

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated to *v5.4.70* from stable korg, recipe `SRCREV` are updated to point to that version now.
-- andrey
=> Consolidated Kernel update (v5.4.70)

recipes-graphics/xorg-driver/xf86-video-imx-vivante_6.4.0.p0.0.bb
=> xf86-video-imx-vivante: Remove trailing slash from S

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated to _v5.4.71_ from stable korg, recipe `SRCREV` are updated to point to that version now.
`linux-fslc` received a separate patch to address VPU FW loading during probing.
`linux-fslc-imx` has updated versioning scheme recorded in `LOCALVERSION` to address build errors due to incompatible symbols were used (Fixes: #521).
-- andrey
=> Consolidated Kernel update (v5.4.71)

recipes-multimedia/libimxvpuapi/libimxvpuapi2_2.1.0.bb
* introduce RGB and packed YUV formats since the Hantro encoder
supports those
* remove hardware specific public headers since they only added
tiled pixel formats; instead, migrate these tiled formats into
ImxVpuApiColorFormat
* imx8 hantro decoder: reorder list of supported decoder color
formats to favor 10 bit output
* imx8 hantro decoder: clear new framebuffer fields to zero
* imx8 hantro encoder: fix segfault caused by trying to unmap
non existing staged raw frame
=> libimxvpuapi2: Update to version 2.1.0

recipes-bsp/libimxdmabuffer/libimxdmabuffer_1.0.1.bb
The i.MX8 QuadMax and QuadXPlus SoCs can use the ION allocator.
Also, if there is a DPU, then G2D will be emulated via the DPU. However,
the emulation's allocation functions are broken, so disable the G2D
allocator then.
=> libimxdmabuffer: Fix allocator packageconfigs for mx8qm and mx8qxp SoCs

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated to _v5.4.72_ from stable korg, recipe `SRCREV` are updated to point to that version now.
`linux-fslc-imx` has patch [`959ad6073277`] removed from the tracking list, as it is now covered in upstream kernel tree.
-- andrey
=> Consolidated Kernel update (v5.4.72)

recipes-bsp/imx-seco/imx-seco-libs_git.bb, recipes-bsp/imx-seco/imx-seco_3.7.1.bb
Simplify the compatibility rule, all mx8 except mx8m supports SECO.
Otherwise, some machines on the list are not upstream.
=> imx-seco: Upgrade to 3.7.1

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated to _v5.4.74_ from stable korg, recipe `SRCREV` are updated to point to that version now.
-- andrey
=> Consolidated Kernel update (v5.4.74)

recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad/0001-vulkan-Drop-use-of-VK_RESULT_BEGIN_RANGE.patch, recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_1.16.imx.bb
VK_RESULT_BEGIN_RANGE has been removed in Vulkan headers, and corresponding patch has been introduced in GStreamer.
Backport patch from upstream GStreamer to NXP fork to address compilation error for Vulkan.
@thochstein Can you take attached patch internally and apply it to NXP fork? This would be required to compile with latest Vulkan headers.
-- andrey
=> gstreamer1.0-plugins-bad: fix vulkan compilation error

recipes-bsp/imx-vpu-hantro-vc/imx-vpu-hantro-vc_1.1.0.bb
=> imx-vpu-hantro-vc: set compatible to the soc, not a specific machine

recipes-extended/tsntool/tsntool_git.bb
Changes:
b74987c tsntool: fix define some_msg in the .h file for compile error
1bd1321 cnc: fix Qbv input gate state hex value
1e76457 libtsn:tsntool: align dscpset qos/dpl field with correct nla_policy
28429eb cnc.py: correct the name of basetime in sgi for sysrepo-tsn v0.2
2618ef7 libtsn:tsntool: fix dscp parameter input
297c7c3 tsntool: fix parameter input of help and queue
=> tsntool: update to b74987c

recipes-kernel/linux/linux-fslc-imx_5.4.bb
Kernel repository has been upgraded to v5.4.75 from stable korg.
Following conflicts were resolved during merge:
----
- drivers/i2c/busses/i2c-imx.c:
Drop NXP changes, which are covered by commit [2c58d5e0c754c] from
upstream.
- drivers/net/can/flexcan.c:
Keep NXP implementation, patch [ca10989632d88] from upstream is
covered in the NXP tree.
- drivers/usb/host/xhci.h:
Fix merge fuzz for upstream commit [2600a131e1f61].
Following commits are included directly on the branch
(recipe tracking record need to carry those):
----
7642303e41c1 irq-imx-irqsteer: fix compile error if CONFIG_PM_SLEEP is not set
----
6e97ed6efa70 Linux 5.4.75
6ce4da84e5f4 staging: octeon: Drop on uncorrectable alignment or FCS error
b869f6b67274 staging: …
=> [master-next]: linux-fslc-imx: update to v5.4.75

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated to _v5.4.75_ from stable korg, recipe `SRCREV` are updated to point to that version now.
Upstream commits, resolved conflicts and additional patches are recorded in corresponding recipe commits.
_Cc:_ @MDoswaldSchiller
-- andrey
=> Consolidated Kernel update (v5.4.75)

recipes-multimedia/gstreamer/gstreamer1.0-plugins-base/0001-glupload-Add-VideoMetas-and-GLSyncMeta-to-the-raw-up.patch, recipes-multimedia/gstreamer/gstreamer1.0-plugins-base/0001-meson-viv-fb-code-must-link-against-libg2d.patch, recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_1.16.imx.bb
Add a pair of patches that's to be applied over the iMX flavor of the
gstreamer1.0-plugins-base codebase.
First patch comes from upstream, and it fixes glupload behavior by avoiding
mapping the GL buffers into CPU memory. It's only applicable to the current
MM_04.05.05_2005_L5.4.24 branch that is based on the upstream 1.16.1 release,
since the patch itself is already present in 1.16.2.
https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/-/merge_requests/444
Second patch is a fix for Meson builds that enable the viv-fb GL winsys.
When enabled, the GL plugins library should also link against libg2d since
the viv-fb code is using g2d allocators.
Signed-off-by: Zan Dobersek <zdobersek@igalia.com>
=> gstreamer1.0-plugins-base: add additional patches

recipes-kernel/linux/linux-fslc-imx_5.4.bb
Kernel repository has been upgraded to _v5.4.76_ from stable korg.
Following conflicts were resolved during merge:
----
- drivers/tty/serial/fsl_lpuart.c:
Fix merge conflict of upstream patches [86875e1d6426] and [8febdfb5973d],
which contradicted with patch [cde0cb39c0e8e] from NXP.
----
```
ec9c6b417e27 Linux 5.4.76
c3d60c695712 arm64: dts: marvell: espressobin: Add ethernet switch aliases
b7f7474b3921 perf/core: Fix a memory leak in perf_event_parse_addr_filter()
21ab13af8c50 xfs: flush for older, xfs specific ioctls
258d01b1577e PM: runtime: Resume the device earlier in __device_release_driver()
37f75c6aa8dd PM: runtime: Drop pm_runtime_clean_up_links()
874dfb5c6aa3 PM: runtime: Drop runtime PM references to supplier on link …
```
=> [master-next]: linux-fslc-imx: update to v5.4.76

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated to _v5.4.76_ from stable korg, recipe `SRCREV` are updated to point to that version now.
Upstream commits, resolved conflicts and additional patches are recorded in corresponding recipe commits.
----
For LS family: _5.4.76_ contains 2 patches from upstream that address UART FIFO mis-configuration, namely:
```
86875e1d6426 tty: serial: fsl_lpuart: LS1021A has a FIFO size of 16 words, like LS1028A
8febdfb5973d tty: serial: fsl_lpuart: add LS1028A support
```
I guess they would be needed in `linux-qoriq` tree.
_Cc:_ @rehsack 
_Cc:_ @ting-liu 
-- andrey
=> Consolidated Kernel update (v5.4.76)

recipes-kernel/linux/linux-fslc-imx_5.4.bb
Kernel repository has been upgraded to v5.4.78 from stable korg.
----
```
315443293a2d Linux 5.4.78
9fda2e762498 Convert trailing spaces and periods in path components
ebc24aeb8694 net: sch_generic: fix the missing new qdisc assignment bug
c5cf5c7b585c perf/core: Fix race in the perf_mmap_close() function
c6b1616f5472 perf scripting python: Avoid declaring function pointers with a visibility attribute
b74fe3186471 x86/speculation: Allow IBPB to be conditionally enabled on CPUs with always-on STIBP
6958fbd52e79 powerpc/603: Always fault when _PAGE_ACCESSED is not set
5af9d48acbee drm/i915: Correctly set SFC capability for video engines
6fcf4141b9a2 r8169: fix potential skb double free in an error path
78f6fac0814e tipc: fix memory …
```
=> linux-fslc-imx: update to v5.4.78

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated to _v5.4.78_ from stable korg, recipe `SRCREV` are updated to point to that version now.
Upstream commits are recorded in corresponding recipe commits.
-- andrey
=> Consolidated Kernel update (v5.4.78)

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated to _v5.4.79_ from stable korg, recipe `SRCREV` are updated to point to that version now.
Upstream commits are recorded in corresponding recipe commits.
-- andrey
=> Consolidated Kernel update (v5.4.79)

recipes-kernel/linux/linux-fslc-imx_5.4.bb
Kernel repository has been upgraded to _v5.4.79_ from stable korg.
----
```
fc8334619167 Linux 5.4.79
26c7d2883851 ACPI: GED: fix -Wformat
087c857e0131 KVM: x86: clflushopt should be treated as a no-op by emulation
7ae6f2df438d can: proc: can_remove_proc(): silence remove_proc_entry warning
1527ab7859b2 mac80211: always wind down STA state
df3305411447 Input: sunkbd - avoid use-after-free in teardown paths
cd61f14592df net: lantiq: Add locking for TX DMA channel
8cad37eb129f powerpc/8xx: Always fault when _PAGE_ACCESSED is not set
b57c75956e79 net/mlx5: Add retry mechanism to the command entry index allocation
7db82a5a4c15 net/mlx5: Fix a race when moving command interface to events mode
3fa9daaccce8 net/mlx5: poll cmd EQ in case of …
```
=> [master-next]: linux-fslc-imx: update to v5.4.79

recipes-graphics/vulkan/vulkan-loader_%.bbappend
The i.MX vulkan driver libvulkan-imx is dynamically loaded, so bitbake won't add it
to the image implicitly, and a missing library error at runtime is the result.
Add the driver explicitly.
=> Add i.MX vulkan driver to image explicitly

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated to _v5.4.80_ from stable korg, recipe `SRCREV` are updated to point to that version now.
Upstream commits and resolved conflicts  are recorded in corresponding recipe commit messages.
-- andrey
=> Consolidated Kernel update (v5.4.80)

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated up to _v5.4.81_ from stable korg, recipe `SRCREV` are updated to point to that version now.
Recipes are synchronized with [_master_] branch of this repository, and effective from this PR would deviate in `linux-fslc-imx` version due to the integration of release `5.4.47-2.2.0` from NXP.
Details of future update strategy are located in PR #571 (see _NOTE_ section).
Upstream commits and resolved conflicts  are recorded in corresponding recipe commit messages.
-- andrey
=> [dunfell]: Consolidated Kernel update (v5.4.81)

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated to _v5.4.82_ from stable korg, recipe `SRCREV` are updated to point to that version now.
-- andrey
=> Consolidated Kernel update (v5.4.82)

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated to _v5.4.82_ from stable korg, recipe `SRCREV` are updated to point to that version now.
-- andrey
=> [dunfell]: Consolidated Kernel update (v5.4.82)

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated to _v5.4.83_ from stable korg, recipe `SRCREV` are updated to point to that version now.
-- andrey
=> [dunfell]: Consolidated Kernel update (v5.4.83)

recipes-kernel/linux/linux-fslc-imx_5.4.bb
Kernel branch for `linux-fslc-imx` was updated to _v5.4.83_ from stable korg, recipe `SRCREV` is updated to point to that version now.
Upstream commits and resolved conflicts are recorded in recipe commit message.
-- andrey
=> linux-fslc-imx: update to v5.4.83

conf/machine/include/imx-base.inc
`imx-boot` is required to be provided as a dependency for `mx8m` machines in order to provide a boot container, which WIC is expecting to include into the final image.
Since the only dependency for WIC present in the layer now is targeting mx8 machine and _MACHINEOVERRIDES_EXTENDER_FILTER_OUT_ removes it when `use-mainline-bsp` is set - it leaves no 'imx-boot' container in the path of creating WIC file, and build for mx8m machines fails.
Append _WKS_FILE_DEPENDS_ to include `imx-boot` for `mx8m`, as it is required to be present regardless of the BSP flavor chosen.
Fixes: e2589ccb ("imx-base.inc: Avoid adding 'imx-boot' as dependency for all SoCs")
=> imx-base.inc: add imx-boot as a dependency for mx8m machines

recipes-bsp/mc-utils/mc-utils_git.bb
mc-utils has different folder structure for lx2162a.
Set MC_CFG and MC_FLAVOUR for it.
=> mc-utils: add support for lx2162a

recipes-bsp/ddr-phy/ddr-phy_git.bb
LX2162A is LX2160A based processor. They share the same ddr-phy binaries.
Remove override '_lx2160a' and add lx2162a into COMPATIBLE_MACHINE.
=> ddr-phy: add support for lx2162aqds

recipes-dpaa2/dce/dce_git.bb
Fix multiple definition of 'qman_version' error:
| .../dce/git-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/../../libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/10.2.0/ld: libqbman.a(qbman_portal.o):/usr/src/debug/dce/git-r0/git/lib/qbman_userspace/driver/qbman_portal.h:36: multiple definition of `qman_version'; libqbman.a(qbman_debug.o):/usr/src/debug/dce/git-r0/git/lib/qbman_userspace/driver/qbman_portal.h:36: first defined here
| collect2: error: ld returned 1 exit status
| Makefile:41: recipe for target 'bin/dce-api-perf-test' failed
| make: *** [bin/dce-api-perf-test] Error 1
=> dce/qbman_userspace: fix build issue with gcc10

recipes-extended/libpkcs11/libpkcs11/0001-fix-multiple-definition-error.patch, recipes-extended/libpkcs11/libpkcs11_git.bb
gcc10 default to -fno-common, which results in error:
| ../aarch64-fsl-linux/10.2.0/ld: /tmp/ccaL5AXA.o:.../libpkcs11/git-r0/git/app/pkcs11_app.c:23: multiple definition of `funcs'; /tmp/ccvGV0xB.o:.../app/utils.c:18: first defined here
| collect2: error: ld returned 1 exit status
| Makefile:66: recipe for target 'app' failed
| make: *** [app] Error 1
=> libpkcs11: fix multiple definition error

recipes-extended/secure-obj/secure-obj.inc
Fix:
| File "/usr/include/optee/export-user_ta/scripts/sign_encrypt.py", line 131, in main
|   from Cryptodome.Signature import pss
| ModuleNotFoundError: No module named 'Cryptodome'
=> secure-obj: DEPENDS python3-pycryptodomex-native

recipes-security/optee/optee-test-qoriq_3.8.0.bb
Fix:
| /usr/include/optee/export-user_ta/scripts/sign_encrypt.py", line 131, in main
|     from Cryptodome.Signature import pss
| ModuleNotFoundError: No module named 'Cryptodome'
=> optee-test-qoriq: DEPENDS python3-pycryptodomex-native

recipes-security/optee-imx/optee-test_3.7.0.imx.bb
Currently nothing is built for optee-test which means
do_install() fails copying xtest binary.
Align the do_compile() with upstream meta-arm optee-test recipe.
With this patch the build then completes OK.
Fixes: a66dc98
(cherry picked from commit 840176462b2ae175bc06322f32c21d5b117b673e)
=> optee-test_3.7.0.imx: fix optee-test build

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated to _v5.4.85_ from stable korg, recipe `SRCREV` are updated to point to that version now.
-- andrey
=> [dunfell]: Consolidated Kernel update (v5.4.85)

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.10.bb
Kernel branches were updated to include following versions for recipes from stable korg:
- `linux-fslc-imx`: _v5.4.85_
- `linux-fslc`: _v5.10.2_
-- andrey
=> Consolidated Kernel update (v5.4.85 + v5.10.2)

conf/machine/imx8mqevk.conf, conf/machine/imx8qmmek.conf, conf/machine/imx8qxpmek.conf, recipes-bsp/imx-atf/imx-atf_2.2.bb, recipes-bsp/imx-mkimage/imx-boot_1.0.bb
This series unifies all imx8 platforms, requiring to set both ATF_PLATFORM & IMX_BOOT_SOC_TARGET in the machine conf files.
Note that I don't believe mainline bsp works for any other platform than i.MX8MQ at this stage because of this:
```
BOOT_STAGING       = "${S}/${IMX_BOOT_SOC_TARGET}"
```
=> that doesn't work for iMX8MM/N/P I believe
=> imx-atf/mkimage: allow to use mainline bsp for all imx8 machines

recipes-graphics/xorg-driver/xf86-video-armada_git.bb
Hi,
apparrently the URL of xf86-video-armada has changed. Hope, it will stay like it is now for a while.
Kind Regards
Kay Bouché
=> xf86-video-armada: Fix no more working SRC_URI

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.10.bb
- `linux-fslc-imx`: _v5.4.88_
- `linux-fslc`: _v5.10.6_
-- andrey
=> Consolidated Kernel update (v5.4.88 + v5.10.6)

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated up to and including _v5.4.88_ from stable korg, recipe `SRCREV` are updated to point to that version now.
-- andrey
=> [dunfell]: Consolidated Kernel update (up to v5.4.88)

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.10.bb
- `linux-fslc-imx`: _v5.4.92_
- `linux-fslc`: _v5.10.10_
-- andrey
=> Consolidated Kernel update (v5.4.92 + v5.10.10)

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated up to and including _v5.4.92_ from stable korg, recipe `SRCREV` are updated to point to that version now.
-- andrey
=> [dunfell]: Consolidated Kernel update (up to v5.4.92)

recipes-bsp/firmware-imx/firmware-nxp-wifi_1.0.bb
linux-firmware package already has firmware for modules, provided in
this recipe.
Drop firmware packages for following modules:
- bcm4339
- bcm43430
- bcm43455
- bcm4356-pcie
Keep the bcm4359-pcie in the recipe as it is not yet made part of
linux-firmware package.
Add recipe description detailing the usage of this package and actions
to be taken once the firmware gets integrated upstream.
=> firmware-nxp-wifi: remove packages existing in upstream

recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_1.16.imx.bb
Hello, 
The processors without gpu (imx6ul imx6ull) support only opengl-es, gstreamer1.0-plugins-bad must also be configured with this API instead of the standard gl api. Otherwise the compilation does not pass and generate errors.
Thank you
=> gstreamer1.0-plugins-bad: Let processors with pxp chose the correct Opengl API

recipes-graphics/imx-gpu-viv/imx-gpu-viv-6.inc
Since opencv depends on virtual/opencl-icd, restore virtual/opencl-icd to the
recipes provided so imx-gpu-viv is properly selected. Fixes:
```
ERROR: Nothing PROVIDES 'virtual/opencl-icd' (but /opt/work/upstream/sources/meta-openembedded/meta-oe/recipes-support/opencv/opencv_4.5.0.bb DEPENDS on or otherwise requires it). Close matches:
virtual/libc
```
=> imx-gpu-viv: Restore virtual/opencl-icd to PROVIDES

recipes-kernel/linux/linux-fslc-qoriq_5.4.bb
*   11d4722c637a Merge pull request #232 from rehsack/5.4.y+qoriq+fslc
|\
| * f3ccdf75e260 staging: fsl-dpaa2/mac: remove unused variable
| * 322847164405 staging: fsl-dpaa2/mac: mark configurable function __maybe_unused
| * e78b4629dad4 rtc: pcf2127: apply upstream fix of initialisation
| *   a7595c24be7a Merge tag 'v5.4.92' into 5.4.y+qoriq+fslc
| |\
| | * 09f983f0c7fc Linux 5.4.92
| | * e2d69319b713 spi: cadence: cache reference clock rate during probe
| | * d04c7938d0f8 mac80211: check if atf has been disabled in __ieee80211_schedule_txq
| | * d46996cb4b16 mac80211: do not drop tx nulldata packets on encrypted links
| | * 56e8947bcf81 tipc: fix NULL deref in tipc_link_xmit()
| | * 55bac51762c3 net, sctp, filter: remap copy_from_user failure error
| | * 52e0b20c8c57 rxrpc: Fix handling …
=> linux-fslc-qoriq: update to LSDK-20.12 & 5.4.92

recipes-bsp/imx-mkimage/imx-mkimage_git.bb
Fixes
imx-mkimage-git: imx-mkimage: native/nativesdk class is not inherited last, this can result in unexpected behaviour.  [native-last]
=> imx-mkimage: Reorder inheriting native class

recipes-graphics/mesa/mesa_%.bbappend
Seems swrast won't disable hardware acceleration and is still needed to prevent
a build break in xserver-xorg.
```
| Package dri was not found in the pkg-config search path.
| Perhaps you should add the directory containing `dri.pc'
| to the PKG_CONFIG_PATH environment variable
| No package 'dri' found
```
=> mesa: Re-enable dri driver swrast for NXP BSP

conf/machine/imx8mp-evk.conf
imx-boot update 5.4.70_2.3.0 requires a new version of ddr firmware to be deployed and used for imx8mp machine (201904 -> 202006).
This is introduced in commits of imx-boot git tree:
322a834 ("MLK-24860 iMX8MP: Use 202006 DDR4 firmware")
658c54a ("MLK-24788 iMX8MP: Update LPDDR4 Firmware to 202006 version")
Update ddr firmware name to include new version in machine config file.
@otavio I've separated the DDR firmware version into a variable for 2 reasons:
1. Ease of future version upgrades
2. This variable would be re-used to filter out version extension in boot container builds
-- andrey
=> imx8mp-evk: update ddr firmware version as required by imx-boot

recipes-bsp/u-boot/u-boot-fslc-mfgtool_2020.10.bb, recipes-kernel/linux/linux-fslc-mfgtool_5.10.bb
This makes u-boot-fslc and linux-fslc support the nxp mfgtool.
=> [master] Provide u-boot-mfgtool and linux-mfgtool for fslc distros

recipes-bsp/u-boot/u-boot-fslc-mfgtool_2020.04.bb, recipes-kernel/linux/linux-fslc-mfgtool_5.4.bb
This makes u-boot-fslc and linux-fslc support the nxp mfgtool.
=> [dunfell] Provide u-boot-mfgtool and linux-mfgtool for fslc distros

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.10.bb
- `linux-fslc-imx`: _v5.4.94_
- `linux-fslc`: _v5.10.12_
-- andrey
=> Consolidated Kernel update (v5.4.94 + v5.10.12)

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated up to and including _v5.4.94_ from stable korg, recipe `SRCREV` are updated to point to that version now.
-- andrey
=> [dunfell]: Consolidated Kernel update (up to v5.4.94)

recipes-graphics/mesa/mesa_%.bbappend
On dunfell parts without DRM (i.MX 6 and 7) break because dri is enabled:
```
| meson.build:455:4: ERROR: Problem encountered: building dri drivers require at least one windowing system or classic osmesa
```
The break does not occur on master since dri is effectively disabled if no dri
drivers are configured. Disabling dri outright is still a better implementation
on master, and of course is required on dunfell.
=> mesa: Disable dri for parts without DRM

conf/machine/include/imx-base.inc, recipes-graphics/mesa/mesa_%.bbappend
This is trying to fix https://github.com/Freescale/meta-freescale/issues/509.
This is still in progress, with failure for `MACHINE=imx6qdlsabresd DISTRO=fsl-wayland`:
```
| meson.build:455:4: ERROR: Problem encountered: building dri drivers require at least one windowing system or classic osmesa
```
`DISTRO=fsl-xwayland` is building fine. `master` is building fine.
=> Dunfell: Cherry-pick mesa fixes for NXP BSP

recipes-bsp/u-boot/u-boot-fslc-mfgtool_2020.04.bb, recipes-kernel/linux/linux-fslc-mfgtool_5.4.bb
This makes `u-boot-fslc` and `linux-fslc` support the NXP mfgtool.
=> [gatesgarth] Provide u-boot-mfgtool and linux-mfgtool for fslc distros

conf/machine/include/imx-base.inc
Add a preferred provider for u-boot-mfgtool since it also has both a community and
an i.MX version.
=> imx-base.inc: Add PREFERRED_PROVIDER_u-boot-mfgtool

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.10.bb
- `linux-fslc-imx`: _v5.4.97_
- `linux-fslc`: _v5.10.15_
Boot-tested on _imx8mm-lpddr4-evk_ machine, result: **PASS**.
-- andrey
=> Consolidated Kernel update (v5.4.97 + v5.10.15)

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated up to and including _v5.4.97_ from stable korg, recipe `SRCREV` are updated to point to that version now.
Boot-tested on _imx8mmevk_ machine, result: **PASS**.
-- andrey
=> [dunfell]: Consolidated Kernel update (up to v5.4.97)

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.10.bb
- `linux-fslc-imx`: _v5.4.98_
- `linux-fslc`: _v5.10.16_
Boot-tested on _imx8mp-evk_ machine, result: **PASS**.
-- andrey
=> Consolidated Kernel update (v5.4.98 + v5.10.16)

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated up to and including _v5.4.98_ from stable korg, recipe `SRCREV` are updated to point to that version now.
Boot-tested on _imx8mpevk_ machine, result: **PASS**.
-- andrey
=> [dunfell]: Consolidated Kernel update (up to v5.4.98)

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc-lts-4.19.bb, recipes-kernel/linux/linux-fslc.inc, recipes-kernel/linux/linux-fslc_5.10.bb
Kernel recipe should define a kernel branch used in recipe via KBRANCH and not a customized variable SRCBRANCH.
KBRANCH variable is used by several OE tools (e.g. devtool) to define the checkout policy when recipe is modified to a separate user workspace.
Replace the occurrence of SRCBRANCH with KBRANCH in kernel recipes, and change fetcher URI to use KBRANCH variable for checkout.
This solves the issue reported on the [meta-freescale ML](https://lists.yoctoproject.org/g/meta-freescale/message/24352) regarding the failure to use `devtool modify linux-fslc` command.
=> linux-fslc[-imx]: use KBRANCH instead of SRCBRANCH in kernel build

recipes-graphics/imx-gpu-apitrace/imx-gpu-apitrace_9.0.0.bb
eglretrace was not available for i.MX 6 and 7 on framebuffer or wayland.
For wayland, waffle is enabled for 6 and 7, matching i.MX 8.
=> imx-gpu-apitrace: Upgrade to restore eglretrace

recipes-bsp/isp-imx/basler-camera_4.2.2.6.0.bb, recipes-bsp/isp-imx/isp-imx_4.2.2.6.0.bb, recipes-kernel/kernel-modules/kernel-module-isp-vvcam_4.2.2.6.0.bb
These recipes are really not meant for non imx architectures, therefore
pin them as such
=> basler-camera,isp-imx,kernel-module-isp-vvcam: Mark imx specific

recipes-graphics/mesa/mesa_%.bbappend
For NXP BSP, building graphics software for a part without GPU can fail with a
dependency issue:
```
ERROR: Nothing RPROVIDES 'libgl' (but /home/r60874/gatesgarth/sources/poky/meta/recipes-gnome/gtk+/gtk+3_3.24.22.bb, /home/r60874/gatesgarth/sources/poky/meta/recipes-graphics/cogl/cogl-1.0_1.22.8.bb RDEPENDS on or otherwise requires it)
```
This is fixed by adding a third case configuration using the default gallium and dri.
(cherry picked from commit 148581622b1097123f0fdb905c3167d0d6d6f5b7)
=> mesa: For i.MX parts without GPU use default gallium and dri

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.10.bb
- `linux-fslc-imx`: _v5.4.100_
- `linux-fslc`: _v5.10.18_
-- andrey
=> Consolidated Kernel update (v5.4.100 + v5.10.18)

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated up to and including _v5.4.100_ from stable korg, recipe `SRCREV` are updated to point to that version now.
-- andrey
=> [dunfell]: Consolidated Kernel update (up to v5.4.100)

recipes-bsp/imx-mkimage/imx-boot_1.0.bb, recipes-bsp/imx-mkimage/imx-mkimage_git.bb, recipes-bsp/imx-test/imx-test_git.bb, recipes-kernel/kernel-modules/kernel-module-imx-gpu-viv_6.4.3.p1.0.bb
Upstream commit 2456f523cf ("licenses: Update license file to match current SPDX names") deprecated the usage of GPL-2.0 SPDX identifier, removed GPL-2.0 license file and replaced it with GPL-2.0-only SPDX identifier and text file.
Adjust layer recipes to use new SDPX identifier and text file.
imx-test recipe has license has been re-captured to use GPL-2.0-or-later identifier, since it is required by the license text accompanying the source code repository through "GPLv2 or later" statement in COPYING file.
-- andrey
=> layer: license: fix GPL-2.0 license identifiers changed upstream

recipes-multimedia/pulseaudio/pulseaudio/imx/pulseaudio-remove-the-control-for-speaker-headphone-widge.patch
Prevents
| Applying patch pulseaudio-remove-the-control-for-speaker-headphone-widge.patch
| patching file src/modules/alsa/mixer/paths/analog-output-headphones.conf
| Hunk #1 succeeded at 88 (offset 7 lines).
| Hunk #2 succeeded at 119 (offset 14 lines).
| patching file src/modules/alsa/mixer/paths/analog-output-speaker.conf
| Hunk #1 succeeded at 91 with fuzz 2 (offset 18 lines).
| Hunk #2 succeeded at 115 (offset 22 lines).
=> pulseaudio: mx7: refresh patch against pulseaudio 14.2

recipes-bsp/firmware-imx/firmware-imx_8.10.bb
When building a eSDK, sdma-imx6q/7d files are installed by
both firmware-imx and linux-firmware causing a abort.
Prevent firmware-imx to install sdma-imx6q/7d allows
linux-firmware to install them exclusively.
Signed-off-by: Vinicius Aquino <voa.aquino@gmail.com>
=> firmware-imx: Prevent sdma-imx6q and imx7d installation

recipes-bsp/u-boot/u-boot-fslc-common_2020.10.inc
Upstream repository has been updated with following commit:
```
80c23498b4 imx8mn_ddr4_evk: Allow booting the kernel by default
```
Bump up revision in recipe to pick up patch applied.
-- andrey
=> u-boot-fslc: update revision to include mx8mn sd card fixes

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.10.bb
- `linux-fslc-imx`: _v5.4.102_
- `linux-fslc`: _v5.10.20_
-- andrey
=> Consolidated Kernel update (v5.4.102 + v5.10.20)

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated up to and including _v5.4.102_ from stable korg, recipe `SRCREV` are updated to point to that version now.
-- andrey
=> [dunfell]: Consolidated Kernel update (up to v5.4.102)

recipes-bsp/imx-vpu-hantro-vc/imx-vpu-hantro-vc_1.3.0.bb
The encoding library was not previously being installed.
=> imx-vpu-hantro-vc: add do_install function

recipes-bsp/imx-vpu-hantro-vc/imx-vpu-hantro-vc_1.2.0.bb
The encoding library was not previously being installed.
=> imx-vpu-hantro-vc: backport do_install fix

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.10.bb
- `linux-fslc-imx`: _v5.4.105_
- `linux-fslc`: _v5.10.23_
`linux-fslc` tree is also updated with `defconfig` modifications enabling `KPROBES` config options to resolve the _LTT-ng_ modules build issue.
Boot-tested on `imx8mm-lpddr4-evk` machine, result - **PASS**.
-- andrey
=> Consolidated Kernel update (v5.4.105 + [v5.10.23 + KPROBES option])

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated up to and including _v5.4.105_ from stable korg, recipe `SRCREV` are updated to point to that version now.
Boot-tested on `imx8mmevk` machine, result - **PASS**.
-- andrey
=> [dunfell]: Consolidated Kernel update (up to v5.4.105)

classes/imx-boot-container.bbclass, conf/machine/imx8mn-ddr4-evk.conf, conf/machine/imx8mp-evk.conf, conf/machine/include/imx-base.inc, conf/machine/include/imx8mm-evk.inc, conf/machine/include/imx8mn-evk.inc, recipes-bsp/firmware-imx/firmware-imx-8m_8.10.bb, recipes-bsp/imx-atf/imx-atf_2.2.bb, recipes-bsp/imx-mkimage/imx-boot_1.0.bb, recipes-bsp/u-boot/u-boot-fslc_2020.10.bb, recipes-security/optee-imx/optee-os_3.10.0.imx.bb
This PR provides a mechanism to create a full image for `mx8m` derivatives based on Community BSP (when _IMX_DEFAULT_BSP_ is set to `use-mainline-bsp`) and allows creation of runtime images that could be used on those derivatives.
Implementation provides a "boot container", which serves as a replacement of `imx-boot` package used in NXP BSP, and is populated in the final image file via new WIC template file.
Basic mechanism description can be summarized as following:
1. Machines that would like to utilize the boot container defines `boot-container` in their _MACHINEOVERRIDES_, which indicates that components required to produce a container are receiving compatibility option.
2. Machines are also **required** to define _ATF_LOAD_ADDR_ parameter, which is used in compilation process of …
=> Boot Container support for mainline BSP and mx8m machines

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.10.bb
- `linux-fslc-imx`: _v5.4.106_
- `linux-fslc`: _v5.10.24_
Upstream commits and resolved merge conflicts are recorded in corresponding recipe commit messages.
Boot-tested on `imx8mp-evk` machine, result - **PASS**.
-- andrey
=> Consolidated Kernel update (v5.4.106 + v5.10.24)

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated up to and including _v5.4.106_ from stable korg, recipe `SRCREV` are updated to point to that version now.
Upstream commits and resolved merge conflicts are recorded in corresponding recipe commit messages.
Boot-tested on `imx8mmevk` machine, result - **PASS**.
-- andrey
=> [dunfell]: Consolidated Kernel update (up to v5.4.106)

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.10.bb
- `linux-fslc-imx`: _v5.4.107_
- `linux-fslc`: _v5.10.25_
Upstream commits and resolved merge conflicts are recorded in corresponding recipe commit messages.
-- andrey
=> Consolidated Kernel update (v5.4.107 + v5.10.25)

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated to _v5.4.107_ from stable korg, recipe `SRCREV` are updated to point to that version now.
-- andrey
=> [dunfell]: Consolidated Kernel update (v5.4.107)

conf/machine/imx23evk.conf, conf/machine/imx25pdk.conf, conf/machine/imx28evk.conf, conf/machine/imx51evk.conf, conf/machine/imx53ard.conf, conf/machine/imx53qsb.conf, conf/machine/imx6qdlsabreauto.conf, conf/machine/imx6qdlsabresd.conf, conf/machine/imx6slevk.conf, conf/machine/imx6sllevk.conf, conf/machine/imx6sxsabreauto.conf, conf/machine/imx6sxsabresd.conf, conf/machine/imx6ulevk.conf, conf/machine/imx6ullevk.conf, conf/machine/imx6ulz-14x14-evk.conf, conf/machine/imx7dsabresd.conf, conf/machine/imx7ulpevk.conf, conf/machine/imx8dxl-evk.conf, conf/machine/imx8mp-evk.conf, conf/machine/imx8mq-evk.conf, conf/machine/imx8qm-mek.conf, conf/machine/include/imx-base.inc, conf/machine/include/imx8mm-evk.inc, conf/machine/include/imx8mn-evk.inc, conf/machine/include/imx8x-mek.inc, recipes-security/optee-imx/optee-os_3.10.0.imx.bb
We need to make it more obvious what is in use, when we support both bootloaders and for it we are now using the _pn suffix for both.
This also fixes the WIC_FILE depending on the choice otherwise image build fails.
=> Rework bootloader choosing logic

recipes-security/optee-imx/optee-os_3.7.0.imx.bb
New pycryptodome is a drop-in replacement for the old pycrypto module. As
pycryptodome is in oe-core/dunfell, while old pycrypto requires meta-python
from meta-openembedded collection, it's better to limit unnecessary BSP
dependencies by replacing pycrypto with pycryptodome.
For more details about corresponding upstream changes, see:
https://git.openembedded.org/openembedded-core/commit/?id=a96f815c53364b119b5743b8b7100eb5588d5cf5
https://git.openembedded.org/meta-openembedded/commit/?id=a8f3c00d8d113b46a49584682e10435157d516ca
https://git.yoctoproject.org/cgit/cgit.cgi/meta-arm/commit/?id=06b648821aa3fbbdf7c00724cf3c3cedbb4f0546
Signed-off-by: Denys Dmytriyenko <denis@denix.org>
=> optee-os.imx: replace pycrypto with pycryptodome - a drop-in replacement

dynamic-layers/ivi/recipes-graphics/wayland/weston-init/weston.ini
- Set core idle-time to 0 to align with non-IVI setting
- Add repaint-window for all i.MX 8 to support 4K display
- Add enable-overlay-view option as comment
- Enable touchscreen_calibrator
(cherry picked from commit e2abe0525384a31f54e1b1fe3ba1aac887ea3573)
=> weston-init: Update weston.ini for IVI

conf/machine/imx8mp-ddr4-evk.conf, recipes-bsp/u-boot/u-boot-imx_2020.04.bb
=> imx8mp-ddr4-evk: Set mainline BSP to use u-boot-imx for now

recipes-graphics/mesa/mesa_%.bbappend
The following error appears when building mesa with NXP BSP:
ERROR: Problem encountered: building dri drivers require at least one
windowing system or classic osmesa
Using the same imxdrm configuration to all imxgpu machines to build mesa
with IMX_DEFAULT_BSP nxp.
=> mesa: Use osmesa and swrast for all imxgpu override

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.10.bb
- `linux-fslc-imx`: _v5.4.110_
- `linux-fslc`: _v5.10.28_
-- andrey
=> Consolidated Kernel update (v5.4.110 + v5.10.28)

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated up to and including _v5.4.110_ from stable korg, recipe `SRCREV` are updated to point to that version now.
-- andrey
=> [dunfell]: Consolidated Kernel update (v5.4.110)

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.10.bb
- `linux-fslc-imx`: _v5.4.111_
- `linux-fslc`: _v5.10.29_
-- andrey
=> Consolidated Kernel update (v5.4.111 + v5.10.29)

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated up to and including _v5.4.111_ from stable korg, recipe `SRCREV` are updated to point to that version now.
-- andrey
=> [dunfell]: Consolidated Kernel update (v5.4.111)

recipes-graphics/wayland/weston-init.bbappend
Fix error "Commented setting '#use-g2d=1' not found"
when building for some imx machines.
Signed-off-by: Vinicius Aquino <voa.aquino@gmail.com>
=> weston-init: Rework uncomment function logic

conf/machine/include/imx-base.inc, recipes-bsp/u-boot/libubootenv_%.bbappend
We found some corner cases which are raised when external layers do make some fancy use of the bootloader settings. This is sometimes required and this is very hard to debug. We ended working on the required fixes which covered the known cases.
=> Fix bootloader advanced use

conf/machine/include/imx-base.inc, conf/machine/include/utilities.inc
This fixes the build case when machine does not use SPL and does not set
it. We couldn't use dynamic expansion or we trigger a recursive
expansion so we opted to use an utility function to do the proper logic.
Fixes: f98059fe ("imx-base.inc: Allow use of SPL_BINARY variable inside wic images")
=> imx-base.inc: Provide a default value for SPL_BINARY

recipes-graphics/wayland/weston-init.bbappend
Show a warning instead of raising an error when uncomment function can't
found the text. This allows using a custom weston.ini file in bbappend.
=> weston-init: Do not exit with error if uncomment function fail

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.10.bb
Kernel branches were updated to following versions for recipes from stable korg:
- `linux-fslc-imx`: _v5.4.112_
- `linux-fslc`: _v5.10.30_
-- andrey
=> Consolidated Kernel update (v5.4.112 + v5.10.30)

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated to _v5.4.112_ from stable korg, recipe `SRCREV` are updated to point to that version now.
-- andrey
=> [dunfell]: Consolidated Kernel update (v5.4.112)

recipes-bsp/uefi/uefi_git.bb
Fix USB xHC transfer polling timeout.
Set DWC3 controller as a non-coherent device, otherwise xHC will not
generate any Event TRB, causing xHC driver polling URB status timeout
during USB device enumeration.
=> uefi: update to 06e9608

recipes-devtools/qemu/qemu-qoriq_4.1.0.bb, recipes-devtools/qemu/qemu-targets.inc, recipes-devtools/qemu/qemu.inc
qemu-qoriq resues qemu.inc from oe-core. As oe-core had upgraded to 5.2.0 which
switched to meson+ninja, build error appear as qemu-qoriq version is 4.1.0.
Copy a working qemu.inc from gatesgarth branch to not break the build.
Some errors:
| stdout: Applying patch cross.patch
| patching file configure
| Hunk #1 FAILED at 6973.
| Hunk #2 FAILED at 6999.
| 2 out of 2 hunks FAILED -- rejects in file configure
| Patch cross.patch does not apply (enforce with -f)
...
| DEBUG: Executing shell function do_configure
| ERROR: unknown option --with-suffix=qemu-qoriq
=> qemu-qoriq: copy qemu.inc to not break build for 4.1.0

recipes-kernel/ceetm/ceetm/0001-use-new-api-tc_print_rate.patch, recipes-kernel/ceetm/ceetm_git.bb
Fix the build issue due to api change in iproute2:
| dpaa1_ceetm.c:637:4: error: too few arguments to function 'print_rate'
| print_rate(buf, sizeof(buf), qopt->rate);
| ^~~~~~~~~~
=> ceetm: use new api tc_print_rate from iproute2

recipes-connectivity/openssl/openssl_%.bbappend
Enable it to offload crypto operation on Qoriq platforms.
=> openssl-qoriq: enable cryptodev-linux PACKAGECONFIG

classes/fsl-kernel-localversion.bbclass
We have to ensure the task run do_kernel_metadata so the config
fragments can be applied properly.
Refs: #707.
Fixes: #733.
Fixes: 49299998 ("classes: fsl-kernel-localversion: Fix task dependency")
Fixes: c7e23876 ("linux-imx.inc: inherit kernel-yocto class")
=> classes: fsl-kernel-localversion: Fix config fragments apply

classes/kernel-itbimage.bbclass
Using spaces instead of tabs gets rid of dozens of warnings by yocto
stating:
`python should use 4 spaces indentation, but found tabs in
kernel-itbimage.bbclass`
=> Fix kernel-itbimage.bbclass indentation

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.10.bb
Kernel branches were updated to following versions for recipes from stable korg:
- `linux-fslc-imx`: _v5.4.113_
- `linux-fslc`: _v5.10.33_
-- andrey
=> Consolidated Kernel update (v5.4.113 + v5.10.31)

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated to _v5.4.113_ from stable korg, recipe `SRCREV` are updated to point to that version now.
-- andrey
=> [dunfell]: Consolidated Kernel update (v5.4.113)

recipes-bsp/imx-mkimage/imx-boot_1.0.bb
The fspi_packer.sh script uses xxd in order to generate the SPI flash
configuration header. If xxd is missing no error is produced and the
output image does not work. The log however contains the following error
messages (e.g. for iMX8MP flash_evk_flexspi target):
./../scripts/fspi_packer.sh ../scripts/fspi_header
./../scripts/fspi_packer.sh: 5: xxd: not found
dd: failed to open 'qspi-header': No such file or directory
3333+1 records in
3333+1 records out
3413776 bytes (3.4 MB, 3.3 MiB) copied, 0.00566483 s, 603 MB/s
dd: failed to open 'qspi-header.off': No such file or directory
cp: cannot stat 'qspi-header.off': No such file or directory
rm: cannot remove 'qspi-header*': No such file or directory
F(Q)SPI IMAGE PACKED
xxd is not in HOSTTOOLS or HOSTTOOLS_NONFATAL, as such the explicit …
=> imx-boot: Add dependency on xxd-native

recipes-graphics/xorg-xserver/xserver-xorg_%.bbappend
The patch 0003-Remove-check-for-useSIGIO-option.patch is applied for
both imxgpu and imxgpu2d overrides. imxgpu is enough.
=> xserver-xorg: Don't apply same patch twice

recipes-graphics/xorg-xserver/xserver-xorg_%.bbappend
- drop redundant FILESEXTRAPATHS_prepend line
- co-locate SRC_URI mods
=> xserver-xorg: Cleanup

conf/machine/ls1043ardb.conf, conf/machine/ls1046afrwy.conf, conf/machine/ls1046ardb.conf
When generating fitImage, the default configuration uses the first dtb
file in KERNEL_DEVICETREE. Change to _prepend to adjust the dtb order,
thus changing the default configuration in fitImage if using nxp BSP.
=> ls1043/ls1046: use _prepend to adjust dtb order

recipes-bsp/imx-mkimage/files/0001-mkimage_fit_atf-fix-fit-generator-node-naming.patch, recipes-bsp/imx-mkimage/imx-mkimage_git.inc
FIT node names generated by imx-mkimage script are not conformant to the latest version of mkimage tool and are caused to be skipped at parsing stage, leading to build errors.
Introduce the patch to correct generated node names (drop unit address fields and replace with names-only).
Fixes: #741 
@thochstein, can you please consider applying the patch internally?
Until the `u-boot-imx` is not switched to use _binman_, the `mkimage_fit_atf.sh` script need to be used to generate a boot container and would fail during later _its_ parsing step (like it is now reported in #741).
-- andrey
=> imx-mkimage: fix node name generations

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.10.bb
Kernel branches were updated to following versions for recipes from stable korg:
- `linux-fslc-imx`: _v5.4.114_
- `linux-fslc`: _v5.10.32_
-- andrey
=> Consolidated Kernel update (v5.4.114 + v5.10.32)

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated to _v5.4.114_ from stable korg, recipe `SRCREV` are updated to point to that version now.
-- andrey
=> [dunfell]: Consolidated Kernel update (v5.4.114)

recipes-kernel/linux/linux-fslc-imx_5.4.bb
Kernel repository has been upgraded to `rel_imx_5.4.70_2.3.2` tag from NXP tree.
Update recipe `SRCREV` to point to new version.
Upstream commits are recorded in corresponding recipe commit message.
-- andrey
Link: https://source.codeaurora.org/external/imx/linux-imx/tag/?h=rel_imx_5.4.70_2.3.2
=> Kernel update (NXP rel_imx_5.4.70_2.3.2)

recipes-bsp/u-boot/u-boot-imx-common.inc, recipes-bsp/u-boot/u-boot-imx_2020.04.bb
Includes following commits:
185bdaaaf5 MA-18534 imx8mp: Enable trusty for powersave config
30549fb526 MA-18346-11 Android refine power on imx8mp board
42ed8fa287 MA-18422 Locate the misc partition by name
35ab562a3b LFU-15 Fix using uninitialized value
5b339f5614 MA-18352-6 Enable device IDs provision
c3acd3ca3a MA-18352-5 Support device IDs provision
970305d9f1 MA-18458 Sync configs for Android 11 release
933b8ef869 MA-18406 Fix panic when provision keys on boards without rpmb key
0fffe00758 MA-16954 set partition type to efi after flash gpt partition
=> u-boot-imx: Update for NXP release 5.4.70-2.3.2

recipes-graphics/imx-gpu-viv/imx-gpu-viv-6.inc, recipes-graphics/wayland/weston_9.0.0.imx.bb
This fixes two issues that caused weston to not work. The second one is particularly noteworthy since it partially reverts a previous commit. @thochstein , can you take a look as well, since that previous commit was yours? When I used strace on weston to find out what's wrong, I noticed attempts at accessing `/dev/galcore`, which just wasn't present. Adding the GPU kernel module adds that device node, fixing the second issue.
=> Fixes for weston and gpu drivers

recipes-support/opencv/opencv_4.5.2.imx.bb
- Upgrade to the 4.5.2 i.MX fork.
- Drop the redundant PV assignment
- Adapt the i.MX test packageconfig now that upstream also has one
=> opencv: Upgrade to 4.5.2.imx

recipes-multimedia/gstreamer/gstreamer1.0-ptest.inc
The gstreamer ptest on oe-core are updated and drop the gstreamer1.0-ptest.inc that is required on meta-freescale
gstreamer1.0: update ptest patch
https://git.yoctoproject.org/cgit/cgit.cgi/poky/commit/?h=master&id=30f3691c3f6fa5a7448220a58b67b4ee6ac9fdff
=> gstreamer: backport gstreamer ptest from oe-core

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.10.bb
- `linux-fslc-imx`: _v5.4.116_
- `linux-fslc`: _v5.10.34_
-- andrey
=> Consolidated Kernel update (v5.4.116 + v5.10.34)

recipes-bsp/isp-imx/basler-camera_4.2.2.11.0.bb, recipes-bsp/isp-imx/isp-imx_4.2.2.11.0.bb, recipes-kernel/kernel-modules/kernel-module-isp-vvcam_4.2.2.11.0.bb
The basler camera support is for 8M Plus SOC only.
(cherry picked from commit 7bfd1773f586a79be8abedf36e04c46b77c7c73c)
=> basler-camera, isp: Fix compatibility for 8M Plus only

recipes-bsp/u-boot/u-boot-fslc-common_2021.07.inc
U-Boot repository has been upgraded to `v2021.07-rc2` from _DENX_ repository.
Upstream commits are recorded in corresponding recipe commit message.
Link: https://lists.denx.de/pipermail/u-boot/2021-May/449442.html
-- andrey
=> u-boot-fslc: update to v2021.07-rc2

recipes-bsp/u-boot/u-boot-fslc-common_2021.07.inc, recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc-lts_5.10.bb, recipes-kernel/linux/linux-fslc_5.12.bb
- `linux-fslc-imx`: _v5.4.118_
- `linux-fslc-lts`: _v5.10.36_
- `linux-fslc`: _v5.12.3_
-- andrey
=> Consolidated Kernel update (v5.4.118 + v5.10.36 + 5.12.3)

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc-lts_5.10.bb, recipes-kernel/linux/linux-fslc_5.12.bb
- `linux-fslc-imx`: _v5.4.119_
- `linux-fslc-lts`: _v5.10.37_
- `linux-fslc`: _v5.12.4_
-- andrey
=> Consolidated Kernel update (v5.4.119 + v5.10.37 + 5.12.4)

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated up to and including _v5.4.119_ from stable korg, recipe `SRCREV` are updated to point to that version now.
-- andrey
=> [dunfell]: Consolidated Kernel update (up to v5.4.119)

recipes-graphics/wayland/weston-init.bbappend
affects the following SoCs:
-mx6q
-mx6dl
-mx6sx
-mx6sl
-mx7ulp
-mx8qm
-mx8mm
-mx8mp
-mx8qxp
Signed-off-by: Chris Dimich <Chris.Dimich@boundarydevices.com>
=> weston-init: uncomment use-g2d=1 based on imxgpu2d MACHINEOVERRIDE

conf/machine/imx8dx-mek.conf, conf/machine/imx8qxp-mek.conf, conf/machine/include/imx8x-mek.inc
The values for ATF_PLATFORM and IMX_BOOT_SOC_TARGET need to be set
in the machine config file directly, as they are not shared with
imx8qxp-mek and are now removed from the include file.
=> imx8dx-mek: Fix ATF_PLATFORM and IMX_BOOT_SOC_TARGET

recipes-bsp/u-boot/u-boot-fslc-common_2021.07.inc
U-Boot repository has been upgraded to `v2021.07-rc3` from _DENX_ repository.
Upstream commits are recorded in corresponding recipe commit message.
Link: https://lists.denx.de/pipermail/u-boot/2021-May/450703.html
-- andrey
=> u-boot-fslc: update to v2021.07-rc3

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc-lts_5.10.bb, recipes-kernel/linux/linux-fslc_5.12.bb
- `linux-fslc-imx`: _v5.4.121_
- `linux-fslc-lts`: _v5.10.39_
- `linux-fslc`: _v5.12.6_
-- andrey
=> Consolidated Kernel update (v5.4.121 + v5.10.39 + 5.12.6)

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc-lts_5.10.bb, recipes-kernel/linux/linux-fslc_5.12.bb
- `linux-fslc-imx`: _v5.4.122_
- `linux-fslc-lts`: _v5.10.40_
- `linux-fslc`: _v5.12.7_
`linux-fslc-imx` received a commit `ff9d9347c331 ("mmc: core: fix missing reserved indexes")`, which fixes the `v5.4.119` merge issue where the reserved indexes of mmc devices has been accidentally dropped.
This should address the problem reported in #788, where it was indicated that indexes were changing.
Cc: @onurcalili
Cc: @sapiippo
-- andrey
=> Consolidated Kernel update (v5.4.122 + v5.10.40 + 5.12.7)

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc-lts_5.10.bb, recipes-kernel/linux/linux-fslc_5.12.bb
- `linux-fslc-imx`: _v5.4.124_
- `linux-fslc-lts`: _v5.10.42_
- `linux-fslc`: _v5.12.9_
-- andrey
=> Consolidated Kernel update (v5.4.124 + v5.10.42 + 5.12.9)

recipes-bsp/isp-imx/isp-imx/0001-isp-imx-drop-use-of-__TIME__-__DATE__.patch, recipes-bsp/isp-imx/isp-imx_4.2.2.11.0.bb
With reproducible build enabled the compiler is configured to throw
an error if __TIME__, __DATE__ preprocessor macros are used,
replace them.
=> isp-imx: fix compiler error with __DATE__, __TIME__

recipes-multimedia/libimxvpuapi/libimxvpuapi2_2.2.0.bb
* Add IMX_VPU_API_DEC_OUTPUT_CODE_VIDEO_PARAMETERS_CHANGED output code
* Deprecate encoder drain mode, better document decoder drain mode
* Various documentation fixes and new overviews about en- and
decoding to help with the basic concepts
* Add note about the current state of i.MX8m plus support
* New functions:
imx_vpu_api_is_color_format_rgb()
imx_vpu_api_vp8_profile_number()
imx_vpu_api_vp8_partition_count_number()
imx_vpu_api_vp9_profile_number()
imx_vpu_api_enc_set_frame_rate()
* imx6-coda: Fix decoded frame fb_context
This was causing crashes when callers relied on said fb_context
=> libimxvpuapi2: Update to version 2.2.0

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc-lts_5.10.bb, recipes-kernel/linux/linux-fslc_5.12.bb
- `linux-fslc-imx`: _v5.4.126_
- `linux-fslc-lts`: _v5.10.44_
- `linux-fslc`: _v5.12.11_
-- andrey
=> Consolidated Kernel update (v5.4.126 + v5.10.44 + 5.12.11)

recipes-extended/jailhouse/jailhouse_0.12.bb
The firmware is installed in /lib regardless of multilib usage.
=> jailhouse: Fix firmware location as non-arch specific

recipes-bsp/u-boot/u-boot-fslc-common_2021.07.inc
U-Boot repository has been upgraded to `v2021.07-rc5` from _DENX_ repository.
Upstream commits and resolved conflicts are recorded in corresponding recipe commit message.
Link: https://lore.kernel.org/u-boot/20210628194137.GU9516@bill-the-cat/
Link: https://github.com/Freescale/u-boot-fslc/pull/41
=> u-boot-fslc: update to v2021.07-rc5

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc-lts_5.10.bb, recipes-kernel/linux/linux-fslc_5.12.bb
- `linux-fslc-imx`: _v5.4.129_
- `linux-fslc-lts`: _v5.10.47_
- `linux-fslc`: _v5.12.14_
Commit a1ff57ba ("linux-fslc-imx: sanitize local version") drops the `-imx` prefix from _LOCALVERSION_ to align with new versioning scheme between `linuximx` and `linux-fslc-imx` kernel providers.
-- andrey
=> Consolidated Kernel update (v5.4.129 + v5.10.47 + 5.12.14)

recipes-extended/tsntool/tsntool_git.bb
New commits:
3111f7f Pull request #22: cnc: add cbgen and cbrec functions
54a6554 cnc: add cbgen and cbrec functions
b30a3fb demo:cnc: support parameter for devices GROUP_NAME
4444d30 cnc: demo: json format unifiy
107ec39 Update cnc demo README
3b69fb2 libtsn: fix the libtsn for third party
44f8c29 cnc: fix subprocess not response- not sure
61ab161 cnc: remove the devices list and set by the device neighbor table
be944a4 cnc: remove some informations
5301380 cnc: fix ip6 resolve address
e506476 cnc: fix the pmc not feedbach make hang
1a4099a cnc: remove more message
93885f6 cnc: fix global neighbors interfaces dynamic changes
bca7435 cnc:add path show with color obviously
b744065 cnc: fix switch can't do path check as end station
d3770dd cnc: add path found
6775903 cnc: get path found …
=> tsntool: update to 3111f7f

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc-lts_5.10.bb, recipes-kernel/linux/linux-fslc_5.12.bb
- `linux-fslc-imx`: _v5.4.134_
- `linux-fslc-lts`: _v5.10.52_
- `linux-fslc`: _v5.12.19 [EOL]_ 
Upstream commits, resolved conflicts and NXP-specific commits to `linux-fslc-imx` are recorded in corresponding recipe commit messages.
**NOTE**: According to [Greg's announcement on LKML](https://lore.kernel.org/lkml/1626791065147152@kroah.com/), `linux-5.12.y` goes into EOL with `v5.12.19` being the last release.
-- andrey
=> Consolidated Kernel update (v5.4.134 + v5.10.52 + 5.12.19 [EOL])

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.10.bb
- `linux-fslc-imx`: _v5.4.134_
- `linux-fslc`: _v5.10.52_
Upstream commits, resolved conflicts and NXP-specific commits to `linux-fslc-imx` are recorded in corresponding recipe commit messages.
-- andrey
=> [hardknott]: Consolidated Kernel update (v5.4.134 + v5.10.52)

recipes-multimedia/alsa/alsa-lib/0001-add-conf-for-multichannel-support-in-imx.patch, recipes-multimedia/alsa/alsa-lib/0004-pcm-Don-t-store-the-state-for-SND_PCM_STATE_SUSPENDE.patch, recipes-multimedia/alsa/alsa-lib/0005-add-ak4458-conf-for-multichannel-support.patch, recipes-multimedia/alsa/alsa-lib/0006-add-conf-for-iMX-XCVR-sound-card.patch
The model name for the i.MX CS42888 sound card is imx-cs42888.
=> alsa-lib: Fix imx-cs42888 model name, fix fuzz

recipes-graphics/imx-gpu-apitrace/imx-gpu-apitrace_9.0.0.bb
Upstream project has issues with new glibc dropping `__libc_dlopen_mode` and `__libc_dlsym` functions, which were initially marked as **GLIBC_PRIVATE**.
Since according to https://github.com/apitrace/apitrace/issues/756 there is no solution for upstream at the moment, exclude the NXP fork of _apitrace_ from builds.
meta-oe has similar exclusion commit ba94b0fef ("apitrace: Exclude from builds with glibc 2.34+") for upstream component.
Cc: @thochstein 
Cc: @kraj
=> imx-gpu-apitrace: exclude from builds with glibc 2.34+

recipes-bsp/u-boot/u-boot-fslc-common_2021.07.inc
U-Boot repository has been upgraded to `v2021.07` from _DENX_ repository.
Upstream commits are recorded in corresponding recipe commit message.
Link: https://lore.kernel.org/u-boot/20210705151317.GW9516@bill-the-cat/
Link: https://github.com/Freescale/u-boot-fslc/pull/42
=> u-boot-fslc: update to v2021.07

recipes-graphics/imx-gpu-viv/imx-gpu-viv-6.inc
Support for GL on framebuffer is available for some time, at least
since 6.4.0.p2.6.
=> imx-gpu-viv: Provides virtual/libgl for framebuffer

recipes-graphics/imx-gpu-viv/imx-gpu-viv-6.inc
Support for GL on framebuffer is available for some time, at least
since 6.4.0.p2.6.
(cherry picked from commit d7fad5bac8d762a73932d908fd5445be6334243c)
=> [hardknott] imx-gpu-viv: Provides virtual/libgl for framebuffer

conf/machine/include/imx-base.inc
Without a default the IMAGE_BOOT_FILES is not parsed properly, leading
to the following error for machines without such a variable definition:
```
| ERROR: _exec_cmd: install -m 0644 -D /z/build-master/imx233-olinuxino-maxi/build/tmp-glibc/deploy/images/imx233-olinuxino-maxi/make_dtb_boot_files /z/build-master/imx233-olinuxino-maxi/build/tmp-glibc/work/imx233_olinuxino_maxi-oe-linux-gnueabi/core-image-base/1.0-r0/tmp-wic/boot.2/make_dtb_boot_files returned '1' instead of 0
| output: install: cannot stat '/z/build-master/imx233-olinuxino-maxi/build/tmp-glibc/deploy/images/imx233-olinuxino-maxi/make_dtb_boot_files': No such file or directory
ERROR: Task (/opt/oe/configs/z/build-master/imx233-olinuxino-maxi/layers/openembedded-core/meta/recipes-core/images/core-image-base.bb:do_image_wic) …
```
=> imx-base.inc: Define a default value for OPTEE_BIN_EXT

recipes-graphics/imx-gpu-apitrace/imx-gpu-apitrace/0001-dlsym-workaround-glibc-2.34-build-failure.patch, recipes-graphics/imx-gpu-apitrace/imx-gpu-apitrace_9.0.0.bb
[Upsteam suggested](https://github.com/apitrace/apitrace/issues/756) that for glibc >= 2.34, dlsym wrappers can be disabled.
Similar commit is introduced in meta-oe:
`9fdc7960b ("apitrace: Enable on glibc >= 2.34")`
Cc: @thochstein
=> imx-gpu-apitrace: enable back for glibc >= 2.34

conf/machine/include/imx8mm-evk.inc
The build for kernel-module-qca9377 is broken:
```
| /.../yocto/master/build/tmp/work/imx8mm_lpddr4_evk-fsl-linux/kernel-module-qca9377/3.1-r0/git/CORE/SERVICES/COMMON/adf/linux/adf_os_dma_pvt.h:104:25: error: 'DMA_ATTR_NON_CONSISTENT' undeclared (first use in this function)
|   104 |                         DMA_ATTR_NON_CONSISTENT);
|       |                         ^~~~~~~~~~~~~~~~~~~~~~~
```
The Linux API here is changed for 5.10, so the i.MX fork is now
incompatible. Nothing suitable is found in Qualcomm's source either,
so drop qca9377.
Fixes: #851
=> imx8mm-evk.inc: Drop qca9377

recipes-multimedia/tinycompress/tinycompress/0002-cplay-Support-wave-file.patch
Fixes a build error discovered by musl, we need to include sys/types.h
for u_charr and its friends.
=> tinycompress: Fix build with musl

recipes-kernel/linux/linux-fslc_5.14.bb
Wouter Vanhauwaert discovered that the latest linux-fslc kernel would panic
when booting on an imx53-based device:
https://github.com/Freescale/meta-freescale/issues/864
Fabio Estevam added a fix to linux-fslc, therefore we bump the revision to
pick up this fix.
=> linux-fslc: bump revision to include msm fix

recipes-bsp/u-boot/u-boot-fslc_2021.07.bb
Recipe contains append to a deploy task, which is currently handled by imx-boot-container class and is not needed in the recipe anymore. Moreover, recipe compatibility does not include mx8m machine override, which makes the deploy append block never to be included.
Remove the unused append block from recipe.
-- andrey
=> u-boot-fslc: drop unused deploy task append

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc-lts_5.10.bb, recipes-kernel/linux/linux-fslc_5.14.bb
- `linux-fslc-imx`: _v5.4.147_
- `linux-fslc-lts`: _v5.10.67_
- `linux-fslc`: _v5.14.6_
Recipe commits are separated based on PR in _linux-fslc_ repository in order to provide a possibility to bisect kernel versions in case of faults (both build and runtime).
-- andrey
=> Consolidated Kernel update (v5.4.147 + v5.10.67 + 5.14.6)

classes/imx-boot-container.bbclass
The whole purpose of the UBOOT_CONFIG machinery is to allow one to
build multiple versions of U-Boot within the same recipe, e.g. one for
writing to an eMMC boot partition, and one for use with an SD card for
bootstrapping/recovery. But the current code here assumes UBOOT_CONFIG
consists of just a single word (and normally leading whitespace in that
variable would be harmless).
So use the variable ${type} which gets set in turn to each individual
word in UBOOT_CONFIG. For compatibility, keep creating the u-boot.itb
and flash.bin symlinks, but only for the first type in
UBOOT_CONFIG.
It might be better (a little less arbitrary) to make the test
something like
if [ ${type} = "sd" ]
but that's not entirely equivalent to the current code if UBOOT_CONFIG
does consist of a single word, but not …
=> imx-boot-container.bbclass: support having more than one UBOOT_CONFIG

recipes-kernel/linux/linux-fslc-imx_5.4.bb, recipes-kernel/linux/linux-fslc_5.4.bb
Both kernel branches were updated up to and including _v5.4.147_ from stable korg, recipe `SRCREV` are updated to point to that version now.
Recipe commits are separated based on PRs in _linux-fslc_ repository in order to provide a possibility to bisect kernel versions in case of faults (both build and runtime).
Boot-tested on `imx8mmevk`, result: **PASS**.
-- andrey
=> [dunfell]: Consolidated Kernel update (up to v5.4.147)

recipes-kernel/linux/linux-fslc-imx_5.4.bb
Bump of `linux-fslc-imx` version cherry-picking the update commits from master
=> Cherry-picking linux-fslc-imx changes and backporting it to hardknott

recipes-kernel/kernel-modules/kernel-module-imx-gpu-viv_6.4.3.p2.0.bb, recipes-kernel/linux/linux-imx-headers_5.10.bb, recipes-kernel/linux/linux-imx_5.10.bb
I found out that linux.imx is broken for target imx8mp-evk-lpddr4 after commit 93cf9cd9492e4c932591806f6bafc43270a934d8. Fixed this by upgrading kernel to 5.10.52-2.1.0. Also bumped linux-imx-hraders and kernel-module-imx-gpu-viv that also had references to 5.10.35.
=> linux-imx*: upgrade to 5.10.52

recipes-bsp/imx-lib/imx-lib_git.bb
Fixes commit 87cb0d99 ("imx-lib: upgrade to 5.10.52_2.1.0")
| ERROR: imx-lib-1_5.9+AUTOINC+87ddd80953-r0 do_package: QA Issue: imx-lib: Files/directories were installed but not shipped in any package:
|   /usr/lib/libcec.go
|   /usr/lib/libipu.go
=> imx-lib: fix packaging

conf/machine/imx8qm-mek.conf
imx8qm-mek-dsp.dtb is no longer available in the kernel,
it was removed in de78ae45bfffed2c9490ab733d11ebab2672984d
Signed-off-by: Samuli Piippo <samuli.piippo@qt.io>
=> imx8qm-mek: remove obsolete dtb

recipes-graphics/imx-gpu-viv/imx-gpu-viv-6.inc
Expose the Vulkan library version so NXP can easily override in their
layer.
Please backport to `honister`.
=> imx-gpu-viv: Expose Vulkan library version

recipes-bsp/isp-imx/isp-imx/0001-isp-imx-drop-use-of-__TIME__-__DATE__.patch, recipes-bsp/isp-imx/isp-imx_4.2.2.15.0.bb, recipes-bsp/isp-imx/libtinyxml2-8_8.0.0.bb
isp-imx currently does not build, These two patches do address the do_patch and do_configure failures.
However there seems to be a binary only file deployed linked against an older version of libtinyxml2 and thus a QA error is generated. (libtinyxml2.so.9 is now provided from meta-openembedded) resulting in:
```
ERROR: isp-imx-4.2.2.15.0-r0 do_package_qa: QA Issue: /usr/lib/libcam_device.so contained in package isp-imx requires libtinyxml2.so.8()(64bit), but no providers found in RDEPENDS:isp-imx? [file-rdeps]
ERROR: isp-imx-4.2.2.15.0-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.
ERROR: Logfile of failure stored in: /build/krm/oe-core_master/build/tmp/work/aarch64-mx8mp-tdx-linux/isp-imx/4.2.2.15.0-r0/temp/log.do_package_qa.6780
ERROR: Task …
```
=> Draft: Master isp imx

conf/machine/include/imx8x-mek.inc
Some dtb for DSP were removed from the kernel.
=> imx8x-mek.inc: Remove obsolete dtb for DSP

recipes-support/opencv/opencv/0001-Use-the-one-argument-version-of-SetTotalBytesLimit.patch, recipes-support/opencv/opencv_4.5.2.imx.bb
2178fd7386 opencv: remove setup_vars_opencv4.sh
cafcc65e74 opencv: fix build with protobuf-3.18 when dnn PACKAGECONFIG is enabled
3c022cd50d opencv: Do not lock to gcc only compiler
=> opencv: Backport updates from OE-Core

recipes-bsp/atf/qoriq-atf_2.4.bb
this is undefined behaviour, mant times devs used them together to get
the missing space at the beginning of string which append/prepend needs
but thats not intended behaviour
=> qoriq-atf: Do not use append with += operator

recipes-fsl/packagegroups/packagegroup-fsl-isp.bb
MACHINE_SOCARCH is not universally defined and results in errors on
non-fsl machines.
=> packagegroup-fsl-isp: Make is machine specific

dynamic-layers/browser-layer/recipes-browser/chromium/chromium-imx.inc, recipes-bsp/ddr-phy/ddr-phy_git.bb, recipes-bsp/imx-kobs/imx-kobs_git.bb, recipes-bsp/imx-uuc/imx-uuc_git.bb, recipes-bsp/inphi/inphi_git.bb, recipes-bsp/libimxdmabuffer/libimxdmabuffer_1.0.1.bb, recipes-bsp/ls2-phy/ls2-phy_git.bb, recipes-bsp/mxsldr/mxsldr_git.bb, recipes-bsp/ppfe-firmware/ppfe-firmware_git.bb, recipes-bsp/qe-ucode/qe-ucode_git.bb, recipes-bsp/u-boot/u-boot-fslc-common_2020.04.inc, recipes-bsp/uefi/uefi_git.bb, recipes-devtools/devregs/devregs_git.bb, recipes-devtools/imx-usb-loader/imx-usb-loader_git.bb, recipes-devtools/utp-com/utp-com_git.bb, recipes-dpaa/fm-ucode/fm-ucode_git.bb, recipes-dpaa2/management-complex/management-complex_10.14.1.bb, recipes-dpaa2/management-complex/management-complex_10.20.4.bb, recipes-kernel/kernel-modules/kernel-module-imx-gpu-viv_6.4.0.p2.4+fslc.bb, recipes-kernel/linux/linux-fslc-qoriq_5.4.bb, recipes-kernel/linux/linux-fslc.inc, recipes-multimedia/gstreamer/gstreamer1.0-plugins-imx_0.13.1.bb, recipes-multimedia/libimxvpuapi/libimxvpuapi2_2.2.0.bb, recipes-multimedia/libimxvpuapi/libimxvpuapi_git.bb
This is a backport of commit bef00d6e4f25b4a9d3272e0d69db7545590ed204 to the dunfell LTS branch:
```
Due to https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git
it is required to use https protocol for github repo accessing.
Update created with oe-core/scripts/contrib/convert-srcuri.py (see [0])
Fixes:
WARNING: /work/meta-freescale/recipes-bsp/u-boot/u-boot-fslc-mxsboot_2021.07.bb: URL: git://github.com/Freescale/u-boot-fslc.git;branch=2021.07+fslc uses git protocol which is no longer supported by github. Please change to ;protocol=https in the url.
[0] - https://git.openembedded.org/openembedded-core/tree/scripts/contrib/convert-srcuri.py
Signed-off-by: Pierre-Jean Texier <texier.pj2@gmail.com>
```
=> [backport dunfell] recipes: use https protocol and add explicit branch parameter

recipes-devtools/devregs/devregs_git.bb
Changelog:
dcc3e3f clarify project license to be GPLv2
ed28469 devregs_imx8mm.dat: add mipi csi regs
2c92a1d scripts: add rough idea of a technical reference parser
05a0313 devregs: add fancy color mode
d713004 devregs: add imx8mm to fixit manual list
Update the license in the recipe now that it has been clarified.
Signed-off-by: Gary Bisson <gary.bisson@boundarydevices.com>
=> devregs: bump revision to dcc3e3f2

recipes-bsp/imx-atf/imx-atf_2.4.bb
This PR is generally a set of patches ported from _meta-arm_, which provides recipe for upstream TF-A.
It addresses the match of toolchain which is provided in the sysroot to what TF-A expects in it's Makefile, specifically:
- Unsets `CFLAGS`, `LDFLAGS`, `AS` and `LD` variables which are defined by TF-A itself
- Drops dependency on C-runtime as it is not required for TF-A (baremetal)
- Enables support to use _Clang_ for TF-A build by sanitizing `CC` and `LD` variables.
Original commits used for this port are linked in commits to this layer.
@thochstein This PR also drops the 79ba26618a075332ac9106f55c1aad573e42c9e0 as `CFLAGS` will be set by TF-A itself. I've tested this on `imx8mq_evk` machine and observed no build issues.
-- andrey
=> imx-atf improvements (Clang ready)

recipes-kernel/linux/linux-fslc_5.15.bb
Kernel repository has been upgraded up to v5.15.12 from stable korg.
----
25960cafa06e Linux 5.15.12
53ccdc73eeda phonet/pep: refuse to enable an unbound pipe
3cb5ae77799e tun: avoid double free in tun_free_netdev
03d00f7f1815 hamradio: improve the incomplete fix to avoid NPD
cb6c99aedd2c hamradio: defer ax25 kfree after unregister_netdev
a8e4a64cdc97 ax25: NPD bug when detaching AX25 device
f547b0f8f3ce r8152: sync ocp base
5cc8813c4966 hwmon: (lm90) Do not report 'busy' status bit as alarm
722fc45be049 hwmom: (lm90) Fix citical alarm status for MAX6680/MAX6681
fb563baa3eb8 pinctrl: mediatek: fix global-out-of-bounds issue
aa50406f36a1 ASoC: rt5682: fix the wrong jack type detected
46b3fe1eb2b7 ASoC: SOF: Intel: pci-tgl: add ADL-N …
=> linux-fslc: update version to v5.15.12

recipes-kernel/linux/linux-fslc-imx_5.10.bb, recipes-kernel/linux/linux-fslc-lts_5.10.bb, recipes-kernel/linux/linux-fslc_5.15.bb
- `linux-fslc-imx`: _v5.10.90_
- `linux-fslc-lts`: _v5.10.90_
- `linux-fslc`: _v5.15.13_
Upstream commits and resolved conflicts are recorded in corresponding recipe commit messages. Additional commits to `linux-fslc-imx` are recorded in recipe tracking section.
`linux-fslc` has been boot-tested on `imx8mm-lpddr4-evk` and `imx8mp-lpddr4-evk` machines, result: **PASS**.
-- andrey
=> Consolidated Kernel update (v5.10.90 + 5.15.13)

recipes-graphics/libsdl2/libsdl2_%.bbappend
openembedded-core commit c00f79c2f1 ("libsdl2: Move to CMake build")
moved the recipe to CMake. Follow this in this bbappend.
=> libsdl2: follow oe-core's move to cmake

recipes-multimedia/gstreamer/imx-gst1.0-plugin_4.6.1.bb, recipes-multimedia/imx-dsp/imx-dsp-codec-ext_1.2.0.bb, recipes-multimedia/imx-dsp/imx-dsp_1.2.0.bb
As per NXP BSP:
- https://source.codeaurora.org/external/imx/meta-imx/tree/meta-bsp/recipes-multimedia/imx-dsp?h=hardknott-5.10.72-2.2.0
- https://source.codeaurora.org/external/imx/meta-imx/commit/?h=hardknott-5.10.72-2.2.0&id=eb72f6dc37079f001106711cdeecdb00f2d8e6cf
=> Add imx-dsp recipes and enable imx-gst1.0-plugin to support i.MX Audio DSP Codec

recipes-multimedia/gstreamer/imx-gst1.0-plugin_4.6.1.bb, recipes-multimedia/imx-dsp/imx-dsp-codec-ext_1.2.0.bb, recipes-multimedia/imx-dsp/imx-dsp_1.2.0.bb
As per NXP BSP:
- https://source.codeaurora.org/external/imx/meta-imx/tree/meta-bsp/recipes-multimedia/imx-dsp?h=hardknott-5.10.72-2.2.0
- https://source.codeaurora.org/external/imx/meta-imx/commit/?h=hardknott-5.10.72-2.2.0&id=eb72f6dc37079f001106711cdeecdb00f2d8e6cf
Signed-off-by: Nate Drude <nate.d@variscite.com>
=> Hardknott: Add imx-dsp recipes and enable imx-gst1.0-plugin to support i.MX Audio DSP Codec

recipes-kernel/linux/linux-fslc_5.4.bb
Kernel branch for linux-fslc was updated up to and including v5.4.172 from stable korg, recipe SRCREV are updated to point to that version now.
Recipe commits are separated based on PRs in linux-fslc repository in order to provide a possibility to bisect kernel versions in case of faults (both build and runtime).
=> [dunfell]: linux-fslc Kernel update (up to v5.4.172)

conf/machine/imx8mq-evk.conf
Recent versions of upstream U-Boot and Kernel do provide support for i.MX8MQ derivative, and it can be built using Mainline BSP.
Convert machine definition to include all parts, that are required to build Mainline BSP:
- Drop hardcoded BSP flavor setting in machine configuration
- Add boot container machine override
- Split machine features
- Define ATF load address
- Add dependency to firmware package
- Provide `extlinux` configuration to utilize _distro boot_ feature
Tested on `imx8mq-evk` machine for both `nxp` and `mainline` setting in `IMX_DEFAULT_BSP`.
-- andrey
=> [imx8mq-evk]: Add Mainline BSP support

recipes-multimedia/gstreamer/gstreamer1.0-libav_1.18.0.bb, recipes-multimedia/gstreamer/gstreamer1.0-plugins-ugly_1.18.0.bb, recipes-multimedia/gstreamer/gstreamer1.0-rtsp-server_1.18.0.bb
Having open recipes in a high priority layer means they will override
always even when its not building for machines not coming from this
layer
Pin them to imx
=> gstreamer: Lockin the versions for imx machines

recipes-kernel/linux/linux-fslc-imx_5.10.bb, recipes-kernel/linux/linux-fslc-lts_5.10.bb, recipes-kernel/linux/linux-fslc_5.15.bb
- `linux-fslc-imx`: _v5.10.93_
- `linux-fslc-lts`: _v5.10.93_
- `linux-fslc`: _v5.15.16_
Upstream commits are recorded in corresponding recipe commit messages. 
`linux-fslc` has been boot-tested on following machines:
- `imx8mm-lpddr4-evk`: **PASS**
- `imx8mn-lpddr4-evk`: **PASS**
- `imx8mp-lpddr4-evk`: **PASS**
- `imx8mq-evk`: **PASS**
-- andrey
=> Consolidated Kernel update (v5.10.93 + 5.15.16)

classes/fsl-vivante-kernel-driver-handler.bbclass
Building core-image-weston with multilib support and builtin graphics
fails:
```
ERROR: Nothing PROVIDES 'virtual/arm-oelmllib32-linux-gnueabi-binutils'. Close matches:
virtual/lib32-arm-oelmllib32-linux-gnueabi-binutils
virtual/lib32-arm-oelmllib32-linux-gnueabi-go-runtime
virtual/lib32-arm-oelmllib32-linux-gnueabi-rust
ERROR: Nothing PROVIDES 'virtual/arm-oelmllib32-linux-gnueabi-gcc'. Close matches:
virtual/lib32-arm-oelmllib32-linux-gnueabi-g++
virtual/lib32-arm-oelmllib32-linux-gnueabi-gcc
virtual/lib32-arm-oelmllib32-linux-gnueabi-rust
```
This is the configuration added in local.conf:
```
require conf/multilib.conf
MULTILIBS = "multilib:lib32"
DEFAULTTUNE:virtclass-multilib-lib32 = "armv7athf-neon"
IMAGE_INSTALL:append = " lib32-glibc lib32-libgcc lib32-libstdc++" …
```
=> fsl-vivante-kernel-driver-handler.bbclass: Fix multilib support

classes/fsl-vivante-kernel-driver-handler.bbclass
Building core-image-weston with multilib support and builtin graphics
fails:
```
ERROR: Nothing PROVIDES 'virtual/arm-oelmllib32-linux-gnueabi-binutils'. Close matches:
virtual/lib32-arm-oelmllib32-linux-gnueabi-binutils
virtual/lib32-arm-oelmllib32-linux-gnueabi-go-runtime
virtual/lib32-arm-oelmllib32-linux-gnueabi-rust
ERROR: Nothing PROVIDES 'virtual/arm-oelmllib32-linux-gnueabi-gcc'. Close matches:
virtual/lib32-arm-oelmllib32-linux-gnueabi-g++
virtual/lib32-arm-oelmllib32-linux-gnueabi-gcc
virtual/lib32-arm-oelmllib32-linux-gnueabi-rust
```
This is the configuration added in local.conf:
```
require conf/multilib.conf
MULTILIBS = "multilib:lib32"
DEFAULTTUNE:virtclass-multilib-lib32 = "armv7athf-neon"
IMAGE_INSTALL:append = " lib32-glibc lib32-libgcc lib32-libstdc++" …
```
=> [honister] fsl-vivante-kernel-driver-handler.bbclass: Fix multilib support

recipes-kernel/kernel-modules/kernel-module-nxp89xx_git.bb
It fails to build with linux-yocto 5.15 e.g.
TOPDIR/build/tmp/work/qemumips-yoe-linux/kernel-module-nxp89xx/git-r0/git/mxm_wifiex/wlan_src/mlinux/moal_shim.c:1405:49: error: 'RX_PKT_FATE_DRV_DROP_NOBUFS' undeclared (first use in this function)
1405 |                                                 RX_PKT_FATE_DRV_DROP_NOBUFS,
|                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
=> kernel-module-nxp89xx: Pin to imx machine kernel

recipes-security/optee-imx/optee-test_3.10.0.imx.bb
For security reason, pycrypto is no longer available, but it can be replaced by
pycryptodome.
=> optee-test: replace old pycrypto with pycryptodome

recipes-bsp/imx-atf/imx-atf_2.4.bb
Otherwise, when ccache is enable the following issue occurs:
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: make -j 8 CROSS_COMPILE=aarch64-oe-linux- PLAT=imx8qx LD=aarch64-oe-linux-ld CC=ccache aarch64-oe-linux-gcc bl31
| make: *** No rule to make target 'aarch64-oe-linux-gcc'.  Stop.
| ERROR: oe_runmake failed
| WARNING: exit code 1 from a shell command.
Fix #969
=> imx-atf: add mark quotation to prevent build issue with ccache 

recipes-graphics/wayland/weston-init.bbappend
The customized weston.ini is installed in the rootfs with an unresolved
bindir variable.
=> weston-init: Set bindir properly in weston.ini

recipes-extended/crconf/crconf_git.bb
This fixes building crconf with usrmerge enabled. It also removes setting the `FILES` variable, since it is unnecessary.
=> Fix building crconf with usrmerge

conf/machine/include/imx-base.inc
The i.MX 8QXP and 8DXL are in the 8X family, but the override was
missed in the new SOC override rework. This causes do_compile for
imx-boot to fail:
```
cp: cannot stat '/.../build/tmp/deploy/images/imx8qxpmek/imx8qm_m4_TCM_power_mode_switch_m40.bin': No such file or directory
```
=> imx-base.inc: Add missing mx8x overrides

conf/machine/include/imx8dxl-evk.inc, conf/machine/include/imx8x-mek.inc
Refs: 9b9f9bb1 ("imx-base.inc: Add missing mx8x overrides")
=> imx8x: The mx8x override is handled in extender so drop it

recipes-kernel/linux/linux-imx-headers_5.10.bb
As some recipes, like imx-vpu-hantro, need to know the imx kernel
version instead of the toolchain header version.
As an example, Honister toolchain uses 5.14 kernel headers. In that
case, imx-vpu-hantro believes it needs to use dmabuf allocation
mechanism although this latter will only be enabled in upcoming NXP
kernel 5.15.
Signed-off-by: Gary Bisson <gary.bisson@boundarydevices.com>
=> linux-imx-headers: whitelist version.h header (Fixes Hantro VPU for honister/master)
