Freescale/meta-freescale

conf/machine/imx7ulpevk.conf
The imx7ulp-com.dtb describes a completely different board: the Embedded
Artists i.MX7ULP COM board, which has no relationship with the NXP
i.MX7ULP EVK board.
Remove the imx7ulp-com.dtb entry.
Signed-off-by: Fabio Estevam <festevam@gmail.com>
=> conf: imx7ulpevk: Remove unrelated imx7ulp-com.dtb entry

classes/machine-overrides-extender.bbclass, conf/machine/include/imx-base.inc, scripts/convert-bsp-specific-overrides
To assist existing layers to convert to the new BSP-specific
overrides. Besides failing the parsing of the recipes where it is in
use, we provide a script to automate most of it.
Fixes: #990.
=> Ensure we fail if old SoC overrides are in use

conf/machine/include/imx-base.inc
When include/imx-base.inc was simplified to use the imx-{mainline,nxp}-bsp
overrides, the "mxs" and "mx23" categories of machines were missed.
Build tested with imx233-olinuxino-* and imx23evk.
Run tested with imx233-olinuxino-maxi.
=> imx-base.inc: add back mxs/mx23 support

classes/imx-boot-container.bbclass, conf/machine/imx8mq-evk.conf, conf/machine/include/imx8mm-evk.inc, conf/machine/include/imx8mn-evk.inc, conf/machine/include/imx8mp-evk.inc
Upstream U-Boot commit `d9a6f0eed66a ("tree: imx: remove old fit generator script")` dropped the FIT generator script, which was using environment variable setting the ATF load address into the FIT ITS file.
This has been replaced by binman node description, where ATF address is defined, hence the environment variable is not required anymore.
Clean-up the layer's class and machine description to remove the variable, which is not used anymore.
_NOTE_: NXP BSP is not affected by this change, as `ATF_LOAD_ADDR` is defined in `iMX8M/soc.mak` file of `imx-boot` package based on ATF machine definition.
**Cc**: @thochstein
=> Clean-up obsolete ATF load address for i.MX8M machines

recipes-graphics/wayland/weston-init.bbappend
The mx8qm-nxp-bsp/mx8qxp-nxp-bsp overrides would not work because
imxgpu2d would take effect in the end since it has higher priority
in MACHINEOVERRIDES.
Append mx8qm-nxp-bsp/mx8qxp-nxp-bsp after imxgpu2d can fix the problem.
Signed-off-by: Ming Liu <liu.ming50@gmail.com>
=> weston-init: fix some invalid overrides

recipes-security/optee-imx/optee-os/0001-arm-imx-fix-RPMB-header-include.patch, recipes-security/optee-imx/optee-os_3.15.0.imx.bb
When CFG_RPMB_FS=y, OP-TEE os no longer compiles because imx_rpmb.c
tries to include a header that doesn't exist. This issue seems linked
to a rework that allows to compile i.MX Secure Non-Volatile Storage
driver without RPMB.
```
|   CC      optee-os/3.15.0.imx-r0/build/core/arch/arm/plat-imx/imx_rpmb.o
| core/arch/arm/plat-imx/imx_rpmb.c:5:10: fatal error: drivers/imx_snvs.h: No such file or directory
|     5 | #include <drivers/imx_snvs.h>
|       |          ^~~~~~~~~~~~~~~~~~~~
| compilation terminated.
| make: *** [mk/compile.mk:159: optee-os/3.15.0.imx-r0/build/core/arch/arm/plat-imx/imx_rpmb.o] Error 1
| make: *** Waiting for unfinished jobs....
|   CC     optee-os/3.15.0.imx-r0/build/core/crypto/crypto.o
|   CC      optee-os/3.15.0.imx-r0/build/core/arch/arm/plat-imx/imx_dt.o
| …
```
=> optee-os: Fix RPMB build break

conf/machine/include/imx-base.inc
Align with 8M family. Enabling Crypto enables FP and SIMD as well.
=> imx-base.inc: Enable Crypto for all 8X

classes/kernel-itbimage.bbclass, classes/mfgtool-initramfs-image.bbclass
The initramfs memory size is limited, so use zstd compression level 10
to cut the cpio archive size by some 30%.
=> mfgtool-initramfs-image: Switch to zstd compression

conf/machine/imx6ulevk.conf, conf/machine/imx6ullevk.conf
The commits to honister and hurdknoot are ready, just need the original cherry-pick commit hash to be updated in commit messages.
The imx6ul-14x14-evk-btwifi-oob.dtb and
imx6ull-14x14-evk-btwifi-oob.dtb are no longer available in the
kernel lf-5.10.y, it was removed in a1488e98156ea1a597353c93b76b4f7fd8dd7c7c
Remove entries for non-existent dtb files. This fixes building a
Linux kernel recipe for imx6ulevk/imx6ullevk.
Fixes: 3f93c925 ("linux-imx*: Upgrade to 5.10.52")
=> Fix: master: imx6ul*: remove obsolete device tree entry

conf/machine/include/qoriq-base.inc
When using a kernel/bootloader fork maintained by board vendor and there are
somer flavours ist would be good to have only weak assignments here. This enables
to override the default by machine config and set final by distro or local.conf.
This is essentually the same as dine in imx-base.inc with the exception that is is don directly here instead via an additional overwritable variable.
=> qoriq-base: weak defaults for u-boot/bootloader/kernel PREFERRED_PROVIDER

conf/machine/include/qoriq-base.inc
When using a kernel/bootloader fork maintained by board vendor and there are
somer flavours ist would be good to have only weak assignments here. This enables
to override the default by machine config and set final by distro or local.conf.
Signed-off-by: Markus Niebel <Markus.Niebel@ew.tq-group.com>
(cherry picked from commit 14389dcee0f79495e688413881c5713a3abdfdc1)
=> [Backport hardknott] qoriq-base: weak defaults for u-boot/bootloader/kernel PREFERRED_PROVIDER

conf/machine/include/qoriq-base.inc
When maintaining a hardware support layer for a SOM there will be different
mainboards and BSP for this SOM. Depending on the use case there may be
different needs for SD / e-MMC images. When providing a valid weak default
in meta-freescale a machine definition can override this easier as well
a BSP for a specific mainboard.
Signed-off-by: Markus Niebel <Markus.Niebel@ew.tq-group.com>
=> qoriq-base: weak defaults for WKS_FILE

conf/machine/include/qoriq-base.inc
When maintaining a hardware support layer for a SOM there will be different
mainboards and BSP for this SOM. Depending on the use case there may be
different needs for SD / e-MMC images. When providing a valid weak default
in meta-freescale a machine definition can override this easier as well
a BSP for a specific mainboard.
Signed-off-by: Markus Niebel <Markus.Niebel@ew.tq-group.com>
(cherry picked from commit 451bafe6d6e0523d0f6143f6862bb6c5b42ac8f6)
=> backport qoriq-base: weak defaults for WKS_FILE

recipes-kernel/linux/linux-fslc-imx_5.10.bb, recipes-kernel/linux/linux-fslc-lts_5.10.bb, recipes-kernel/linux/linux-fslc_5.15.bb
- `linux-fslc-imx`: _v5.10.109_
- `linux-fslc-lts`: _v5.10.109_
- `linux-fslc`: _v5.15.32_
Upstream commits are recorded in corresponding recipe commit messages. 
`linux-fslc-imx` has additional commit included:
```
27b6c760cc7f thermal: imx: fix a merging issue
```
`linux-fslc` has been boot-tested on following machines:
- `imx8mm-lpddr4-evk`: **PASS**
- `imx8mn-lpddr4-evk`: **PASS**
- `imx8mp-lpddr4-evk`: **PASS**
- `imx8mq-evk`: **PASS**
-- andrey
=> Consolidated Kernel update (v5.10.109+ 5.15.32)

recipes-bsp/u-boot/u-boot-fslc-mxsboot_2022.04.bb
gnutls is now required in order to build one of the host tools which are part
of U-Boot.
| .../build/tmp-glibc/work/x86_64-linux/u-boot-fslc-mxsboot-native/v2022.04+gitAUTOINC+f885198273-r0/git/tools/mkeficapsule.c:21:10: fatal error: gnutls/gnutls.h: No such file or directory
|  #include <gnutls/gnutls.h>
|           ^~~~~~~~~~~~~~~~~
| compilation terminated.
| make[2]: *** [scripts/Makefile.host:95: tools/mkeficapsule] Error 1
| make[2]: *** Waiting for unfinished jobs....
| make[1]: *** [.../build/tmp-glibc/work/x86_64-linux/u-boot-fslc-mxsboot-native/v2022.04+gitAUTOINC+f885198273-r0/git/Makefile:1894: tools] Error 2
| make[1]: Leaving directory '.../build/tmp-glibc/work/x86_64-linux/u-boot-fslc-mxsboot-native/v2022.04+gitAUTOINC+f885198273-r0/build'
| make: *** [Makefile:177: …
=> u-boot-fslc-mxsboot: add dependency on gnutls-native

conf/machine/imx8mm-ddr4-evk.conf, conf/machine/imx8mn-ddr4-evk.conf, conf/machine/imx8mp-ddr4-evk.conf
This is necessary because mainline U-Boot doesn't supports DDR4 for i.MX8M EVK.
Also these machines aren't supported by mainline kernel.
=> imx8m: Set DDR4 machines to use IMX BSP only

recipes-kernel/linux/linux-qoriq.inc
The merge_delta_config must run before do_kernel_localversion task,
which is what fsl-kernel-localversion now use.
Fixes: #721.
Fixes: 49299998 ("classes: fsl-kernel-localversion: Fix task dependency")
Also an issue on dunfell.
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>
=> linux-qoriq: Fix task order of merge_delta_config task

recipes-graphics/wayland/weston/0001-g2d-renderer-Add-vsync-to-cloned-displays.patch, recipes-graphics/wayland/weston_9.0.0.imx.bb
When using g2d clone mode allocates additional surfaces according to
FB_MULTI_BUFFER for each cloned display. The g2d blit from the main screen
to the cloned displays is done using inactive surface. The FBIOPAN_DISPLAY
ioctl to the surface is done afterwards.
=> weston: Add vsync to cloned displays.

recipes-bsp/atf/qoriq-atf_2.4.bb
It is already internally provided by the recipe, so
don't need to depends on a external provider.
=> qoriq-atf: Remove mbedtls from dependence list

conf/machine/include/qoriq-base.inc
This reverts commit 451bafe6d6e0523d0f6143f6862bb6c5b42ac8f6.
This is necessary to follow the pattern used by imx-base.inc.
Also prevents the following error: "No kickstart files from
WKS_FILES were found"
It happens because WKS_FILE was already assigned and can't be
reassigned by SOC_DEFAULT_WKS_FILE due to a weaker assignment
(??=).
=> Revert "qoriq-base: weak defaults for WKS_FILE"

dynamic-layers/openembedded-layer/recipes-devtools/cst/imx-cst_3.3.1.bb
Fixes
WARNING: imx-cst-3.3.1-r0 do_populate_lic: QA Issue: imx-cst: No generic license file exists for: BSD in any provider [license-exists]
=> imx-cst: Use specific BSD license

classes/fsl-eula-unpack.bbclass
NXP EULA archive-based builds like imx-gpu-viv fail because the unpacked
folder is empty:
```
ERROR: imx-gpu-viv-1_6.4.3.p2.4-aarch64-r0 do_populate_lic: QA Issue: imx-gpu-viv: LIC_FILES_CHKSUM points to an invalid file: /opt/work/upstream/fsl-xwayland/tmp/work/cortexa53-crypto-mx8m-fsl-linux/imx-gpu-viv/1_6.4.3.p2.4-aarch64-r0/imx-gpu-viv-6.4.3.p2.4-aarch64/COPYING [license-checksum]
```
This is traced to a change in bitbake:
```
b074f4a ast: Improve function flags handling for EXPORT_FUNCTIONS
```
That change includes a fix for cleandirs, so now the call to base_unpack,
done after the NXP EULA archive unpack, does now remove the folder(s)
created by the NXP EULA archive unpack.
Fix the problem by simply unpacking the NXP EULA archives last.
Signed-off-by: Tom Hochstein …
=> fsl-eula-unpack.bbclass: Unpack NXP EULA archives last

conf/machine/ls1028ardb.conf, conf/machine/ls1088ardb-pb.conf, conf/machine/ls1088ardb.conf
Current setting cannot set the right overrider order as expected. For example:
MACHINEOVERRIDES="fsl-lsch3:ls1088a:aarch64:use-nxp-bsp:qoriq:qoriq-arm64:ls1088ardb-pb"
Update them to align with other Layerscape machines.
Signed-off-by: Jun Zhu <junzhu@nxp.com>
=> ls1028ardb/ls1088ardb/ls1088ardb-pb: Correct MACHINEOVERRIDES

recipes-dpaa/fmlib/fmlib_git.bb
When building fmlib package based on Yocto 4.0, there is below
warning reported
WARNING: fmlib-git-r1 do_populate_lic: QA Issue: fmlib:
No generic license file exists for: BSD in any provider [license-exists]
Because "BSD" is ambiguous, and there is no corresponding license file
in COMMON_LICENSE_DIR directory. So, set precise BSD license to fix
this issue.
Signed-off-by: Meng Li <Meng.Li@windriver.com>
=> fmlib: set precise BSD license

recipes-bsp/imx-mkimage/files/0001-Add-LDFLAGS-to-link-step.patch, recipes-bsp/imx-mkimage/files/0001-Add-support-for-overriding-BL31-BL32-and-BL33.patch, recipes-bsp/imx-mkimage/files/0001-Add-support-for-overriding-BL32-and-BL33-not-only-BL.patch, recipes-bsp/imx-mkimage/imx-mkimage_git.bb, recipes-bsp/imx-mkimage/imx-mkimage_git.inc
This script gives the address, the offset and the size of binaries have been
stored into U-Boot FIT image that contains TF-A, U-Boot and OP-TEE.
=> imx-imkimage: install print_fit_hab.sh

recipes-bsp/imx-mkimage/files/0001-Add-support-for-overriding-BL31-BL32-and-BL33.patch
When the variable BL31 is empty, BL33 was initialized instead of BL31.
This issue has been introduced by the #1060. 
=> imx-imkimage: fix a typo in a patch for print_fit_hab.sh

recipes-bsp/imx-mkimage/files/0001-Add-LDFLAGS-to-link-step.patch
I wonder why we need the explicit $(LDFLAGS) in the first place, i.e. what does it fix.
The patch is not very verbose on explaining the why.
=> imx-mkimage: fix patch

recipes-bsp/imx-mkimage/files/0001-Add-support-for-overriding-BL32-and-BL33-not-only-BL.patch
From the patch 0001-Add-support-for-overriding-BL32-and-BL33-not-only-BL.patch
an occurrence of tee.bin wasn't replaced by $BL32.
In addition, this patch use $BL31 and $BL32 value, in a displayed line, instead
hardcoded values.
This path has been introduced by the PR #1060.
=> imx-mkimage: Fix a BL32 missing overriding in mkimage_fit_atf.sh

recipes-multimedia/gstreamer/gstreamer1.0-plugins-imx_2.1.0.bb, recipes-multimedia/libimxvpuapi/libimxvpuapi2_2.2.1.bb
This pull request upgrades libimxvpuapi2 to version 2.2.1 and gstreamer1.0-plugins-imx to version 2.1.0. The changelogs are found in the individual commit messages.
This can also be applied to the master branch, but requires the libimxdmabuffer 1.1.2 upgrade (which is already in kirkstone) to be included into master as well.
A separate PR for backporting these two to dunfell will follow.
=> libimxvpuapi2 and gstreamer1.0-plugins-imx upgrades

recipes-bsp/libimxdmabuffer/files/0001-g2d-Fix-typo.patch, recipes-bsp/libimxdmabuffer/libimxdmabuffer_1.1.2.bb, recipes-multimedia/gstreamer/gstreamer1.0-plugins-imx_2.1.0.bb, recipes-multimedia/libimxvpuapi/libimxvpuapi2_2.2.1.bb
This pull request upgrades libimxdmabuffer and libimxvpuapi2 to versions 1.1.2 and 2.2.1, respectively, upgrading them to the same version as in [this kirkstone PR](https://github.com/Freescale/meta-freescale/pull/1074).
In addition, gstreamer1.0-plugins-imx v2.1.0 is backported from that kirkstone PR. It is set to not be the default (gstreamer1.0-plugins-imx 0.13.1 remains the default gstreamer1.0-plugins-imx version).
=> libimxdmabuffer, libimxvpuapi2, gstreamer1.0-plugins-imx upgrades and backports for dunfell

conf/machine/imx8mm-lpddr4-evk.conf, conf/machine/imx8mn-lpddr4-evk.conf, conf/machine/imx8mp-lpddr4-evk.conf
This is necessary because mainline U-Boot doesn't supports LPDDR4 for
i.MX8M EVK.
Also these machines aren't supported by mainline kernel.
=> imx8m: Set LPDDR4 machines to use IMX BSP only

recipes-bsp/imx-atf/imx-atf/0001-Makefile-Suppress-array-bounds-error.patch, recipes-bsp/imx-atf/imx-atf_2.4.bb
The array-bounds error is triggered now in cases where it was silent before,
causing errors like:
```
plat/imx/imx8m/hab.c: In function 'imx_hab_handler':
plat/imx/imx8m/hab.c:64:57: error: array subscript 0 is outside array bounds of 'uint32_t[0]' {aka 'unsigned int[]'} [-Werror=array-bounds]
64 | #define HAB_RVT_CHECK_TARGET_ARM64      ((unsigned long)*(uint32_t *)(HAB_RVT_BASE + 0x18))
|                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
It appears that these new cases will be silenced soon in gcc [1], so for
now just silence the warning locally as workaround.
[1] https://gcc.gnu.org/bugzilla/show_bug.cgi?id=99578#c39
Fixes: #1084
=> imx-atf: Suppress array-bounds error

recipes-bsp/imx-atf/imx-atf_2.4.bb
Correct the name of patch and prepend FILESEXTRAPATHS, in order to fix
the following issue:
ERROR: imx-atf-2.4+gitAUTOINC+05f788b9bb-r0 do_fetch: Bitbake Fetcher
Error: FetchError('Unable to fetch URL from any source.',
'file://0001-alsa-state-Remove-PCM-devices-mapped-by-5.15-kernel.patch')
#1089
=> imx-atf: fix patch applying

conf/machine/imx8qm-mek.conf, conf/machine/include/imx8dxl-evk.inc, conf/machine/include/imx8x-mek.inc, recipes-kernel/linux/linux-qoriq.inc
With OE core commit [1c90b27d2c](https://github.com/openembedded/openembedded-core/commit/1c90b27d2c65cfb4f9debf0272820b6a95942f76) ("kernel: make kernel-base recommend kernel-image, not depend") the way the kernel is deployed into the rootfs silently changed, i.e. there is no build or run time error/warning that the kernel binary is deployed despite one did not want it. 
Note that commit 1c90b27d2c is already in the kirkstone branch.
=> machines: follow kernel deployment changes

recipes-bsp/rcw/rcw_git.bb
Specify the BSD variant used. This fixes the following warning when building on kirkstone:
WARNING: rcw-git-r0 do_populate_lic: QA Issue: rcw: No generic license file exists for: BSD in any provider [license-exists]
=> rcw: Use SPDX-style license

recipes-bsp/u-boot/u-boot-fslc_2022.04.bb, recipes-kernel/linux/linux-fslc.inc
Upstream commit [`dea5e88637 ("lzop: remove recipe from oe-core")`](https://github.com/openembedded/openembedded-core/commit/dea5e8863792dc7bb3324b543e04da4c94a060aa) dropped support of _lzop_ and removed recipe from OE-Core.
Drop _lzop_ dependencies in recipes across the layer, it is not available anymore.
Cc: @Ossanes
=> Remove lzop dependency dropped upstream

recipes-kernel/kernel-modules/kernel-module-isp-vvcam/0001-dwe_isr.c-fix-error-found-by-gcc12.patch, recipes-kernel/kernel-modules/kernel-module-isp-vvcam_4.2.2.16.0.bb
@thochstein 
Another recipe which doesn't build on current master. (i.MX 8M Plus machine specific recipe)
I believe the warning treated as error is legitimate.
Can you check internally what's the way forward?
Less intrusive to my patch is to simple delete the whole 'if' clause which will never ever be executed.
=> kernel-module-isp-vvcam: fix error found by gcc 12

conf/machine/include/imx-base.inc
Properly set provider for i.MX GPU, as noted by bitbake:
```
NOTE: Multiple providers are available for virtual/opencl-icd (imx-gpu-viv, opencl-icd-loader)
Consider defining a PREFERRED_PROVIDER entry to match virtual/opencl-icd
```
=> imx-base.inc: Set virtual/opencl-icd provider for i.MX

recipes-kernel/linux/linux-fslc-imx_5.15.bb, recipes-kernel/linux/linux-fslc-lts_5.15.bb, recipes-kernel/linux/linux-fslc_5.18.bb
- `linux-fslc-imx`: _v5.15.46_
- `linux-fslc-lts`: _v5.15.46_
- `linux-fslc`: _v5.18.3_
`linux-fslc` has been boot-tested on `imx8mn-lpddr4-evk` and `imx8mp-lpddr4-evk` machines, result: **PASS**.
-- andrey
=> Consolidated Kernel (v5.15.46 + v5.18.3)

classes/mfgtool-initramfs-image.bbclass
Close #951 by changing `IMAGE_FSTYPES` to a weak variable
=> classes: mfgtool-initramfs-image use weak variable for IMAGE_FSTYPES

classes/imx-boot-container.bbclass, conf/layer.conf, conf/machine/include/imx-base.inc, dynamic-layers/meta-arm/recipes-bsp/trusted-firmware-a/trusted-firmware-a_%.bbappend, recipes-bsp/imx-atf/imx-atf_2.4.bb, recipes-bsp/imx-mkimage/imx-boot_1.0.bb
This PR adds an extension to be able to build and use [_TF-A  from upstream_](https://git.trustedfirmware.org/TF-A/trusted-firmware-a.git/).
In order to use the upstream _TF-A_ in the BSP, one need to pull `meta-arm` layer into the setup to get the `trusted-firmware-a` recipe and package.
Additional variable `DEFAULT_ATF_PROVIDER` shall be set to point to `trusted-firmware-a` recipe name, so that it would be picked up instead of NXP one. As a continuation of this work, TF-A provider can be made distro-specific, for the moment it is left open in this PR.
Above provider choice (when upstream TF-A is set) requires `COMPATIBLE_MACHINE` definition, which is added via _dynamic-layers_ mechanism.
Verified booting for following machines (upstream TF-A version `v2.7`):
- _imx8mm-lpddr4-evk_: …
=> Support upstream TF-A usage for i.MX8M machines

classes/mfgtool-initramfs-image.bbclass
The fix to allow the user to override the IMAGE_FSTYPES setting for
mfgtool-initramfs-image [1] does break the default behavior by turning
the setting into a no-op:
```
IMAGE_FSTYPES="wic.bmap wic.gz"
```
The layer uses an extra variable SOC_DEFAULT_IMAGE_FSTYPES to override
IMAGE_FSTYPES [2], so use it here.
[1] 0a29050 classes: IMAGE_FSTYPES as weak variable in mfgtool-initramfs-image
[2] 541b8b8 imx-base.inc: Move IMAGE_FSTYPES override to a SoC variable
=> mfgtool-initramfs-image: Fix override of IMAGE_FSTYPES

recipes-bsp/isp-imx/isp-imx_4.2.2.16.0.bb
The source and build directories are usually ${WORKDIR}/build and
${WORKDIR}/${BP} but not always. For example when using devtool they are
different, leading to install failures such as:
cp: cannot stat '.../tmp/work/.../isp-imx/4.2.2.16.0-r0/build/generated/release/bin/*_test': No such file or directory
Fix by using the S and B variables which always point to the correct
directory.
Signed-off-by: Luca Ceresoli <luca.ceresoli@bootlin.com>
=> isp-imx: fix source and build directories

recipes-bsp/imx-mkimage/imx-boot_1.0.bb
When UBOOT_SIGN_ENABLE we want to use the DTB in which mkimage has
added the signature node.
This fix missing signature check in u-boot, same as reported here:
https://community.nxp.com/t5/i-MX-Processors/iMX8-U-Boot-FIT-Image-Signature/m-p/1429547
Should be merged to LTS branches, dunfell & co...
=> imx-boot: Use public key injected DTB when FIT signature is enabled

recipes-graphics/wayland/weston/0001-Revert-protocol-no-found-wayland-scanner-with-Yocto-.patch, recipes-graphics/wayland/weston_9.0.0.imx.bb
This seems to be master only, i.e. on Kirkstone the wayland update is not present.
=> weston: 9.0.0.imx: fix build with latest master

conf/machine/ls1046ardb.conf
LS1046A add shared MAC DTB from Kernel 5.10
Signed-off-by: Jun Zhu <junzhu@nxp.com>
=> conf/machine/ls1046ardb.conf: Add DTB fsl-ls1046a-rdb-usdpaa-shared.dtb

recipes-bsp/imx-atf/imx-atf/0001-Makefile-Suppress-array-bounds-error.patch
Refine the commit message for the patch 0001-Makefile-Suppress-array-bounds-error.patch,
making it clear that the patch is a workaround for an issue in GCC 12,
and that the issue is fixed in GCC 13.
=> imx-atf: Refine array-bounds patch commit message

conf/machine/include/imx8mm-evk.inc, conf/machine/include/imx8mn-evk.inc, conf/machine/include/imx8mp-evk.inc
We ought to add `imx-boot-container` `MACHINEOVERRIDES` only if not
building for `u-boot-imx`. This can be removed once it uses `binman` as
`u-boot-imx` and u-boot-fslc would use same mechanism to build the
container.
=> imx8m*-evk: allow switch between `u-boot-imx` and `u-boot-fslc`

conf/machine/imx8mq-evk.conf
Extend the recent fix to properly configure `imx-boot-container`
machine overide.
Extends: 1650359
=> imx8mq-evk.conf: Extend fix for `u-boot-imx` and `u-boot-fslc`

recipes-bsp/u-boot/u-boot-imx-common_2022.04.inc
Fixes:
```
| /.../tmp/work/imx8mq_evk-fsl-linux/u-boot-imx/2022.04-r0/git/tools/mkeficapsule.c:21:10: fatal error: gnutls/gnutls.h: No such file or directory
|  #include <gnutls/gnutls.h>
|           ^~~~~~~~~~~~~~~~~
```
=> u-boot-imx: Add missing gnutls dependency

classes/fsl-eula-unpack.bbclass
We have an internal use for the license information calculated by class.
=> Rework fsl-eula-unpack.bbclass for reuse

recipes-kernel/linux/linux-imx_5.15.bb
Using underscore '_' in LOCALVERSION makes build failures if you use
deb packages.
Error message:
Subprocess output:dpkg-deb: error: package name has characters that aren't lowercase alphanums or '-+.'
Change '_' to '-' to avoid this problem. It seems that linux-fslc-imx already have this convention
and previous versions of linux-imx also had.
Signed-off-by: Peter Bergin <peter@berginkonsult.se>
=> linux-imx: change LOCALVERSION to not use underscore

recipes-bsp/imx-atf/imx-atf_2.6.bb
Fixes #1178
I tried to build imx-atf with this patch in kirkstone and it builds fine. However, I assume that binutils will not be backported to kirkstone in openbedded-core and this patch will not be needed in kirkstone.
=> imx-atf: fix build error with binutils 2.39

recipes-kernel/kernel-modules/kernel-module-isp-vvcam_4.2.2.16.0.bb
This recipe fails when using devtool:
ERROR: [...] do_populate_lic: QA Issue: kernel-module-isp-vvcam: LIC_FILES_CHKSUM points to an invalid file: [...]/build/tmp/work/nitrogen8mp-fslc-linux/kernel-module-isp-vvcam/4.2.2.16.0-r0/git/vvcam/LICENSE [license-checksum]
How to reproduce:
devtool modify kernel-module-isp-vvcam
bitbake kernel-module-isp-vvcam
Fix by pointing to a path relative to S.
Signed-off-by: Luca Ceresoli <luca.ceresoli@bootlin.com>
=> kernel-module-isp-vvcam: fix LIC_FILES_CHKSUM when using devtool

recipes-security/optee-imx/optee-os/0008-no-warn-rwx-segments.patch, recipes-security/optee-imx/optee-os_3.17.0.imx.bb
binutils 2.39 started to produce warning on RWX LOAD segments, which breaks the linking process of `optee-os`.
Upstream `optee-os` package has patch [`ac425901 ("arm/optee-os: backport RWX permission error patch")`](https://github.com/jonmason/meta-arm/commit/ac4259011f4c8cec01191828014487ccc5de73ca) integrated, which has been backported in OP-TEE from [`PR #5475`](https://github.com/OP-TEE/optee_os/pull/5474) targeting master in upstream.
Port upstream `optee-os` commit into NXP fork of `optee-os`.
**Cc**: @thochstein
=> optee-os: fix build with binutils 2.39

recipes-bsp/imx-atf/imx-atf/rwx-segments.patch, recipes-bsp/imx-atf/imx-atf_2.6.bb
Reverts #1179 in favour of a binutils agnostic fix. This now works also on kirkstone with binutils 2.38.
=> reworked: "imx-atf: fix build error with binutils 2.39"

recipes-bsp/mc-utils/mc-utils_git.bb, recipes-dpaa2/restool/restool_git.bb
This saves a QA warning per recipe an -if `create-spdx` an error for unknown license
=> License fixes

recipes-bsp/imx-atf/imx-atf_2.6.bb, recipes-graphics/cairo/cairo_%.bbappend, recipes-graphics/imx-gpu-viv/imx-gpu-viv_6.4.3.p4.2-aarch64.bb
When clang is default compiler, we need to ensure that its added as
dependency as well.
Reported-by: Cliff Brake <cbrake@bec-systems.com>
=> imx-atf: Use clang when using toolchain-clang defaults

recipes-graphics/gtk+/gtk+3_%.bbappend
Last commit had a thinko, where it should be removing x11 only if x11 is not in distro features, but it ended up doing that for wayland
=> gtk+3: Fix logical error in removing x11

recipes-graphics/gtk+/gtk+3_%.bbappend
The original intent of dropping x11 support from the package was so only wayland would be supported. The fix in efcb2fe and 7447f7c removes that. However, it keeps the idea that the x11 packageconfig should be disallowed from being added if x11 is not in the distro features. This was never the intent of the original logic, and since the default is to enable x11 packageconfig if and only if x11 is a distro feature, just drop the logic entirely.
=> gtk+3: Drop x11 config logic

recipes-graphics/imx-gpu-viv/imx-gpu-viv-6.inc
The GPU drivers do not support 8M Mini, so properly exclude them from PACKAGES so the user gets an earlier indication of a problem:
```
$ bitbake vulkan-loader
ERROR: Nothing RPROVIDES 'libvulkan-imx' (but /.../poky/meta/recipes-graphics/vulkan/vulkan-loader_1.3.216.0.bb RDEPENDS on or otherwise requires it)
ERROR: Required build target 'vulkan-loader' has no buildable providers.
Missing or unbuildable dependency chain was: ['vulkan-loader', 'libvulkan-imx']
```
=> imx-gpu-viv: Mark libvulkan-imx unavailable for 8M Mini

recipes-graphics/imx-gpu-viv/imx-gpu-viv-6.inc
@thochstein 
Wouldn't we need to remove the OpenCL package(s) for the i.MX 8M Mini in the same way we do it for Vulkan?
AFAIK the Mini doesn't support OpenCL too.
@otavio 
This has already been backported to kirkstone and that is where I initially saw the error, so this would eventually need to go into kirkstone too.
=> imx-gpu-viv: remove vulkan files if not packaged

recipes-graphics/imx-gpu-viv/imx-gpu-viv-6.inc
This configuration is experimental and has never been fully tested.
See #1212
=> imx-gpu-viv: Add support for i.MX 8 without Wayland

recipes-graphics/wayland/weston_10.0.0.imx.bb
The `weston_10.0.0.imx` now depends on `freerdp` which in turn pulls some unrelated big dependencies like `cups` and `gstreamer`.
```
| # meta-freescale/recipes-graphics/wayland/weston_10.0.0.imx.bb
| PACKAGECONFIG[rdp] = "-Dbackend-rdp=true,-Dbackend-rdp=false,freerdp"
|
| PACKAGECONFIG:append = " \
|    rdp \
|    ${@bb.utils.filter('DISTRO_FEATURES', '${PACKAGECONFIG_OPENGL}', d)}"
```
```
| # meta-openembedded/meta-oe/recipes-support/freerdp/freerdp_2.8.0.bb
| PACKAGECONFIG ??= " \
|     ${@bb.utils.filter('DISTRO_FEATURES', 'directfb pam pulseaudio wayland x11', d)}\
|     gstreamer cups pcsc \
| "
|
| PACKAGECONFIG[cups] = "-DWITH_CUPS=ON,-DWITH_CUPS=OFF,cups"
| PACKAGECONFIG[gstreamer] = "-DWITH_GSTREAMER_1_0=ON,-DWITH_GSTREAMER_1_0=OFF,gstreamer1.0 gstreamer1.0-plugins-base"
``` …
=> weston: disable rdp as it pulls in some big dependencies

recipes-graphics/wayland/weston_10.0.0.imx.bb
This can cause problem by creating unknown packageconfigs by concatenating the strings
=> weston: Add missing space before appending to PACKAGECONFIG

recipes-graphics/wayland/weston_10.0.0.imx.bb
Previous commit did not really work because we are using bb.utils.filter and that removed the artificial space sadly. Therefore add it outside this function call.
=> weston: Fix the append logic

recipes-graphics/imx-gpu-viv/imx-gpu-viv-6.inc
The resent removal of gpu features for SoC which don't support the feature had some side effects.
@thochstein  I know that I proposed removing OpenCL, sorry about that.
The commits address three OE build errors.
=> Some fixes for imx-nxp-bsp

recipes-graphics/wayland/weston_10.0.0.imx.bb
When removing rdp as default dependency a hidden buildtime dependency on libdrm is uncovered for targets using fbdev as backend and g2d as renderer. As a result compiling for i.MX6 will fail due to missing libdrm headers.
Add libdrm to DEPENDS for imxfbdev.
Signed-off-by: Markus Niebel <Markus.Niebel@ew.tq-group.com>
=> weston_10.0.0.imx: add build dependency on libdrm

recipes-graphics/imx-gpu-viv/imx-gpu-viv-6.inc
OpenVX is fully supported on i.MX 8 QuadMax and 8 QuadPlus. A recent change removed OpenVX packages except for this case. This was a mistake, since there is in fact limited OpenVX support provided on other i.MX 8 machines as needed for i.MX machine learning packages.
Fixes: 09e2ce3
=> imx-gpu-viv: Allow limited OpenVX support

conf/machine/include/imx-base.inc, recipes-graphics/imx-gpu-viv/imx-gpu-viv-6.inc, recipes-graphics/vulkan/vulkan-loader_%.bbappend
Vulkan is disabled on meta-freescale for 8M Mini since ee92b5a8, so add the same logic to not recommends libvulkan-imx on this machines.
- imx-base.inc: Introduce imxvulkan override
All iMX8 modules with the imxgpu override support Vulkan with a
single exception for the iMX8M Mini that uses the mx8mm override.
- vulkan-loader: use the imxvulkan override in recommends
With this the libvulkan-imx is recommends only when the machine
supports Vulkan.
- imx-gpu-viv: use the imxvulkan override for libvulkan
Signed-off-by: Jose Quaresma <jose.quaresma@foundries.io>
=> vulkan-loader: iMX8M Mini doesn't support vulkan

classes/fsl-dynamic-packagearch.bbclass
To reproduce the problem
Add to local.conf:
require conf/multilib.conf
MULTILIBS = "multilib:lib32"
DEFAULTTUNE:virtclass-multilib-lib32 = "armv7athf-neon-vfpv4" 
IMAGE_INSTALL_append = "lib32-libusb1"
Build image with:
'bitbake core-image-minimal'
The build will fail during do_rootfs/do_populate_sdk on lib32-wayland-protocols package
=> Fix the image/SDK generation for packages built for MACHINE_SOCARCH with MULTILIB support

dynamic-layers/qt4-layer/recipes-qt4/qt4/qt4-imx-support.inc
To be backported to LTS also. Sorry for the typo
=> qt4-imx-support: fix typo

recipes-kernel/linux/linux-mfgtool.inc
Using a KERNEL_PACKAGE_NAME without the "linux-" prefix causes parsing errors like:
```
ERROR: [...]/meta-freescale/recipes-kernel/linux/linux-fslc-mfgtool_5.4.bb: QA Issue: [...]/meta-freescale/recipes-kernel/linux/linux-fslc-mfgtool_5.4.bb: Variable RDEPENDS is set as not being package specific, please fix this. [pkgvarcheck]
```
Fix this by setting KERNEL_PACKAGE_NAME to "linux-mfgtools", which also reflects the value mentioned in the [original commit's message](https://github.com/Freescale/meta-freescale/commit/9a5a143d97345871d4c258ce6ce13567d87f5ba7).
=> linux-mfgtool.inc: Fix KERNEL_PACKAGE_NAME

recipes-kernel/linux/linux-fslc-imx_5.15.bb
Change log:
- 4b8b3fd681df Merge pull request #602 from angolini/5.15-2.1.x-imx-bump
- d0ee47da9a09 Merge tag 'v5.15.60' into 5.15-2.1.x-imx
- 6bc02055c373 Merge tag 'v5.15.59' into 5.15-2.1.x-imx
- 647349ddd965 Merge tag 'v5.15.58' into 5.15-2.1.x-imx
- 8c8464177402 Merge tag 'v5.15.57' into 5.15-2.1.x-imx
- 143ca87ada4a Merge tag 'v5.15.56' into 5.15-2.1.x-imx
- a34846a37808 Merge tag 'v5.15.55' into 5.15-2.1.x-imx
- 19ac7f0d6628 Merge tag 'v5.15.54' into 5.15-2.1.x-imx
- dea6099cfa06 Merge tag 'v5.15.53' into 5.15-2.1.x-imx
- 39a72c404f21 drm: bridge: it6161: add missing gpio consumer header
- 200ac21eb0f5 ARM: mach-imx: conditionally disable some functions from busfreq-imx
- 4af46d106d63 gpio: fix enabling GPIO_VF610
- 7af0d9d37f0c cert host tools: Stop complaining about deprecated …
=> linux-fslc-imx: upgrade to lf-5.15.52-2.1.0 from NXP

recipes-graphics/vulkan/vulkan-loader_1.2.182.0.bbappend
The logic to move the .so into the main package is incorrect and results in all libraries being moved to the dev package, causing a QA error like the following:
```
ERROR: imx-gpu-sdk-5.7.1-r0 do_package_qa: QA Issue: imx-gpu-sdk rdepends on vulkan-loader-dev [dev-deps]
```
=> vulkan-loader: Fix library packaging

recipes-graphics/wayland/weston/0001-tests-Add-dependency-on-screenshooter-client-protoco.patch, recipes-graphics/wayland/weston_10.0.0.imx.bb
tests: Add dependency on screenshooter client protocol
Given that the test-helper code relies on the screenshooter protocol, make sure it's available for us to build, and the dependency ensures we build in order.
Link: https://github.com/wayland-project/weston
Commit: 2ac6b6b084a877adde64db7faff2ed22eb3ea97a
Fixes: #1273
Signed-off-by: Maxim Paymushkin <maxim.paymushkin@gmail.com>
=> weston: fix build test-internal-screenshot

recipes-bsp/imx-mkimage/imx-mkimage_git.bb
Replace do_compile() with EXTRA_OEMAKE:
- The cd ${S} is redundant
- The clean operation is already done in do_configure()
- The two steps building the bin and mkimage_mx8 are the default behavior of the top-level Makefile with target mkimage_mx8
Drop redundant cd ${S} in do_install().
=> [Backport Kirkstone] imx-mkimage: Simplify compile and install tasks

classes/fsl-eula-unpack.bbclass
bb.data.update_data is removed in poky. https://github.com/yoctoproject/poky/commit/d8e9ee8fd53b7620e72b2dfebb2e8d464b737dbb . Fixes https://github.com/Freescale/meta-freescale/issues/1295
=> bb.data.update_data is deprecated

classes/imx-boot-container.bbclass
Needed for platforms requiring other firmware files than the DDR (like the HDMI/DP firmware on i.MX 8MQ).
Signed-off-by: Gary Bisson <gary.bisson@boundarydevices.com>
=> imx-boot-container: add extra firmware copy from deploydir

recipes-extended/jailhouse/jailhouse_0.12.bb
Also fix installation path of the modules and firmware when usrmerge is enabled.
Signed-off-by: Jose Quaresma <jose.quaresma@foundries.io>
=> jailhouse: update to lf-5.15.32_2.0.0 branch

dynamic-layers/openembedded-layer/recipes-dpaa/fmc/fmc_git.bb, recipes-bsp/atf/qoriq-atf-2.4.inc, recipes-bsp/mc-utils/mc-utils_git.bb, recipes-bsp/rcw/rcw_git.bb, recipes-bsp/u-boot/u-boot-qoriq_2021.04.bb, recipes-devtools/qemu/qemu-qoriq_4.2.bb, recipes-devtools/qoriq-cst/qoriq-cst_git.bb, recipes-dpaa/eth-config/eth-config_git.bb, recipes-dpaa/flib/flib_git.bb, recipes-dpaa/fmlib/fmlib_git.bb, recipes-dpaa2/aiopsl/aiopsl_git.bb, recipes-dpaa2/dce/dce_git.bb, recipes-dpaa2/gpp-aioptool/gpp-aioptool_git.bb, recipes-dpaa2/restool/restool_git.bb, recipes-dpaa2/spc/spc_git.bb, recipes-extended/dpdk/dpdk-20.11.inc, recipes-extended/dpdk/dpdk_19.11-20.12.bb, recipes-extended/libpkcs11/libpkcs11_git.bb, recipes-extended/odp/odp.inc, recipes-extended/ofp/ofp_git.bb, recipes-extended/ovs-dpdk/ovs-dpdk_2.15.bb, recipes-extended/secure-obj/secure-obj.inc, recipes-extended/tsntool/tsntool_git.bb, recipes-kernel/ceetm/ceetm_git.bb, recipes-kernel/linux/linux-qoriq_5.10.bb, recipes-security/optee-qoriq/optee-client.nxp.inc, recipes-security/optee-qoriq/optee-os.nxp.inc, recipes-security/optee-qoriq/optee-test.nxp.inc
Fetch QorIQ's source code from github.com/nxp-qoriq, as original source.codeaurora.org/external/qoriq will stop to access from April 2023.
Signed-off-by: Jun Zhu <junzhu@nxp.com>
=> Switch NXP QorIQ repositories to github.com

dynamic-layers/ivi/recipes-graphics/wayland/weston-init/weston.ini, recipes-graphics/wayland/weston-init.bbappend, recipes-graphics/wayland/weston-init/imx-nxp-bsp/weston.ini
The main recipe now sets xwayland=true in weston.ini, so drop it from here.
=> weston-init: Drop redundant xwayland=true setting

conf/machine/imx6qdlsabreauto.conf, conf/machine/imx6qdlsabresd.conf, conf/machine/imx6slevk.conf, conf/machine/imx6sllevk.conf, conf/machine/imx6sxsabreauto.conf, conf/machine/imx6sxsabresd.conf, conf/machine/imx6ulevk.conf, conf/machine/imx6ullevk.conf, conf/machine/imx6ulz-14x14-evk.conf, conf/machine/imx7dsabresd.conf, conf/machine/imx7ulpevk.conf, conf/machine/imx8mq-evk.conf, conf/machine/imx8qm-mek.conf, conf/machine/include/imx-base.inc, conf/machine/include/imx8dxl-evk.inc, conf/machine/include/imx8mm-evk.inc, conf/machine/include/imx8mn-evk.inc, conf/machine/include/imx8mp-evk.inc, conf/machine/include/imx8x-mek.inc, recipes-bsp/firmware-imx/firmware-nxp-wifi_1.0.bb
Add NXP WiFi/BT firmware support, enabled by `MACHINE_FEATURES`, and tied into existing NXP development boards.
=> Add NXP WiFi/BT support

recipes-multimedia/libimxvpuapi/libimxvpuapi2_2.2.2.bb
* imx6-coda: Skip incomplete frames instead of just reporting them
* imx6-coda: Only flush bit buffer when framebuffers were registered This prevents misleading error-level log lines from occurring
* imx6-coda: Prefer semi planar modes over fully planar ones
* imx8m-hantro: Reset decoder write_offset to fill_level when moving read_offset
* Add imx_vpu_api_is_color_format_tiled() function
* update waf to 2.0.24
* Add closed_gop_interval field to ImxVpuApiEncOpenParams This allows for enforcing regularly occurring IDR boundaries when encoding to h.264
* imx8m-hantro: Fix supported decoder color formats and include tiled formats
* Fix and improve h.264 max level estimation for encoding
* imx6-coda: Use 2-row alignment in encoder
* imx6-coda: Fix JPEG encoding quantization parameter handling …
=> libimxvpuapi2: Upgrade to version 2.2.2

recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_1.20.0.imx.bb
This ensures that clang based distributions can compile this recipe, since it uses nested functions ( bad bad ) which is not supported by clang
=> gstreamer1.0-plugins-bad: Force gcc compiler always

recipes-security/optee-imx/optee-os_3.17.0.imx.bb, recipes-security/optee-imx/optee-test_3.17.0.imx.bb
It does not compile with clang, all work to get it compiling with clang has gone into 3.18+ ( see meta-arm ) until imx version revs up to 3.18 lets use gcc always to build it
=> optee-os: Use gcc compiler

recipes-bsp/u-boot/u-boot-fslc-common_2023.01.inc
This merges following fixes:
386ee4eecc8 u-boot-initial-env: rework make target 5404dfcc4db arm: rmobile: rzg2_beacon: Enable alternative Ethernet PHY edd9c891d20 arm: dts: rz-g2-beacon-u-boot: Fix QSPI Regression 14165918766 pylibfdt: Fix disable version normalization 519e6641dbd cmd: pxe_utils: Limit fdtcontroladdr usage to non-fitImage bee3551e000 Revert "Revert "cmd: pxe_utils: Check fdtcontroladdr in label_boot"" ab644db9ba0 rockchip: Fix the broken Video out for rk3288 boards 4671435c54c i2c: uniphier-f: correct error recovery f8548ce0e09 imx7d-pico: Fix the name of the u-boot.dtsi file 1b697407aed powerpc/mpc85xx: socrates: Re-enable building u-boot-socrates.bin a2e0b041d66 arm: stm32mp: Fix board_get_usable_ram_top() again 60bba6e2052 efi_loader: populate console handles in system …
=> u-boot-fslc: Bump to 386ee4eecc8 revision

recipes-kernel/linux/linux-fslc-lts_5.15.bb
Kernel repository has been upgraded up to v5.15.78 from stable korg.
- a86fe5cb4fe9 Merge pull request #618 from angolini/5.15.x+fslc-bump
- 252c1d02bdc0 Merge tag 'v5.15.86' into 5.15.x+fslc
- a0f39cf81199 Merge tag 'v5.15.85' into 5.15.x+fslc
- 84f811fea1c5 Merge tag 'v5.15.84' into 5.15.x+fslc
- 0892f11a056f Merge tag 'v5.15.83' into 5.15.x+fslc
- ff29b3af0c5e Merge tag 'v5.15.82' into 5.15.x+fslc
- 65648211dafe Merge tag 'v5.15.81' into 5.15.x+fslc
- ef2e16b43d6d Merge tag 'v5.15.80' into 5.15.x+fslc
- 90ffbb727c51 Linux 5.15.86
- 3082f8705e82 pwm: tegra: Fix 32 bit build
- caa40d1f8524 mfd: qcom_rpm: Use devm_of_platform_populate() to simplify code
- 408dbaa06578 extcon: usbc-tusb320: Call the Type-C IRQ …
=> linux-fslc-lts: update to v5.15.86

recipes-kernel/linux/linux-fslc-imx_5.15.bb
- 7f663d3247e3 Merge pull request #617 from dv1/duplicate-sysfs-path-fix
- 437f5776f40f Merge pull request #619 from angolini/5.15-2.1.x-imx-bump
- d508464f2ca1 Merge tag 'v5.15.86' into 5.15-2.1.x-imx
- 347b86f408db Merge tag 'v5.15.85' into 5.15-2.1.x-imx
- f0b0000c0575 Merge tag 'v5.15.84' into 5.15-2.1.x-imx
...
=> linux-fslc-imx: update to v5.15.86

recipes-graphics/imx-gpu-apitrace/imx-gpu-apitrace_10.0.0.bb, recipes-graphics/libva/libva_%.bbappend, recipes-graphics/piglit/piglit_%.bbappend, recipes-multimedia/gstreamer/gstreamer1.0-omx_%.bbappend, recipes-sato/webkit/webkitgtk_%.bbappend
Fixes build errors like
2.38.3-r0/webkitgtk-2.38.3/Source/WebCore/platform/graphics/egl/GLContextEGL.cpp:198:59: error: invalid 'static_cast' from type 'GLNativeWindowType' {aka 'long unsigned int'} to type 'EGLNativeWindowType' {aka 'wl_egl_window*'}
198 |         surface = eglCreateWindowSurface(display, config, static_cast<EGLNativeWindowType>(window), nullptr);
|                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
=> Fix misc recipes to build with imx  gpu drivers

recipes-bsp/u-boot/u-boot-fslc-common_2023.01.inc
This merges following fixes:
- 452c07a6410 arm: dts: imx8mn-u-boot: use versioned ddr4 firmware
- ee92ca28498 Revert "config: tools only: add VIDEO to build bmp_logo"
=> u-boot-fslc: Bump to 3b524eeb247 revision

recipes-bsp/u-boot/u-boot-fslc_2023.01.bb
This fix comes from https://github.com/Freescale/meta-freescale/issues/1399
Since U-Boot 2022.04 the host tool mkeficapsule requires gnutls. Some boards, i.e. imx8mp_rsb3720a1, imx8mm-cl-iot-gate, etc. have EFI enabled by default and fail to find <gnutls/gnutls.h> when building.
Add gnutls-native to the dependency to solve building issues.
=> u-boot-fslc: add gnutls-native dependency

recipes-kernel/linux/linux-fslc-imx_5.15.bb
This bumps the kernel 5.15-2.2.x-imx to 3248ffcb12d1
- 3248ffcb12d1 Merge pull request #621 from MrCry0/5.15-2.2.x-imx-lpuart
- b9ae52e89c61 serial: fsl_lpuart: fix merging issue
=> linux-fslc-imx: fix fsl_lpuart boot issue

recipes-kernel/linux/linux-fslc-lts_5.15.bb
Missed bumping LINUX_VERSION. Fix it.
Fixes: 9f2c6a40 ("linux-fslc-lts: update to v5.15.91")
=> linux-fslc-lts: fix linux version

recipes-kernel/linux/linux-fslc-lts_5.15.bb
Kernel repository has been upgraded up to v5.15.91 from stable korg.
- 4d20f1dcda24 Merge pull request #622 from MrCry0/5.15.x+fslc
- dd6ac8bf3555 Merge tag 'v5.15.91' into 5.15.x+fslc
- 9cf4111cdf94 Linux 5.15.91
- 14cc13e433e1 perf/x86/amd: fix potential integer overflow on shift of a int
- 033636b32258 netfilter: conntrack: unify established states for SCTP paths
- 0b08201158f1 x86/i8259: Mark legacy PIC interrupts with IRQ_LEVEL
- b57740036792 block: fix and cleanup bio_check_ro
- 1d152437e46f kbuild: Allow kernel installation packaging to override pkg-config
- a1964688582d cpufreq: governor: Use kobject release() method to free dbs_data
- 7c513ced0dec cpufreq: Move to_gov_attr_set() to cpufreq.h
- cf7a08622d2b Revert "Input: synaptics - switch touchpad on HP Laptop …
=> [Backport kirkstone] linux-fslc-lts: update to v5.15.91

dynamic-layers/openembedded-layer/recipes-devtools/cst/files/0001-fix-err-msg-linking.patch, dynamic-layers/openembedded-layer/recipes-devtools/cst/imx-cst_3.3.1.bb
NXP uses weaken to solve a conflict in linking.
The linker in Ubuntu seems to ignore weak symbols does
not link libcrypto at all.
The patch fixes the conflict in the code itself.
It restricts the scope of err_msg to the module.
Signed-off-by: Walter Schweizer <walter.schweizer@siemens.com>
=> On Ubuntu 22.04(LTS) cst fails to link with libcrypto.

classes/use-imx-security-controller-firmware.bbclass, conf/machine/imx8ulp-lpddr4-evk.conf, conf/machine/include/imx-base.inc, conf/machine/include/imx8ulp-evk.inc, recipes-bsp/firmware-sentinel/firmware-sentinel_0.8.bb, recipes-bsp/firmware-upower/firmware-upower_1.1.0.bb, recipes-bsp/imx-mkimage/imx-boot_1.0.bb
I have only built the source code. I don't have the board so I cannot test it. In case anyone is available to test, please, let me know the result.
It's important to note that the `IMXBOOT_TARGETS` tries to use dualboot, but the `m33` binaries are not included:
```
IMXBOOT_TARGETS_SD   = "flash_singleboot flash_dualboot"
IMXBOOT_TARGETS_FSPI = "flash_dualboot_flexspi"
IMXBOOT_TARGETS_ND   = ""
```
=> Add i.MX 8ULP Machines

recipes-bsp/imx-mkimage/imx-boot_1.0.bb, recipes-bsp/u-boot/u-boot-imx_2022.04.bb
With the imx bsp override the u-boot-imx does
not compile imx-boot-tools. This causes an error
in imx-boot because it does not find imx-boot-tools.
Signed-off-by: Rodrigo M. Duarte <rodrigo.duarte@ossystems.com.br>
=> u-boot-imx: Change the imx bsp override to generic bsp

recipes-bsp/boot-format/boot-format_git.bb
https is the preferred protocol especially with github
Fixes
WARNING: boot-format-git-r6 do_fetch: URL: git://github.com/nxp-qoriq-yocto-sdk/boot-format;nobranch=1 uses git protocol which is no longer supported by github. Please change to ;protocol=https in the url.
=> boot-format: Use https protocol with github

conf/machine/include/imx-base.inc, recipes-multimedia/gstreamer/gstreamer1.0-libav/0001-libav-Fix-for-APNG-encoder-property-registration.patch, recipes-multimedia/gstreamer/gstreamer1.0-libav_1.20.3.bb, recipes-multimedia/gstreamer/gstreamer1.0-plugins-ugly_1.20.3.bb, recipes-multimedia/gstreamer/gstreamer1.0-rtsp-server_1.20.3.bb
oe-core has moved to gstreamer 1.22.0 and recipes which don't have an imx version can no longer be built. Add older version of those components to be used with the gstreamer 1.20.3.imx.
=> gstreamer: add recipes for upstream 1.20.3 versions

recipes-bsp/imx-mkimage/files/0001-iMX8M-soc.mak-use-native-mkimage-from-sysroot.patch, recipes-bsp/imx-mkimage/imx-boot_1.0.bb, recipes-bsp/imx-mkimage/imx-mkimage_git.inc
mkimage tool is provided as a part of sysroot and should not be used as a local copy, since it contains runtime dependencies which local copy does not account for.
Drop the local copy on mkimage, introduce the patch that fixes mkimage invocations in build system.
(cherry picked from commit c59f817b0d1ee70ef224405ff8acd31e0743ed91)
=> imx-mkimage: use mkimage tool from sysroot

conf/machine/include/imx-base.inc, recipes-multimedia/gstreamer/gstreamer1.0-libav_1.20.3.imx.bb, recipes-multimedia/gstreamer/gstreamer1.0-plugins-ugly_1.20.3.imx.bb, recipes-multimedia/gstreamer/gstreamer1.0-rtsp-server_1.20.3.imx.bb
These recipes are copies of oe-core 1.20.3 that are not available anymore upstream on the master branch.
The requirement to have them is because they are dependencies of the other ones imx specific gstreamer forks on the layer. So make their names maching the exisng ones will make it more safe.
=> gstreamer: rename the version to be imx specific

recipes-extended/dpdk/dpdk.inc, recipes-extended/dpdk/dpdk/0001-examples-fix-Arm-build-with-GCC-12.patch, recipes-extended/dpdk/dpdk_19.11-20.12.bb, recipes-multimedia/gstreamer/imx-gst1.0-plugin/0001-aiurdemux-Fix-type-of-USER_DATA_LOCATION.patch, recipes-multimedia/gstreamer/imx-gst1.0-plugin/0002-aiurdemux.h-Include-glib-gprintf.h-for-g_printf-prot.patch, recipes-multimedia/gstreamer/imx-gst1.0-plugin/0003-grecorder-Fix-build-with-clang.patch, recipes-multimedia/gstreamer/imx-gst1.0-plugin/0004-gstimxcommon-Return-0-instead-of-NULL-for-a-function.patch, recipes-multimedia/gstreamer/imx-gst1.0-plugin/0005-aiurstreamcache-Include-gst-gstinfo.h.patch, recipes-multimedia/gstreamer/imx-gst1.0-plugin/0006-Fix-typecast-warnings-found-with-clang.patch, recipes-multimedia/gstreamer/imx-gst1.0-plugin/0007-gstimxv4l2-Fix-typecasting-errors.patch, recipes-multimedia/gstreamer/imx-gst1.0-plugin/0008-beepdec-Declare-beep_register_external_typefinders.patch, recipes-multimedia/gstreamer/imx-gst1.0-plugin/0009-gstimxv4l2.c-Fix-incompatible-integer-to-pointer-con.patch, recipes-multimedia/gstreamer/imx-gst1.0-plugin/0010-provide-declaration-for-aiur_register_external_typef.patch, recipes-multimedia/gstreamer/imx-gst1.0-plugin_git.bb
These warnings are already there, gcc just does not error on them yet but clang does. Therefore clean them up a bit
=> imx-gst1.0-plugin: Fix build with clang

recipes-bsp/isp-imx/isp-imx_4.2.2.19.0.bb
- NXP decided to change the binaries without updating the version [1]
- Here is NXP changelog: [LF-8298] Fix intermittent build break "Error copying file ... isi_common.h".
[1] https://github.com/nxp-imx/meta-imx/commit/43c0642e
=> isp-imx: Update isp-imx_4.2.2.19.0.bb to commit a7ef904

recipes-extended/jailhouse/jailhouse_0.12.bb
Update jailhouse to the lf-5.15.71_2.2.0 release and also extend the default compatible machine list to include 8ulp and mx93, since they are now supported on this release.
=> jailhouse: update to lf-5.15.71_2.2.0

conf/machine/include/imx-base.inc
8MQ video is not working. The problem is traced to a change in `weston.ini`, specifically that the file is now from OE-Core layer instead of meta-freescale. This problem is traced to the move of the `imx-boot-container` override [1], specifically that the override was moved with a trailing `:` that inserts an empty override.
```
MACHINEOVERRIDES="aarch64:armv8a:use-nxp-bsp:imx-generic-bsp:imx-nxp-bsp:imxdrm:imxvpu:imxgpu:imxgpu3d:imxvulkan:mx8-generic-bsp:mx8-nxp-bsp:mx8m-generic-bsp:mx8m-nxp-bsp:mx8mq-generic-bsp:mx8mq-nxp-bsp:imx-boot-container::imx8mq-evk"
```
[1] https://github.com/Freescale/meta-freescale/commit/0ee4cb24eba5171da75ab8eeb72c7eab06083339
=> imx-base.inc: Fix 8M overrides

classes/use-imx-security-controller-firmware.bbclass, recipes-bsp/firmware-imx/firmware-imx-8_8.18.bb, recipes-bsp/imx-sc-firmware/imx-sc-firmware_1.15.0.bb, recipes-bsp/imx-seco/imx-seco_5.9.0.bb
SECO/SC FW/HDMI FW and friends should not be restricted to imx-nxp-bsp. If one wants to build machines for a mainline kernel / user space these would be required to build the boot container too.
=> imx: fw: allow to build for mainline bsp too

classes/imx-boot-container.bbclass, conf/machine/include/imx-base.inc
Moving the override from the <machine>.conf files to the common imx-base.inc and setting the use of imx-boot-container unconditionally on the used SoC makes the use of an extra override obsolete.
Simply set UBOOT_PROVIDES_BOOT_CONTAINER depending on the used SoC is enough. Both the U-Boot recipe and the class implementing the logic don't need the override but only look at the variable.
This also simplifies overriding the value set in imx-base.inc in an individual <machine>.conf should that be needed.
=> imx-boot-container: drop from machine overrides

conf/machine/include/imx-base.inc
This pull request adds the ability to dynamically choose whether or not to use the boot container in the imx-base.inc file. The change is based on the current default bootloader being used (u-boot-imx). This should improve the flexibility of the code and make it easier to customize for different use cases.
In addition, a typo in a comment was fixed in the first commit of this pull request.
=> Add boot container dynamic selection to imx-base.inc

classes/image_populate_mfgtool.bbclass, classes/mfgtool-initramfs-image.bbclass, conf/machine/include/imx-base.inc, recipes-devtools/uuu/uuu-bin_1.4.243.bb
The class provides the infrastructure for MFGTOOL generation and is tied
to images. To generate the bundle, the task populate_mfgtool must be
called. For example:
,----[ Running populate_mfgtool for core-image-minimal image ]
| $: bitbake core-image-minimal -c populate_mfgtool
`----
The class behavior is controlled through the MFGTOOL_SCRIPT variable. The
MFGTOOL_SCRIPT variable itself specifies a space-separated list of the
scripts to enable. Following the scripts, you can determine the behavior
of each script by providing up to two order-dependent arguments, which
are separated by commas. You can omit any argument you like but must
retain the separating commas. The order is important and specifies the
following:
1. Extra dependencies that should be added to the do_populate_mfgtool
task, …
=> Allow generation of mfgtool bundle

classes/image_populate_mfgtool.bbclass
Eventually, multiple `uuu` script may install same binaries. We need to
ensure we install them once, otherwise it'll fail as it might try to
override a existing binary.
This commit ensure all dependencies and binaries are mentioned once,
removing duplication.
Fixes: ae7af6f8 ("classes/image_populate_mfgtool: init")
=> classes/image_populate_mfgtool: avoid error copying duplicated files

recipes-bsp/atf/qoriq-atf_2.6.bb
mbedtls is included in SCR_URI into fetched source code tree.
=> qoriq-atf: Remove mbedtls from DEPENDS

recipes-bsp/firmware-imx/firmware-nxp-wifi_1.0.bb
=> firmware-nxp-wifi: Fix license after update to lf-6.1.1_1.0.0

recipes-graphics/wayland/weston_10.0.1.imx.bb
Otherwise xwayland.pc would not be present in sysroot, this leads to some xwayland configs missing like have_listenfd, have_glamor.
=> weston: add xwayland to DEPENDS for PACKAGECONFIG xwayland

recipes-kernel/linux/linux-imx.inc
Fixes: dca02c80 ("linux-imx: remove SoC-specific defconfig to use in-tree defconfig")
=> linux-imx: remove SoC-specific defconfig to use in-tree defconfig

recipes-kernel/kernel-modules/kernel-module-nxp89xx_git.bb
Update to the version used in NXP BSP release L6.1.1-1.0.0.
=> kernel-module-nxp89xx: upgrade to lf-6.1.1_1.0.0

dynamic-layers/meta-arm/recipes-bsp/trusted-firmware-a/trusted-firmware-a_%.bbappend
Some board or user could like to change the build or install target of the ARM trusted firmware.
Only set those variables if they are empty.
=> dynamic-layers: meta-arm: don't force build nor install target in TF-A

recipes-bsp/firmware-imx/imx-boot-firmware-files_8.18.bb
Fixes: 90df14f9 ("imx-boot-firmware-files: consolidate deploy firmware files across SoCs")
=> imx-boot-firmware-files: Avoid Cadence firmware for in mx8m

conf/machine/imx23evk.conf, conf/machine/imx28evk.conf, conf/machine/include/imx-base.inc
This unbreaks `IMAGE_FEATURES:append = " splash"`, as since poky `46d287faa6b72778dbe7652cde71e5def0f94747`, the "splash" image feature depends on the "screen" machine feature. Since `MACHINE_FEATURES` is an unconditional set (` = `) in `imx-base.inc`, appending to `MACHINE_FEATURES` in `local.conf` is not possible.
=> Add screen machine feature to all machine configurations

recipes-graphics/imx-gpu-viv/imx-gpu-viv-6.inc
Amend 6e41d851e71505183ff021b07c317e5290571916 and move cl_viv_vx_ext.h header to the libclc-imx-dev package. Missing value for ${FILES:libclc-imx-dev} caused Bad substitution error for imx8mm builds.
=> imx-gpu-viv: fix libclc-imx packaging

recipes-kernel/linux/linux-fslc-imx_6.1.bb, recipes-kernel/linux/linux-fslc_6.1.bb, recipes-kernel/linux/linux-imx/ARM-imx_v7_defconfig-Remove-KERNEL_LZO-config.patch, recipes-kernel/linux/linux-imx_6.1.bb
There are three commits related to the Linux kernel configuration in the imx platform. This changes
remove the KERNEL_LZO configuration Linux kernel configuration and uses the KERNEL_GZIP, which is
the default. This is enough to remove the lzop-native dependency.
=> Remove the need of lzop-native from layer

conf/layer.conf
LAYERDEPENDS Lists the layers on which this recipe depends.
meta-oe is required by the linux-fscl recipe because it depends of lzop-native.
=> conf: set the list of required layers

recipes-security/swm/keyctl-caam_git.bb
This recipe comes from [meta-imx](https://github.com/nxp-imx/meta-imx/blob/kirkstone-5.15.71-2.2.0/meta-bsp/recipes-security/smw/keyctl-caam_git.bb).
keyctl-caam (the binary name is `caam-keyctl`) is a tool useful to implement use cases like encrypted storage using CAAM secure keys as described in the NXP Application note AN12714.
=> keyctl-caam: add keyctl-caam recipe from meta-imx

recipes-kernel/kernel-modules/kernel-module-imx-gpu-viv_6.4.11.p1.0+fslc.bb
Update to the version used in NXP Yocto branch langdale-6.1.1-1.0.0.
=> kernel-module-imx-gpu-viv: 6.4.3.p4.6+fslc -> 6.4.11.p1.0+fslc

recipes-graphics/imx-gpu-viv/imx-gpu-viv-6.inc
The OpenCL extensions for VX Intrinsics is limited.
=> imx-gpu-viv: Limit cl_viv_vx_ext.h to 8QuadMax and 8M Plus

recipes-devtools/uuu/uuu_git.bb
This apparently prevents the recipe from actually building for the most useful variants, native and nativesdk - it's really rare that one would actually want to run uuu itself _on_ an imx target.
Moreover, we have a test setup where we use Raspberry Pis for power cycling, exposing the serial console etc. from various boards, so we do want to build uuu for the BSPs we put on those RPis in order to automatically test bootstrapping of imx boards.
=> uuu: drop bogus COMPATIBLE_MACHINE

recipes-graphics/wayland/weston-init.bbappend
A regression was introduced by commit 47f0410be1:
[ weston-init: Rework weston.ini configuration ]
xwayland had been dropped from weston.ini for mainline BSPs before that commit, since it's not supported by mainline BSPs, but after that, it's added back again.
Introduce a xwayland PACKAGECONFIG to control that, drop it from weston.ini from mainline BSPs.
=> weston-init: disable xwayland for mainline BSPs

dynamic-layers/openembedded-layer/recipes-multimedia/mpv/mpv_%.bbappend, recipes-multimedia/gstreamer/gstreamer1.0-plugins-good/0001-v4l2-Include-gst-allocators-gstdmabuf.h-for-gst_is_d.patch, recipes-multimedia/gstreamer/gstreamer1.0-plugins-good_1.20.3.imx.bb, recipes-multimedia/gstreamer/gstreamer1.0-python_1.20.3.imx.bb
setuptools3-base FILES assignments have been simplified, therefore the internal libraries should be now packaged explicitly.
Fixes
ERROR: QA Issue: gstreamer1.0-python: Files/directories were installed but not shipped in any package:
/usr/lib/gstreamer-1.0/libgstpython.so
=> Fixes with latest oe-core master changes and clang16

recipes-graphics/imx-gpu-viv/imx-gpu-viv-6.inc
The OpenCL implementation includes an extension for VX Intrinsics. To use it, an app requires the CL compiler and /usr/include/CL/cl_viv_vx_ext.h, so add the appropriate runtime dependency to libopenvx-imx.
=> imx-gpu-viv: Add runtime dependency for OpenCL VX Intrinsic Extension

recipes-dpaa/fmlib/fmlib_git.bb
When building package fmlib based on Yocto version mickledore, there is below warning reported:
WARNING: fmlib-git-r1 do_package_qa: QA Issue: File /usr/lib64/libfm-arm.a in package fmlib-staticdev contains reference to TMPDIR [buildpaths] Because the KERNEL_SRC is passed into Makefile, and not mapped to a target path like the source of this package. To void this warning, it also needs to add the path map in CFLAGS  for kernel source.
=> meta-freescale: fmlib: map kernel source path to target path

recipes-bsp/imx-atf/imx-atf_2.6.bb, recipes-bsp/imx-sc-firmware/imx-sc-firmware_1.15.0.bb, recipes-graphics/imx-gpu-viv/imx-gpu-viv-6.inc
This component uses BFD linker specific options which may not be available when default ld is not GNU BFD LD
Fixes
| aarch64-yoe-linux-ld: error: unknown argument '--fix-cortex-a53-835769'
=> imx-atf: Explicitly demand BFD linker

recipes-extended/tsntool/tsntool/0001-tsntool-remove-redundant-parameters-from-BIN_LDFLAGS.patch, recipes-extended/tsntool/tsntool_git.bb
The recipe file has pass the same parameter(-Wl,-rpath-link,<lib path>) to Makefile, so remove redundant parameters from BIN_LDFLAGS.
=> meta-freescale: tsntool: remove redundant parameters from BIN_LDFLAGS

recipes-bsp/isp-imx/basler-camera_4.2.2.21.0.bb
The binary blob providing basler-camera files now (4.2.2.21) contains configuration files for the Omnivion OS08A20 as used on NXP's camera module [1].
Those files have been and still are provided by isp-imx. The content is identical.
Delete them to prevent the following error during do_rootfs if the basler-camera package is installed into a image:
| * check_data_file_clashes: Package libdaa3840-30mc1 wants to install file
|        .../rootfs/opt/imx8-isp/bin/dewarp_config/sensor_dwe_os08a20_1080P_config.json
|        But that file is already provided by package  * isp-imx
| * check_data_file_clashes: Package libdaa3840-30mc1 wants to install file
|        .../rootfs/opt/imx8-isp/bin/dewarp_config/sensor_dwe_os08a20_4K_config.json
|        But that file is already provided by package  * …
=> basler-camera: delete files also provided by isp-imx

classes/fsl-kernel-localversion.bbclass
CONFIG_LOCALVERSION is a string setting. It needs to go between quotes in the .config file.
$ grep CONFIG_LOCALVERSION= .config
CONFIG_LOCALVERSION="-dey"
=> fsl-kernel-localversion: fix regression setting LOCALVERSION

conf/machine/include/imx-base.inc
The NXP BSP overrides imxdrm and imxpxp were accidentally included in MACHINEOVERRIDES_EXTENDER:mx93:use-mainline-bsp.
=> imx-base.inc: Remove imxdrm and imxpxp overrides from mx93 mainline-bsp

recipes-graphics/imx-gpu-viv/imx-gpu-viv/imx_icd.json
Vulkan loader reads driver path from imx_icd.json so update it to use a driver version installed on target.
=> imx-gpu-viv: Fix i.MX GPU driver version for Vulkan loader

recipes-graphics/imx-gpu-viv/imx-gpu-viv-6.inc
When the recipe include file imx-gpu-viv-6.inc is used from another layer, the included SRC_URI file imx_icd.json is not found.
=> imx-gpu-viv: Simplify using imx-gpu-viv-6.inc from another layer

recipes-multimedia/libimxvpuapi/libimxvpuapi2_2.2.2.bb
This fixes the compilation issue on imx8mp, where "hanto" files are missing.
=> Update libimxvpuapi2_2.2.2.bb: "hanto" missing files fix (imx8mp)

recipes-bsp/alsa-state/alsa-state.bbappend
Current implement can only apply the setting under folder imx-generic-bsp. Add paths for the NXP and mainline specific setting.
=> alsa-state: Add FILESEXTREAPATHS for NXP specific and Mainline BSP

conf/machine/include/imx-base.inc, recipes-graphics/wayland/wayland/0001-build-Fix-strndup-detection-on-MinGW.patch, recipes-graphics/wayland/wayland/run-ptest, recipes-graphics/wayland/wayland_1.22.0.imx.bb
Current xwayland 23.1.1 release is not compatible with the wayland version available in kirkstone (1.20.0).
Make a local copy of the 1.22.0 recipe from oe-core master b73784851 but for imx, with default preference set as -1, following how xwayland was also imported from oe-core.
This change is mostly relevant for uses wanting to use meta-freescale master with oe-core kirkstone. In case it is not desired to fork yet another recipe due kirkstone compatibility I can have a similar change on my distro layer instead (but opening the pull request anyway).
=> wayland: make local copy of the 1.22.0 recipe

conf/machine/include/imx-base.inc
When using wayland and an i.MX SoC the recipes ought to be in sync. This
fixes a build error in nativesdk-wayland when running in mickledore:
,----
| ../wayland-1.21.0/src/meson.build:81:1: ERROR: Dependency lookup for
|   wayland-scanner with method 'pkgconfig' failed: Invalid version, need
|   'wayland-scanner' ['1.21.0'] found '1.22.0'.
`----
Fixes: 60510fbb ("wayland: make local copy of the 1.22.0 recipe")
=> wayland: sync wayland, wayland-native and nativesdk-wayland versions

recipes-downgrade/vulkan/vulkan-loader_1.2.182.0.bb
WARNING: vulkan-headers-1.2.182.0-r0 do_fetch: Failed to fetch URL git://github.com/KhronosGroup/Vulkan-Headers.git;branch=master;protocol=https, attempting MIRRORS if available
WARNING: vulkan-loader-1.2.182.0-r0 do_fetch: Failed to fetch URL git://github.com/KhronosGroup/Vulkan-Loader.git;protocol=https;branch=master, attempting MIRRORS if available
WARNING: libwebp-1.2.4-r0 do_fetch: Failed to fetch URL http://downloads.webmproject.org/releases/webp/libwebp-1.2.4.tar.gz, attempting MIRRORS if available
ERROR: vulkan-loader-1.2.182.0-r0 do_fetch: Fetcher failure: Unable to find revision 1896143df69d439b0933c1bb485f5a4587bdf2dc in branch master even from upstream
=> vulkan-loader: Fix renamed master branch in source repository

classes/mfgtool-initramfs-image.bbclass
INITRAMFS_IMAGE_NAME stay as before but it assumes that all images used as initramfs will set IMAGE_NAME_SUFFIX to empty.
https://git.yoctoproject.org/poky/commit/?id=6f6c79029bc2020907295858449c725952d560a1
=> mfgtool-initramfs-image: IMAGE_NAME_SUFFIX should by empty for initramfs

recipes-sato/webkit/webkitgtk_%.bbappend
opengl-or-es can be kept now
This ends up configure errors with newly updated 2.40 webkit in core Fixes issues like
| CMake Error at Source/cmake/WebKitMacros.cmake:154 (target_link_libraries):
|   Target "WebCore" links to:
|
|     WPE::libwpe
|
|   but the target was not found.  Possible reasons include:
|
|     * There is a typo in the target name.
|     * A find_package call is missing for an IMPORTED target.
|     * An ALIAS target is missing.
=> webkitgtk: Remove x11 from packageconfigs

conf/machine/imx6qdlsabreauto.conf, conf/machine/imx6qdlsabresd.conf, conf/machine/imx6slevk.conf, conf/machine/imx6sllevk.conf, conf/machine/imx6sxsabreauto.conf, conf/machine/imx6sxsabresd.conf, conf/machine/imx6ulevk.conf, conf/machine/imx6ullevk.conf, conf/machine/imx7dsabresd.conf, conf/machine/imx7ulpevk.conf, conf/machine/imx8mq-evk.conf, conf/machine/imx8qm-mek.conf, conf/machine/include/imx8mm-evk.inc, conf/machine/include/imx8mn-evk.inc, conf/machine/include/imx8mp-evk.inc
UBOOT_CONFIG[mfgtool] is no longer used since the following:
88399694 linux-*-mfgtool, u-boot-*-mfgtool: Remove specific recipes
=> imx*.conf: Drop unused UBOOT_CONFIG[mfgtool]

conf/machine/include/imx-base.inc, recipes-kernel/kernel-modules/kernel-module-nxp-wlan_git.bb, recipes-kernel/kernel-modules/kernel-module-nxp89xx_git.bb
The NXP W-Fi driver is the all-in-one driver to support all of NXP Wi-Fi modules.
Rename the recipe name to provide the right information.
=> Upgrade NXP Wi-Fi driver to L6.1.22-2.0.0 and rename it to kernel-module-nxp-wlan

recipes-kernel/linux/linux-fslc_6.1.bb
Tested building with:
- **aarch64**: defconfig
- **arm**: mxs_defconfig imx_v4_v5_defconfig imx_v6_v7_defconfig
The kernel repository has been upgraded up to v6.1.38 from a stable release.
Following commits are added on top of stable tree:
- 085682f3fc7e ("kbuild: filter only valid dtb files to construct complex dtb")
=> linux-fslc: update to v6.1.38

conf/machine/include/imx-base.inc, recipes-kernel/linux/linux-fslc_6.1.bb
@otavio @thochstein I'm not sure whether we keep these settings for users that use meta-freescale in their own distros with mx27 machines.
There are no machines on this platform supported by meta-freescale anymore.
Remove the rest of the mx27 platform settings.
=> mx27: remove platform settings

recipes-graphics/wayland/weston-init.bbappend
The logic adding use-g2d to weston.ini adds a commented version for builds without G2D support.
=> weston-init: Don't add use-g2d where not supported

recipes-kernel/kernel-modules/kernel-module-imx-gpu-viv_6.4.11.p1.2+fslc.bb
Update to the version used in NXP Yocto branch mickledore-6.1.22-2.0.0.
=> kernel-module-imx-gpu-viv: 6.4.11.p1.0+fslc -> 6.4.11.p1.2+fslc

conf/machine/imx93-14x14-lpddr4x-evk.conf
It is based on 6.1.22_2.0.0 NXP BSP release.
=> imx93-14x14-lpddr4x-evk: Add i.MX 93 14x14 EVK machine

conf/machine/imx6ullevk.conf, conf/machine/imx6ulz-14x14-evk.conf, recipes-bsp/imx-lib/imx-lib_git.bb, recipes-bsp/imx-mkimage/files/0001-iMX8M-soc.mak-use-native-mkimage-from-sysroot.patch, recipes-bsp/imx-mkimage/imx-mkimage_git.inc, recipes-bsp/imx-test/imx-test_git.bb, recipes-bsp/u-boot/u-boot-imx-common_2023.04.inc, recipes-bsp/u-boot/u-boot-imx_2023.04.bb, recipes-kernel/linux/linux-fslc-imx_6.1.bb, recipes-kernel/linux/linux-imx-headers_6.1.bb, recipes-kernel/linux/linux-imx_6.1.bb
For https://github.com/Freescale/meta-freescale/issues/1588:
- Upgrade Linux kernel and U-Boot (i.MX variants)
Tested building, flashing, and booting on:
- imx6ullevk
- imx8mm-lpddr4-evk
- imx7ulpevk
=> Update imx[-fslc] linux kernel, u-boot and related recipes to 6.1.22-2.0.0

recipes-bsp/firmware-imx/firmware-nxp-wifi_1.0.bb
Also install the standalone NXP firmware for wlan and bt, available as part of lf-6.1.22_2.0.0.
=> firmware-nxp-wifi: install NXP wlan and bt only firmware blobs

conf/machine/include/imx93-evk.inc
imx-base.inc uses nxpiw612-sdio instead of iw612 when adding the relevant firmware packages.
=> imx93-evk: use correct name for the iw612 machine feature

recipes-kernel/linux/linux-imx/drivers-mxc-gpu-viv-Fix-enum-int-mismatch-warning.patch, recipes-kernel/linux/linux-imx_6.1.bb
Fix the warning (treated as error):
ignal' due to enum/integer mismatch; have 'gceSTATUS(struct _gckOS *, void *)' {aka 'enum _gceSTATUS(struct _gckOS *, void *)'} [-Werror=enum-int-mismatch] |  5675 | _QuerySignal(IN gckOS Os, IN gctSIGNAL Signal)
|       | ^~~~~~~~~~~~
| In file included from /(...)tmp/work-shared/imx93-11x11-lpddr4x-evk/kernel-source/drivers/mxc/gpu-viv/hal/os/linux/kernel/gc_hal_kernel_os.c:56:
| /(...)/buildw/tmp/work-shared/imx93-11x11-lpddr4x-evk/kernel-source/drivers/mxc/gpu-viv/hal/os/linux/kernel/gc_hal_kernel_linux.h:341:1: note: previous declaration of '_QuerySignal' with type 'gctBOOL(struct _gckOS *, void *)' {aka 'int(struct _gckOS *, void *)'}
|   341 | _QuerySignal(IN gckOS Os, IN gctSIGNAL Signal);
|       | ^~~~~~~~~~~~
| cc1: all warnings being treated …
=> linux-imx: Add patch to fix build issue

recipes-bsp/imx-atf/imx-atf_2.8.bb
Update to the 2.8 version aligned with NXP BSP release L6.1.22-2.0.0.
- 99195a23d MA-21286 imx8m: habv4: support dram dynamic mapping
- 57e74c226 MA-21277 imx93: fix boot failure on opteed
- 8c5bfc946 MA-21257 imx93: enable trusty support
- 5ce0b6827 MA-21254 remove static declaration for rank_setting_update()
- 8ab375a81 LF-9014 imx8ulp: pd: Fix EPDC update issue
- 70db244d4 MA-21229 android: imx8mq: fix build break
- 4dfe57384 MA-21228 trusty: sync spmd ffa handler function
- a78eb7c37 LF-8090 imx93: TRDC: Fix wrong fuse bits for USB1 and eQOS disable
- d25473f6f LF-8893 feat(imx8ulp): add some delay before cmc1 access
- 64de3dc30 LF-8890 feat(imx8ulp): update the upower pmic_cfg setting
- 856a80e65 LF-8838 feat(imx93): skip system level power config when m33 active
- …
=> imx-atf: Update 6.1.1-1.0.0 to 6.1.22-2.0.0

recipes-extended/jailhouse/jailhouse_git.bb
Switch a branch to lf-6.1.22_2.0.0 to align the recipe with NXP BSP LF6.1.22_2.0.0, and update relevant parts of the recipe.
=> jailhouse: Update to lf-6.1.22_2.0.0

recipes-multimedia/alsa/imx-alsa-plugins_git.bb, recipes-multimedia/imx-codec/imx-codec_4.8.0.bb, recipes-multimedia/imx-dsp/imx-dsp-codec-ext_2.0.5.bb, recipes-multimedia/imx-dsp/imx-dsp_2.0.5.bb, recipes-multimedia/imx-parser/imx-parser_4.8.0.bb, recipes-multimedia/imx-sw-pdm/imx-sw-pdm_1.0.3.bb, recipes-multimedia/imx-vpuwrap/imx-vpuwrap_git.bb
The updated recipes are:
- imx-codec/imx-parser: Upgrade to 4.8.0.
- imx-dsp/imx-dsp-codec-ext: Upgrade to 2.0.5.
- imx-sw-pdm: Upgrade to 1.0.3.
- imx-vpuwrap/imx-alsa-plugins: Upgrade to new revision.
=> recipe-multimedia: Upgrade to 6.1.22-2.0.0 release

recipes-downgrade/vulkan/vulkan-loader_1.2.182.0.imx.bb
as long as vulkan is part of distro features this should work. this also ensures that build works when using eglfs with opengl instead
=> vulkan-loader: Do not limit to x11 or wayland

recipes-bsp/firmware-imx/firmware-nxp-wifi_1.0.bb
Drop:
- uartuart8987_bt.bin
- uartuart8997_bt_v4.bin
- uartuart9098_bt_v1.bin
- uartiw416_bt_v0.bin
- uartspi_n61x_v1.bin.se
Fixes: #1639
=> firmware-nxp-wifi: Drop UART firmware now in linux-firmware

conf/machine/include/imx-base.inc, recipes-bsp/firmware-imx/firmware-nxp-wifi_1.0.bb
Revised fix for #1639. Depends on OE-Core update to `linux-firmware`. That is currently pending a final internal review before I submit the change to OE-Core.
=> NXP WiFi firmware

recipes-devtools/uuu/uuu_git.bb
Since 1.4.243, uuu includes zstd support. Currently, this dependency is not specified, and thus if nativesdk-uuu is built, cmake will err during do_configure reporting that the package is missing.
To fix this, add zstd to DEPENDS.
=> uuu: Add missing zstd dependency

recipes-kernel/kernel-modules/kernel-module-ar_git.bb, recipes-kernel/kernel-modules/kernel-module-ls-debug_git.bb, recipes-kernel/kernel-modules/kernel-module-scatter-gather_git.bb, recipes-kernel/kernel-modules/kernel-module-uio-seville_0.1.bb
Disclaimer: As I don't use any layerscape based machine I didn't build test at all.
Due to COMPATIBLE_MACHINE the bitbake parser will not even parse the recipe.
These (together with one recipe in meta-freescale-distro) seem to be the last instances of a github fetch using the git protocol in the layers I use.
=> recipes: Update github.com urls to use https

recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_1.22.%.bbappend, recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_1.22.0.imx.bb
* Extract PACKAGECONFIG_GL settings into a common .bappend file that is used for both the imx GStreamer fork and upstream GStreamer.
* Backport fix for being able to use the viv-fb display support in upstream GStreamer (relevant for i.MX6).
* Backport fix for decoupling Vivante direct textures from the viv-fb display support, since direct textures can also be used with other systems like Wayland for example. This obviates the need to enable the viv-fb package just to get "fast paths" in GStreamer pipelines; if direct textures are supported, they are enabled automatically.
=> gstreamer1.0-plugins-base: Fix GL packageconfig and Vivante GPU details

classes/imx-boot-container.bbclass, recipes-bsp/imx-mkimage/imx-boot_1.0.bb, recipes-bsp/u-boot/u-boot-imx_2023.04.bb
This is a rebase for https://github.com/Freescale/meta-freescale/pull/1439
It creates the `imx-boot` binary only for the first `UBOOT_CONFIG`, so UUU class is satisfied.
It also supports imx93 and imx8ulp (missing in the first PR)
----
**From the original PR:**
A long time ago I implemented a workaround to support multiple u-boot builds for the same machine.
This saved our project several hours every day on builds (16 different U-boots) because the image was common to all machines, only U-boot had a few changes per machine configuration. All wic-images are generated at once, separate tasks are not needed.
It still supports the original way of configuration, but for multiple u-boot I added flags for the same env vars.
For example, original machine configs for boards M1 and M2 :
``` …
```
=> Multiple uboot

classes/imx-boot-container.bbclass, recipes-bsp/imx-mkimage/imx-boot_1.0.bb, recipes-bsp/u-boot/u-boot-imx_2022.04.bb
Backport PR https://github.com/Freescale/meta-freescale/pull/1657, https://github.com/Freescale/meta-freescale/pull/1642 and https://github.com/Freescale/meta-freescale/pull/1652.
I left out U-boot recipe part. Do you think it is needed for kirkstone?
Thanks.
=> Backport 1642, 1657 and 1652 to kirkstone - multiple boot binaries

recipes-bsp/isp-imx/isp-imx/0001-cpp-netlib-parsers.ipp-add-missing-include.patch, recipes-bsp/isp-imx/isp-imx_4.2.2.22.0.bb
Add missing include as boost no longer indirectly includes it.
(https://github.com/boostorg/spirit/pull/758/commits/a1086d992b6a904fb022320f7ceeb784f22be2d1)
=> isp-imx: fix compile with boost 1.83.0

recipes-devtools/uuu/uuu-bin_1.4.243.bb, recipes-devtools/uuu/uuu_git.bb
Due to the transition of github.com/NXPMicro/mfgtools to github.com/nxp-imx/mfgtools, this commit updates the repository links to ensure future fetches will not break.
The recipe still works because NXPMicro repository became an alias to nxp-imx.
=> uuu: Update nxp repository links

recipes-kernel/linux/linux-fslc_6.1.bb
Kernel repository has been upgraded up to v6.1.57 from stable release.
Build test: imx8mm-lpddr4-evk only
=> linux-fslc: update to v6.1.57

recipes-bsp/u-boot/u-boot-imx-common_2023.04.inc, recipes-bsp/u-boot/u-boot-imx_2023.04.bb
Tested building all imx* machines with `IMX_DEFAULT_BOOTLOADER="u-boot-imx" bitbake u-boot`
For `U-Boot (i.MX variants)` in  https://github.com/Freescale/meta-freescale/issues/1655
=> Update u-boot-imx to lf-6.1.36-2.1.0

recipes-bsp/imx-sc-firmware/imx-sc-firmware_1.15.0.bb
Its not supported by gcc < 13 and this package uses a prebuilt toolchain based on gcc 8
Fixes
| arm-none-eabi-gcc: error: unrecognized command line option '-fcanon-prefix-map'; did you mean '-fmacro-prefix-map='?
=> imx-sc-firmware: Remove -fcanon-prefix-map

recipes-kernel/kernel-modules/kernel-module-nxp-wlan/0001-moal_cfg80211-remove-dropped-REGULATORY_IGNORE_STALE.patch, recipes-kernel/kernel-modules/kernel-module-nxp-wlan_git.bb
Apply patch to fix build for kernels 6.1.39 and greater.
Fixes: #1676
=> kernel-module-nxp-wlan: Fix REGULATORY_IGNORE_STALE_KICKOFF build break

conf/machine/imx23evk.conf, conf/machine/imx28evk.conf, conf/machine/imx51evk.conf, conf/machine/imx53qsb.conf
The 32-bit ARM device trees in the Linux kernel were reorganized in a manner similar to how the 64-bit ARM device trees have always been organized: by placing them in vendor+family subdirectories. Therefore update the KERNEL_DEVICETREE definitions to match.
=> ARM 32-bit device-tree reorganization

recipes-kernel/linux/linux-fslc-imx_6.1.bb, recipes-kernel/linux/linux-fslc-lts_6.1.bb, recipes-kernel/linux/linux-imx.inc, recipes-kernel/linux/linux-imx_6.1.bb
Newer kernels have moved the dtbs to a vendor sub-folder, including the ones for i.MX 32-bit, which now reside in nxp/imx. In order to maintain one KERNEL_DEVICETREE for both new and old kernels, provide logic that can be enabled in older kernels to strip the new sub-folder.
Fixes: 0d838c68
=> linux: Add compatibility logic for 32-bit dtb move

recipes-fsl/mcore-demos/imx-mcore-demos.inc
When using multilib configuration there is a build break at packaging step
=>  imx-mcore-demos: Fix install for multilib  Replace  `base_libdir` with `nonarch_base_libdir`

classes/image_types_fsl.bbclass
This is no longer required since its already merged into IMAGE_NAME and IMAGE_LINK_NAME via [1] in OE-Core. Infact it causes problems now if we add .rootfs explicitly, this created non-existent filenames and resulting images are wrong.
[1] https://git.openembedded.org/openembedded-core/commit/meta/classes-recipe/image-artifact-names.bbclass?id=26d97acc71379ab6702fa54a23b6542a3f51779c
=> image_types_fsl.bbclass: Drop use of IMAGE_NAME_SUFFIX

wic/imx-uboot-mxs-bootpart.wks.in
${IMAGE_LINK_NAME} already contains "rootfs" at the end, therefore it does not need to be added explicitly. Otherwise the wic creation fails with:
wic.filemap.Error: cannot open image file '.../build/tmp-glibc/deploy/images/imx233-olinuxino-maxi/core-image-minimal-imx233-olinuxino-maxi.rootfs.rootfs.uboot-mxsboot-sdcard'
=> imx-uboot-mxs-bootpart.wks.in: drop extra 'rootfs'

classes/fsl-kernel-localversion.bbclass, classes/fsl-u-boot-localversion.bbclass
The localversion string built into the kernel and u-boot should be deterministic. With OpenEmbedded it is common practice to apply patches to the sources. The commit id of HEAD will differ each time the patching step is rerun. With the previous implementation of the fsl-{kernel,u- boot}-localversion classes this produced non-deterministic commit ids to be used. This is undesireable, because the commit-id read from the version string during runtime is not present in the sources. It also caused problems when building out-of-tree kernel-modules if the kernel itself was taken from sstate cache but the kernel-module needed to be rebuild and retriggered the kernels do_patch task (see #961).
Rework to produce a deterministic string that will use the commit id given as SRCREV and count the number …
=> classes: make localversion classes deterministic

recipes-security/optee-imx/optee-client_3.21.0.imx.bb, recipes-security/optee-imx/optee-os-fslc.inc, recipes-security/optee-imx/optee-os_3.21.0.imx.bb, recipes-security/optee-imx/optee-test_3.21.0.imx.bb
It needs https://github.com/Freescale/meta-freescale/pull/1702 to be merged.
It closes "Upgrade OP-TEE" task of https://github.com/Freescale/meta-freescale/issues/1655
=> Upgrade OP-TEE to LF3.1.66-2.1.0 NXP BSP

conf/machine/imx8mp-lpddr4-evk.conf
This PR removes a device-tree from `im8mp-lpddr4-evk` machine which doesn't exist on `linux-fslc-imx` (which is the default kernel on `imx8mp-lpddr4-evk` board)
Otherwise `linux-fslc-imx` recipe failed to build for this target.
Fixes #1704
=> conf/machine: remove unsupported dtb for imx8mp-lpddr4-evk machine

recipes-kernel/linux/linux-fslc-imx_6.1.bb
Merge changes from the tag lf-6.1.36-2.1.0 into 6.1-2.1.x-imx.
Tested building:
- imx8mm-lpddr4-evk
- imx8mq-lpddr4-wevk
- imx8mp-lpddr4-evk
- 688f1f419b08a Merge branch 'lf-6.1.36_2.1.0' into 6.1-2.1.x-imx-6.1.36-2.1.0
- d9e9cb8ce9bc7 hx280enc_vc8000e: fix misplaced #endif
- 04b05c5527e9a LF-9952 clocksource: imx-tpm: Wait for CnV write to take effect
- 5a6b16bf87543 LF-9849-3: dts: arm64: imx8dxl: add PHY reset gpio and drop refclk-in
- a11213e8e518d LF-9849-2: dts: arm64: imx8qxp: add PHY reset gpio
- b675c820b30b2 LF-9849-1: dts: arm64: imx8qm: correct clock setting
- 8c65de4996afd fec_uio: support deferred probing
- 9e1862c64d629 LF-9794: spi: nxp-fspi: reset the flashx control1 registers
- 2655f9cbd0d56 net: sdk_fman: cleanup resources if HashTableSet fails
- …
=> linux-fslc-imx: Merge NXP changes from lf-6.1.36-2.1.0

recipes-devtools/uuu/files/0001-libuuu-usbhotplug.cpp-don-t-limit-retry-logic-to-win.patch, recipes-devtools/uuu/uuu_git.bb
Bump the uuu revision to the latest tag.
While testing, I found that the the udev rules didn't always kick in soon enough, so a small patch is needed to also have some retry logic on linux.
=> uuu: bump to 1.5.141

conf/machine/imx93-11x11-lpddr4x-evk.conf, conf/machine/imx93-14x14-lpddr4x-evk.conf, conf/machine/imx93-9x9-lpddr4-qsb.conf, conf/machine/include/imx93-evk.inc
The three machines require imx93-evk.inc, and the mx93 override is common to all of them, so it can be moved to imx93-evk.inc to avoid repetition.
=> imx93: rearrange repeated overrides

recipes-bsp/imx-mkimage/imx-mkimage_git.inc
This closes "imx-mkimage" of https://github.com/Freescale/meta-freescale/issues/1715
- c436545 LF-10397 imx8: Fix SCU container file offset issue
- 5c97f59 imx9: Fix flash_singleboot_spinand broken
- c684071 iMX9: Add signature DTS file
- e019f61 imx9: Add System ready relevant targets
- 5c58565 Support MSEL option for MX95 SM.
- d683e41 Add FW header support
- 703bc3c Update LPDDR5 FW to v202306
- cc6c3a4 imx95: Clean up targets in soc.mak and update Readme.imx95
- 3686be1 Add SM target with OEI+SM+M7(TCM)+AP.
- e8d6d79 Update SM targets.  Add SM target with M7 image in DDR.
- 2ae36d5 Add SM+M7 target for i.MX9.
- 3b13c36 Replace the OEI image with the prebuilt one
- b41f521 Add SM only target for i.MX9.
- 0eaf132 Introduce LPDDR_FW_PREFIX parameter
- 3b69364 add Readme …
=> imx-mkimage: Update for NXP release 6.1.55-2.2.0

recipes-bsp/u-boot/u-boot-imx-common_2023.04.inc
Tested building for imx93-14x14-lpddr4x-evk, imx8ulp-lpddr4-evk: OK
This partially closes the task "U-Boot (i.MX variants)" of https://github.com/Freescale/meta-freescale/issues/1715
Update the u-boot-imx to the tag lf-6.1.55-2.2.0, that is used in the NXP BSP LF6.1.55_2.2.0.
- 49b102d9888 LFU-611 arm: dts: imx93: update anatop node
- 0fdbf5df153 efi_loader: support all uclasses in device path
- b64f06fee79 efi_loader: Fix warnings for unaligned accesses
- d23550de2fe efi_loader: Fix flexible array member definitions
- d17db0235cc LF-10422-2 dts: imx93: Fix date reset fail
- f78da92266a LF-10422-1 rtc: Fix date reset fail
- ee041d63eae LFU-600 imx8mp_evk: Change back kernel DTB to old EVK board
- 26768c4e470 MA-21741-1 Correct some uboot attributes which about hardware
- …
=> u-boot-imx: Update to lf-6.1.55-2.2.0

recipes-graphics/cairo/cairo_%.bbappend
These packageconfigs are gone with migration to meson in 1.18+
Fixes
ERROR: cairo-1.18.0-r0 do_configure: QA Issue: cairo: invalid PACKAGECONFIG: egl [invalid-packageconfig] ERROR: cairo-1.18.0-r0 do_configure: QA Issue: cairo: invalid PACKAGECONFIG: glesv2 [invalid-packageconfig]
=> cairo: Drop the removed packageconfigs

conf/machine/include/imx93-evk.inc
After [1] the MACHINEOVERRIDES for imx93 based machines became:
MACHINEOVERRIDES="imx-generic-bsp:imx-nxp-bsp:imxdrm:imxpxp:mx9-generic-bsp:
mx9-nxp-bsp:mx93-generic-bsp:mx93-nxp-bsp:aarch64:armv8-2a:
use-nxp-bsp:imx93-11x11-lpddr4x-evk"
which is different from what we had before. It impacts how some recipes are choosen, for example u-boot.
After this patch, the MACHINEOVERRIDES goes back to what we had before. Just like the following:
MACHINEOVERRIDES="aarch64:armv8-2a:use-nxp-bsp:imx-generic-bsp:imx-nxp-bsp:
imxdrm:imxpxp:mx9-generic-bsp:mx9-nxp-bsp:mx93-generic-bsp:
mx93-nxp-bsp:imx93-11x11-lpddr4x-evk"
[1] https://github.com/Freescale/meta-freescale/pull/1714
=> imx93-evk.inc: Change MACHINEOVERRIDES order

recipes-kernel/linux/linux-imx_6.1.bb
Update the linux-imx kernel to be aligned with the NXP BSP LF6.1.55_2.2.0.
=> linux-imx: Update lf-6.1.36_2.1.0 to lf-6.1.55-2.2.0

recipes-kernel/linux/linux-fslc-imx_6.1.bb
Merge changes from the tag lf-6.1.55-2.2.0 into 6.1-2.2.x-imx. Merge stable tags until v6.1.70
- 32a344619c75 Merge pull request #650 from angolini/6.1-2.2.x-imx_bump_to_6.1.70
- ae9972d1ca6b Merge tag 'v6.1.70' into 6.1-2.2.x-imx
- 4950fde33a86 Merge tag 'v6.1.69' into 6.1-2.2.x-imx
- 77a660738af5 Revert "net: stmmac: fix FPE events losing"
...
=> linux-fslc-imx: Merge NXP changes from lf-6.1.55-2.2.0

recipes-kernel/linux/linux-fslc-lts_6.1.bb
Kernel repository has been upgraded up to v6.1.72 from stable korg.
=> linux-fslc-lts: update to v6.1.72

recipes-graphics/waffle/waffle/0001-meson-Add-missing-wayland-dependency-on-EGL.patch
In yocto release kirkstone, waffle package is upgraded from 1.7.0 to 1.7.2, and there is below error reported when applying patch: Applying patch 0001-meson-Add-missing-wayland-dependency-on-EGL.patch patching file meson.build
Hunk #1 succeeded at 65 (offset 2 lines).
Hunk #2 succeeded at 107 (offset 2 lines).
Hunk #3 succeeded at 126 with fuzz 1 (offset 4 lines). So, adjust the patch context to compatible with version 1.7.2
=> meta-freescale: update waffle patch to compatible with version 1.7.2

recipes-bsp/isp-imx/basler-camera_4.2.2.24.0.bb, recipes-bsp/isp-imx/isp-imx_4.2.2.24.0.bb
Should have built to a rootfs when updating isp-imx.
Related-to: https://github.com/Freescale/meta-freescale/issues/1715 https://github.com/Freescale/meta-freescale/pull/1734
=> Update basler-camera to 4.2.2.24.0 used with lf-6.1.55-2.2.0 and fix isp-imx to work alongside basler-camera

recipes-multimedia/gstreamer/gstreamer1.0/0006-systemclock-Use-futex_time64-syscall-if-available-32.patch, recipes-multimedia/gstreamer/gstreamer1.0_1.20.3.imx.bb
=> gstreamer1.0: use futex_time64 syscall if available (32-bit systems) #1725

recipes-extended/jailhouse/jailhouse-imx_git.bb
Unblock https://github.com/Freescale/meta-freescale/pull/1709
=> Jailhouse-imx: cleanup and fix bitbake tasks overrides 

recipes-fsl/mcore-demos/README, recipes-fsl/mcore-demos/imx-m33-demos_2.14.2.bb
This updates only adds a new version of imx-m33-demos only for imx93. 
This also updates the info on README to the current status.
=> mcode-demos: Update to LF6.1.55_2.2.0

recipes-bsp/u-boot/u-boot-qoriq_2021.04.bb
Building this recipe on an Unbuntu 20.04 host results in the following erro:
Traceback (most recent call last):
File "u-boot-qoriq/2021.04+fslgit-r0/git/tools/binman/binman", line 39, in <module>
from binman import control
File "u-boot-qoriq/2021.04+fslgit-r0/git/tools/binman/../binman/control.py", line 11, in <module>
import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
With the added dependency the build completes.
=> u-boot-qoriq: add 'python3-setuptools-native' to depends

recipes-extended/jailhouse/files/arm-arm64-Makefile-Remove-march-option-from-Makefile.patch, recipes-extended/jailhouse/jailhouse-imx_git.bb
It changes the Makefile, so the recipe is the only one controlling the build arguments.
It is related to [1]
[1] https://git.yoctoproject.org/poky/commit/?id=04eac1f2b67eac5f892a9e0f8fcfe54849923af5
---
Now it builds
=> jailhouse-imx: Avoid the build error when using -mcpu and -march

recipes-graphics/imx-gpu-viv/imx-gpu-viv-6.inc
For each of the EGL rendering APIs, the EGL implementation does a dlopen for the unversioned library link to the rendering API implementation. So, a runtime dependency is needed for the -dev package of each such rendering API implementation.
Fixes: #1744
=> imx-gpu-viv: Fix EGL dependencies

conf/machine/include/imx-base.inc, recipes-multimedia/alsa/imx-alsa-plugins_git.bb, recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_1.22.5.imx.bb, recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_1.22.5.imx.bb, recipes-multimedia/gstreamer/gstreamer1.0-plugins-good_1.22.5.imx.bb, recipes-multimedia/gstreamer/gstreamer1.0_1.22.5.imx.bb, recipes-multimedia/gstreamer/imx-gst1.0-plugin_git.bb, recipes-multimedia/imx-codec/imx-codec_4.8.2.bb, recipes-multimedia/imx-dsp/imx-dsp-codec-ext_2.1.6.bb, recipes-multimedia/imx-dsp/imx-dsp_2.1.6.bb, recipes-multimedia/imx-opencl-converter/imx-opencl-converter_0.1.bb, recipes-multimedia/imx-parser/imx-parser_4.8.2.bb, recipes-multimedia/imx-vpuwrap/imx-vpuwrap_git.bb
Upgraded:
- gstreamer1.0-plugins-bad:     1.22.0 -> 1.22.5
- gstreamer1.0-plugins-base:    1.22.0 -> 1.22.5
- gstreamer1.0-plugins-good:    1.22.0 -> 1.22.5
- gstreamer1.0:                 1.22.0 -> 1.22.5
- imx-codec:                    4.8.1 -> 4.8.2
- imx-dsp:                      2.1.5 -> 2.1.6
- imx-dsp-codec-ext:            2.1.5 -> 2.1.6
- imx-parser:                             4.8.1 -> 4.8.2
Updated:
- imx-alsa-plugins_git.bb
- imx-gst1.0-plugin_git.bb
- imx-vpuwrap_git.bb
New feature:
- imx-opencl-converter_0.1.bb
=> recipes-multimedia: Update for NXP release 6.1.55-2.2.0

recipes-devtools/uuu/uuu-bin_1.5.165.bb
Bump to the latest pre-release tag, matching the uuu recipe (using the 1.5.x series)
=> uuu-bin: upgrade 1.4.243 -> 1.5.165

conf/machine/include/imx-base.inc, recipes-security/optee-imx/optee-client_4.0.0.imx.bb, recipes-security/optee-imx/optee-os/0001-core-Define-section-attributes-for-clang.patch, recipes-security/optee-imx/optee-os/0002-optee-enable-clang-support.patch, recipes-security/optee-imx/optee-os/0003-arm32-libutils-libutee-ta-add-.note.GNU-stack-sectio.patch, recipes-security/optee-imx/optee-os/0004-core-link-add-no-warn-rwx-segments.patch, recipes-security/optee-imx/optee-os_4.0.0.imx.bb, recipes-security/optee-imx/optee-test_4.0.0.imx.bb
This PR closes the "Upgrade OP-TEE" task of https://github.com/Freescale/meta-freescale/issues/1715
=> Upgrade OP-TEE to LF6.1.55-2.2.0 NXP BSP

recipes-devtools/uuu/uuu_git.bb
tinyxml2 build dependency has been introduced in:
https://github.com/nxp-imx/mfgtools/commit/e6c6874714f63cce96077921813a33f30463b914
=> uuu: add libtinyxml2 to the build dependencies

recipes-kernel/linux/linux-fslc-imx_5.15.bb
the 5.15-2.2.x-imx branch in linux-fslc is on v5.15.129, update the recipe to use this version
=> linux-fslc-imx: update to v5.15.129

conf/machine/include/imx-base.inc
bmaptool is now part of the Yocto Project and their recipe renamed it to bmaptool.
=> imx-base.inc: Rename bmap-tools to bmaptool

classes/uuu_bootloader_tag.bbclass, recipes-bsp/imx-mkimage/imx-boot_1.0.bb
Add UUU_BOOTLOADER_UNTAGGED flag to add the possibility to deploy a
imx-boot binary without the tagged footer
'UUUBURNXXOEUZX7+A-XY5601QQWWZ%sEN' at the end.
The addition of the footer 'UUUBURNXXOEUZX7+A-XY5601QQWWZ%sEN' at the end
causes issues when the binary is loaded into RAM memory, this footer may
cause issues where the binary size exceeds the typical USB package size
used by UUU (1021 bytes).
As example, if the footer is split across two distinct USB packages,
such as sending 'UUUBURNXXXOE' in the last packet and
'UZX7+A-XY5601QQWWZ%sEND' in the next one, it can lead to UUU halting
while waiting for a response in SDPS mode.
After sending 'UUUBURNXXXOE', iMX8MP's boot room starts SPL, not waiting
for the next packet ('UZX7+A-XY5601QQWWZ%sEND'), leading to UUU
breaking.
Therefore, …
=> uuu_bootloader_tag.bbclass: Add UUU_BOOTLOADER_UNTAGGED

recipes-bsp/u-boot/u-boot-imx_2023.04.bb
After commit 5a906365fd29 ("uuu_bootloader_tag.bbclass: Add UUU_BOOTLOADER_UNTAGGED"), the option for a untagged binary was added to uuu_bootloader_tag.bbclass. The u-boot-imx recipe also uses this binary, thefore add UUU_BOOTLOADER_TAGGED to this recipe as well.
=> u-boot-imx_2023.04.bb: Add UUU_BOOTLOADER_UNTAGGED variable

classes/uuu_bootloader_tag.bbclass
Use UUU_BOOTLOADER_TAGGED variable instead of UUU_BOOTLOADER in the stat function to make the code more specific and easy to read.
=> uuu_bootloader_tag.bbclass: Use UUU_BOOTLOADER_TAGGED variable

recipes-bsp/u-boot/u-boot-imx_2022.04.bb
After commit 4375edbb9da1 ("uuu_bootloader_tag.bbclass: Add UUU_BOOTLOADER_UNTAGGED"), the option for a untagged binary was added to uuu_bootloader_tag.bbclass. The u-boot-imx recipe also uses this binary, thefore add UUU_BOOTLOADER_TAGGED to this recipe as well.
(Cherry picked from commit 35f3ef016c21 and adjusted for kirkstone)
Signed-off-by: Hiago De Franco <hiago.franco@toradex.com>
=> u-boot-imx_2022.04.bb: Add UUU_BOOTLOADER_UNTAGGED variable

dynamic-layers/qt6-layer/recipes-qt/qt6/qtbase_%.bbappend
Mimic the behavior from recipe proper here since we override packageconfig defaults. With QT 6.7, qtbase built without wayland support is not sufficient to build rest of QT components e.g. qtwayland errors out during build/configure
ERROR: Qt Wayland Client requires QtGui to be build with support for wayland
Therefore add it when wayland is in distro features.
=> qtbase: Enable wayland knob when in distro features

recipes-bsp/imx-test/imx-test_git.bb
Hardcoding the root home directory could cause issues when the ROOT_HOME is not set to '/home/root'. As example, the ROOT_HOME can be changed to '/root', which makes imx-test install files in the wrong folder.
Therefore, replace '/home/root' with '$ROOT_HOME'. Usually, ROOT_HOME is already set to '/home/root' [1].
[1] https://docs.yoctoproject.org/4.3.3/ref-manual/variables.html?highlight=variables#term-ROOT_HOME
=> imx-test: Use ROOT_HOME instead of hardcoded home directory

recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_1.22.%.bbappend, recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_1.22.5.imx.bb
GStreamer is now 1.22.5 and as commented drop the viv-fb append.
=> gstreamer1.0-plugins-base: Don't always enable viv-fb

conf/machine/imx6qdlsabresd.conf
Change device tree paths to linux mainline, this was changed to the latest linux version.
=> imx6qdlsabresd: Change device tree paths to linux mainline

recipes-graphics/cairo/cairo_%.bbappend
This fixes the https://github.com/Freescale/meta-freescale/issues/1735
The master branch of meta-freescale is compatible with multiply Yocto releases since Kirstone.
Before Scarthgap cairo needs to be compiled with egl/gles. Return back replacing GL libraries for cairo 1.16.0 to fix rhe building issue [1].
[1]
2024-01-13 03:04:58 - INFO     - | cairo/1.16.0/recipe-sysroot-native/usr/bin/aarch64-lms-linux/../../libexec/aarch64-lms-linux/gcc/aarch64-lms-linux/13.2.0/ld: ../../boilerplate/.libs/libcairoboilerplate.a(cairo-boilerplate-glx.o): in function `_cairo_boilerplate_gl_cleanup':
2024-01-13 03:04:58 - INFO     - | cairo/1.16.0-r0/boilerplate/cairo-boilerplate-glx.c:60:(.text+0x16c): undefined reference to `glXDestroyContext'
2024-01-13 03:04:58 - INFO     - | …
=> cairo: Return back packageconfigs for 1.16.0

recipes-kernel/linux/linux-fslc_6.6.bb
Kernel repository has been upgraded up to v6.6.26 from stable kernel version.
=> linux-fslc: Update form v6.6 to v6.6.26

recipes-multimedia/alsa/alsa-lib/0001-pcm-Fix-segfault-with-32bit-libs.patch, recipes-multimedia/alsa/alsa-lib/0001-pcm-rate-fix-the-crash-in-snd_pcm_rate_may_wait_for_.patch, recipes-multimedia/alsa/alsa-lib/0007-add-conf-for-imx-cs42448-sound-card.patch, recipes-multimedia/alsa/alsa-lib_%.bbappend, recipes-multimedia/alsa/imx-alsa-plugins_git.bb, recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_1.22.5.imx.bb, recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_1.22.5.imx.bb, recipes-multimedia/gstreamer/gstreamer1.0-plugins-good_1.22.5.imx.bb, recipes-multimedia/gstreamer/gstreamer1.0_1.22.5.imx.bb, recipes-multimedia/gstreamer/imx-gst1.0-plugin_git.bb, recipes-multimedia/imx-codec/imx-codec_4.8.3.bb, recipes-multimedia/imx-dsp/imx-dsp-codec-ext_2.1.7.bb, recipes-multimedia/imx-dsp/imx-dsp_2.1.7.bb, recipes-multimedia/imx-opencl-converter/imx-opencl-converter_0.2.0.bb, recipes-multimedia/imx-parser/imx-parser_4.8.3.bb, recipes-multimedia/imx-vpuwrap/imx-vpuwrap_git.bb, recipes-multimedia/pipewire/pipewire/0001-launch-allow-pipewire-pulse-can-be-started-by-root.patch, recipes-multimedia/pipewire/pipewire_%.bbappend
Updated:
- alsa-lib update to 6.6.3_1.0.0 release and skip QA check for 32bit timer
- gstreamer1.0-plugins-bad_1.22.5.imx update to 6.6.3_1.0.0 release, enable g2d
- gstreamer1.0-plugins-base_1.22.5.imx update to 6.6.3_1.0.0 release, add opengl dependencies
- gstreamer1.0-plugins-good_1.22.5.imx update to 6.6.3_1.0.0 release, enable pulseaudio and 32bit timer
- gstreamer1.0_1.22.5.imx update to 6.6.3_1.0.0 release and add runtime dependency glibc-gconv-iso8859-5
- imx-gst1.0-plugin update to 6.6.3_1.0.0 release
- imx-vpuwrap update to 6.6.3_1.0.0 release
Upgraded:
- imx-codec: 4.8.2 -> 4.8.3
- imx-dsp-codec-ext: 2.1.6 -> 2.1.7
- imx-dsp: 2.1.6 -> 2.1.7
- imx-parser: 4.8.2 -> 4.8.3
- imx-opencl-converter: 0.1 -> 0.2.0
New feature:
- pipewire_1.0.0
=> recipes-multimedia: Upgrade to NXP release 6.6.3_1.0.0

recipes-kernel/linux/linux-fslc-imx_6.1.bb
This commit includes the following changes:
- 2bfda7392e66 Merge pull request #658 from tq-niebelm/6.1-2.2.x-imx
- 86a389d3e879 Merge remote-tracking branch 'lf-6.1.y' into 6.1-2.2.x-imx
- dad30ee71946 Merge pull request #657 from tq-niebelm/fslc-6.1-2.2.x-imx-fixes
- 5f6af3b30755 arm64: dts: imx8mm: fix csi nodes for NXP vendor stack
- 2443a1146bfd phy: phy-fsl-lynx-28g: fix wrong merge resolve
- 4e3fc5471376 Merge pull request #652 from schiffermtq/6.1-2.2.x-imx-fixes
- 2047384fddad i2c: imx: fix lockdep issue
- 4e0b61655262 ARM: dts: imx7s: fix ARM timer definition
- e0170f358bd1 ARM: imx: fix OCOTP compatible string on i.MX6SLL and i.MX6ULL
- 8ff00014e030 ARM: imx: fix i.MX7D-only build with CONFIG_SMP
- 1f7da780d0e7 ARM: imx: fix i.MX7D-only build with CONFIG_OPTEE
- 658bd1c4e0d1 …
=> linux-fslc-imx: Bump revision to 2bfda7392

conf/machine/imx6qdlsabreauto.conf, conf/machine/imx6qdlsabresd.conf, conf/machine/imx6slevk.conf, conf/machine/imx6sllevk.conf, conf/machine/imx6sxsabreauto.conf, conf/machine/imx6sxsabresd.conf, conf/machine/imx6ulevk.conf, conf/machine/imx6ullevk.conf, conf/machine/imx6ulz-14x14-evk.conf, conf/machine/imx7dsabresd.conf, conf/machine/imx7ulpevk.conf, recipes-kernel/linux/linux-fslc-imx_6.6.bb, recipes-kernel/linux/linux-imx-headers_6.6.bb, recipes-kernel/linux/linux-imx_6.6.bb
This PR updates the linux-imx and linux-fslc-imx to the branches based on linux 6.6 version
=> Update linux-imx and linux-fslc-imx versions

recipes-bsp/u-boot/u-boot-imx-common_2023.04.inc
Update the u-boot-imx to the tag lf-6.6.3-1.0.0, that is used in the NXP BSP LF6.6.3_1.0.0.
- f8a2983ec83 LFU-646-2 arm: imx: Fix coverity issue (Unintentional integer overflow)
- 89291cfd36e LFU-646-1 arm: imx: Fix coverity issue 36261228: Use after free
- 9b3315f59f6 LFU-647 mmc: Fix coverity issue 28682987: Logically dead code
- b72b414f4bc LFU-643 misc: imx_ele: Fix FSB redundancy fuse word check
- 398fdef0c06 MA-22105 android: imx8q: use default mcu reserved memory
- c1505f0cda5 LFU-639 ddr: imx95: add CRC field in quick boot state
- 3bdcde9e46c LFU-638 imx95-Titan: Fix I2C address conflict and I2C7 speed
- c1665b45e75 LFU-637 doc:imx:ahab Add i.MX95 Information to Secure Boot documentation
- …
=> u-boot-imx: Update to lf-6.6.3-1.0.0

recipes-security/optee-imx/optee-client_4.0.0.imx.bb, recipes-security/optee-imx/optee-os_4.0.0.imx.bb, recipes-security/optee-imx/optee-test_4.0.0.imx.bb
Update optee-* packages:
- optee-os
- optee-client
- optee-test
=> Update optee--* to 6.6.3

recipes-bsp/imx-atf/imx-atf_2.8.bb
Update to 8dbe28631 used in the NXP BSP release L6.6.3-1.0.0.
- 8dbe28631 LF-11383 imx95: Add support for q-channel/lpcg based wakeup sources
- 58f873d08 LF-11375 feat(imx95): flush L3 when system suspend
- da9bffd12 LF-11313 feat(plat) imx: imx95: clear LPIs enable
- 8d3073131 LF-11278 imx95: Ensure the cluster can be powered off in suspend.
- 8076903b6 LF-11057-2 feat(imx95): optimize cpuidle latency
- 9eb7b6ab1 LF-11057-1 feat(imx95): coding style cleanup
- 7d5458822 MA-21906 imx95: support Trusty OS
- d953d43e6 LF-10796 imx95: Move BL31 from OCRAM to DDR secure region
- d7fd4b3e2 LF-10524-08 feat(imx95): Make SCMI to be default enabled
- 657e94012 LF-10524-07 feat(imx93): get soc info from ele
- …
=> imx-atf: Update 6.1.55-2.2.0 to 6.6.3-1.0.0

conf/machine/include/imx-base.inc, recipes-bsp/firmware-imx/firmware-ele-imx_0.1.1.bb, recipes-bsp/firmware-imx/firmware-nxp-wifi_1.0.bb
=> Update firmware-nxp-wifi, firmware-ele-imx to 6.6.3-1.0.0

recipes-extended/jailhouse/jailhouse-imx_git.bb
Update the recipe to the BSP 6.6.3_1.0.0.
Add support of SoC i.MX95.
=> jailhouse-imx: Update the recipe to align to the NXP BSP LF6.6.3_1.0.0

recipes-bsp/imx-mkimage/imx-boot_1.0.bb
The folder iMX9 has been replaced by iMX91 and iMX93.
The same issue occurs on Scarthgap.
=> imx-boot: fix imx9 boot staging directory

recipes-graphics/waffle/waffle/0001-meson-Add-missing-wayland-dependency-on-EGL.patch, recipes-graphics/waffle/waffle/0002-meson-Separate-surfaceless-option-from-x11.patch
The patches for waffle 1.8.0 on master are not compatible with scarthgap. From here, scarthgap will be split from master.
This reverts commit 259541a36cd2cebaa32cced885da33cb30205dc8.
=> Revert "waffle: Fix broken patches"

recipes-kernel/linux/linux-fslc-imx_6.6.bb, recipes-kernel/linux/linux-fslc_6.6.bb
Tested building for:
- imx8dxl-a1-ddr3l-evk OK
- imx8dxl-a1-lpddr4-evk OK
- imx8dxl-b0-ddr3l-evk OK
- imx8dxl-b0-lpddr4-evk OK
- imx8dx-mek OK
- imx8mm-ddr4-evk OK
- imx8mm-lpddr4-evk OK
- imx8mn-ddr4-evk OK
- imx8mn-lpddr4-evk OK
- ...
=> Update linux-fslc-imx up to 6.6.28

recipes-kernel/kernel-modules/kernel-module-nxp-wlan_git.bb
Don't know if you're already working on this and/or have other routines for these things, but I needed to do this change in order to make wifi work on my IMX8MP-EVK with scarthgap, and I thought I might just as well create a PR for it.
=> kernel-module-nxp-wlan: Update to 6.6.3-1.0.0

recipes-bsp/imx-lib/imx-lib_git.bb, recipes-kernel/kernel-modules/kernel-module-isp-vvcam_4.2.2.24.1.bb
This seems to be the latest update for https://github.com/Freescale/meta-freescale/issues/1777
(if we are not going to add imx95 right now)
=> 6.6.3-1.0.0: update imx-lib and kernel-module-isp-vvcam

recipes-bsp/ppfe-firmware/ppfe-firmware_git.bb
Fixes QA error:
```
QA Issue: ppfe-firmware package is not obeying usrmerge distro feature. /lib should be relocated to /usr. [usrmerge]
```
How to proceeed to get this into `scarthgap` branch as well?
=> ppfe-firmware: Respect nonarch_base_libdir

recipes-kernel/linux/linux-fslc-lts_5.15.bb
Kernel repository has been upgraded up to v5.15.105 from stable korg.
=> [kirkstone] linux-fslc-lts: update to v5.15.105

recipes-core/udev/udev-rules-imx.bb, recipes-graphics/imx-gpu-viv/imx-gpu-viv-6.inc
This is now must with master branch of oe-core
=> imx-gpu-viv-6: Replace WORKDIR refrences with UNPACKDIR

recipes-core/udev/udev-rules-imx.bb
Setting S here to something local is redundant moreover master oe-core flags it now
Using S = ${WORKDIR} is no longer supported
=> udev-rules-imx: Drop setting S

recipes-kernel/linux/linux-fslc-imx_6.6.bb
- a1f3157034fe4 Merge pull request #670 from DiogoSilva014/6.6-1.0.x-imx-lpcg
- 55720fcb81c3e arch: arm64: freescale: imx8qm: fix flexcan clocks
- 9203cfabdfb68 Merge pull request #668 from DiogoSilva014/6.6-1.0.x-imx-fix-lpcg
- d6110c170fb98 Revert lpcg indice changes
- 2df26cdfbbbe0 Merge pull request #667 from MrCry0/6.6-1.0.x-imx-fix-imx8-usdhc
- a744d880dbb46 arch: arm64: freescale: imx8: fix sdhci clocks
=> linux-fslc-imx: 6.6: Fix merging issues

recipes-kernel/linux/linux-fslc-imx_6.6.bb
Update the kernel version to fix i.MX93 boot by selecting CONFIG_GPIO_VF610.
- d8b0bac40433 ("Merge pull request #672 from fabioestevam/imx93evk")
- e9ea6badf7e5 ("arm64: imx_v8_defconfig: Enable CONFIG_GPIO_VF610")
=> linux-fslc-imx: 6.6: Update kernel to fix i.MX93 boot

recipes-multimedia/gstreamer/gstreamer1.0-omx_%.bbappend
gstreamer1.0-omx has been removed from oe-core since:
commit 9c21815339afb85f558d8a1e0365614320cdc7d7
Author: Alexander Kanavin <alex@linutronix.de>
Date:   Mon May 27 20:12:13 2024 +0200
gstreamer1.0: update 1.22.11 -> 1.24.3
Drop gstreamer1.0-omx recipe as upstream has removed it:
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/4976
kate plugin dropped from bad.
amrnb/amrwb moved from ugly to good.
Signed-off-by: Alexander Kanavin <alex@linutronix.de>
Signed-off-by: Alexandre Belloni <alexandre.belloni@bootlin.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
Remove the gstreamer1.0-omx bbappend file.
=> gstreamer1.0-omx: Remove bbappend file

conf/machine/include/imx-base.inc, recipes-multimedia/gstreamer/gst-devtools_1.22.5.imx.bb, recipes-multimedia/gstreamer/gstreamer1.0-libav_1.22.5.imx.bb, recipes-multimedia/gstreamer/gstreamer1.0-plugins-ugly_1.22.5.imx.bb, recipes-multimedia/gstreamer/gstreamer1.0-python_1.22.5.imx.bb, recipes-multimedia/gstreamer/gstreamer1.0-rtsp-server_1.22.5.imx.bb, recipes-multimedia/gstreamer/gstreamer1.0-vaapi_1.22.5.imx.bb
Add the full set of 1.22.5 compatible recipes with the following exceptions due to build breaks for obsolete components:
- gstreamer1.0-omx: Drop the recipe
- gstreamer1.0-plugins-ugly: Drop liba52 and mpeg2dec support
These exceptions mirror changes in the upstream support:
9c21815339 gstreamer1.0: update 1.22.11 -> 1.24.3
90fbfe9fe1 liba52: remove the recipe
d46660e6c0 mpeg2dec: remove the recipe
(From OE-Core rev: ae9c64cd2291f4b24ac442816a4e354e47c70933)
=> gstreamer: Downgrade non-forked recipes to match 1.22.5.imx

recipes-kernel/linux/linux-fslc_6.6.bb
Kernel repository has been upgraded up to v6.6.32 from stable korg.
=> linux-fslc: update to v6.6.32

recipes-kernel/linux/linux-fslc_6.6.bb
The KBUILD_DEFCONFIG:mx5-generic-bsp entries appear three times.
Keep a single entry.
=> linux-fslc: Remove repeated mx5-generic-bsp entries

recipes-kernel/linux/linux-imx.inc, recipes-kernel/linux/linux-qoriq.inc
The default source code location for kernel is defined on the kernel.bbclass and it was 'S = "${STAGING_KERNEL_DIR}"'
In reality, although the kernel has its code in 'S = "${WORKDIR}/git"' it ends up being moved to '${STAGING_KERNEL_DIR}' in the do_symlink_kernsrc kernel.bbclass function.
With this change, the do_symlink_kernsrc kernel.bbclass function will no longer create the symbolic link and the final result will be the same.
=> linux: drop the old style kernels unshared S

recipes-bsp/imx-vpu-hantro-vc/imx-vpu-hantro-vc_1.9.1.bb, recipes-bsp/imx-vpu-hantro/imx-vpu-hantro-daemon_1.1.9.bb, recipes-bsp/imx-vpu-hantro/imx-vpu-hantro_1.32.0.bb, recipes-multimedia/imx-vpuwrap/imx-vpuwrap/0001-vpu_wrapper_hantro_encoder-add-sys-time.h-for-gettim.patch, recipes-multimedia/imx-vpuwrap/imx-vpuwrap_git.bb
This updates imx-vpu-hantro to rel_imx_6.6.3_1.0.0.
GCC-14 set more warnings to errors, fix the errors. Note that GCC throws errors also if building the older recipe versions.
=> Update imx-vpu-hantro and friends and fix compiler errors

dynamic-layers/chromium-browser-layer/recipes-browser/chromium/chromium/chromium.patch, dynamic-layers/openembedded-layer/recipes-devtools/luajit/luajit/ppc-fixplt.patch, dynamic-layers/qt4-layer/recipes-qt4/qt4/qt4/0001-Add-support-for-i.MX-codecs-to-phonon.patch, dynamic-layers/qt4-layer/recipes-qt4/qt4/qt4/0001-config.tests-add-DEFINES-to-compile-egl-test-with-im.patch, dynamic-layers/qt4-layer/recipes-qt4/qt4/qt4/0002-config.tests-add-DEFINES-to-compile-egl4gles1-test-w.patch, dynamic-layers/qt4-layer/recipes-qt4/qt4/qt4/0002-i.MX-video-renderer-Allow-v4l-device-from-environmen.patch, dynamic-layers/qt5-layer/recipes-qt/qt5/qtbase/0014-Add-IMX-GPU-support.patch, recipes-multimedia/imx-opencl-converter/imx-opencl-converter/0001-src-ocl.c-fix-wrong-integer-type.patch, recipes-multimedia/imx-vpuwrap/imx-vpuwrap/0001-vpu_wrapper_hantro_encoder-add-sys-time.h-for-gettim.patch
OE-core enabled the picky QA check on Upstream-Status. commit b7fb91c797ab ("insane: add patch-status to default ERROR_QA") Add missing upstream-status respectively fix unknown 'unknown' state.
strict_status_re = re.compile(r"^Upstream-Status: (Pending|Submitted|Denied|Inappropriate|Backport|Inactive-Upstream)( .+)?$", re.MULTILINE)
=> patches: fix upstream-status

recipes-kernel/linux/linux-imx.inc, recipes-kernel/linux/linux-qoriq.inc
This reverts commit 6dcdeccc845145a666fd30e7e48cf3d18988974e.
My conclusion was wrong because the source will be move to the STAGING_KERNEL_DIR only when we use the kernel-yocto.bbclass. This is because the same logic of moving sources is replicated here too.
Fix https://github.com/Freescale/meta-freescale/issues/1855
=> Revert "linux: drop the old style kernels unshared S"

dynamic-layers/openembedded-layer/recipes-dpaa/fmc/fmc/0001-FMCCFGReader-improve-parameter-definition-of-functio.patch
The code of fmc package is created in windows editer environment, and the CRLF is different from unix format, so update patch format so that apply patch smoothly.
=> fmc: update patch format

recipes-kernel/linux/linux-fslc-imx_6.6.bb
Update the kernel version to support for Olimex iMX8MP-SOM-4GB-IND and iMX8MP-SOM-EVB-IND.
- 13ed4e836942 ("Merge pull request #673 from leon-anavi/imx8mp-olimex")
- 6cdcd7103c2f ("imx8mp-olimex.dts: Olimex iMX8MP-SOM-EVB-IND")
=> linux-fslc-imx: 6.6: Support Olimex i.MX8MP

recipes-kernel/linux/linux-fslc-imx_6.6.bb
Update the kernel version to support for Olimex iMX8MP-SOM-4GB-IND and iMX8MP-SOM-EVB-IND.
- 13ed4e836942 ("Merge pull request #673 from leon-anavi/imx8mp-olimex")
- 6cdcd7103c2f ("imx8mp-olimex.dts: Olimex iMX8MP-SOM-EVB-IND")
=> Scarthgap: linux-fslc-imx: 6.6: Support Olimex i.MX8MP

recipes-bsp/imx-atf/imx-atf_2.10.bb
Update to 49143a1701d9 used in the NXP BSP release L6.6.23-2.0.0.
=> imx-atf: Update 6.6.3-1.0.0 to 6.6.23-2.0.0

recipes-kernel/linux/linux-fslc_6.6.bb
The build failures:
ERROR: linux-fslc-6.6.36+git-r0 do_package_qa: QA Issue: File /usr/src/debug/linux-fslc/6.6.36+git/lib/oid_registry_data.c in package linux-fslc-src contains reference to TMPDIR [buildpaths] ERROR: linux-fslc-6.6.36+git-r0 do_package_qa: Fatal QA errors were found, failing task.
ERROR: linux-fslc-6.6.36+git-r0 do_package_qa: QA Issue: File /usr/src/debug/linux-fslc/6.6.36+git/drivers/tty/vt/consolemap_deftbl.c in package linux-fslc-src contains reference to TMPDIR ERROR: linux-fslc-6.6.36+git-r0 do_package_qa: Fatal QA errors were found, failing task.
ERROR: linux-fslc-6.6.36+git-r0 do_package_qa: QA Issue: File /usr/src/debug/linux-fslc/6.6.36+git/drivers/video/logo/logo_linux_clut224.c in package linux-fslc-src contains reference to TMPDIR [buildpaths] ERROR: …
=> linux-fslc: Fix TMPDIR build failure

classes/fsl-u-boot-localversion.bbclass
Fixes regression introduced by
d7e13f19fbf9 ("fsl-u-boot-localversion.bbclass: fix SRCREV_machine and AUTOREV use cases")
Please backport to scarthgap as well.
=> Fix uboot localversion

recipes-bsp/imx-seco/imx-seco_5.9.4.bb
Update imx-seco to the new NXP BSP 6.6.23-2.0.0.
#1861
=> imx-seco: Update 6.6.3-1.0.0 to 6.6.23-2.0.0

recipes-bsp/firmware-imx/firmware-nxp-wifi_1.0.bb
Update to the new NXP BSP 6.6.23-2.0.0.
#1861
=> firmware-nxp-wifi: Update 6.6.3-1.0.0 to 6.6.23-2.0.0

recipes-kernel/kernel-modules/kernel-module-nxp-wlan_git.bb
Update mwifiex to the new NXP BSP 6.6.23-2.0.0.
#1861
=> kernel-module-nxp-wlan: Update 6.6.3-1.0.0 to 6.6.23-2.0.0

recipes-bsp/imx-lib/imx-lib_git.bb
Update the imx-lib branch to the new NXP BSP 6.6.23-2.0.0.
#1861
=> imx-lib: Update 6.6.3-1.0.0 to 6.6.23-2.0.0

recipes-bsp/imx-mkimage/imx-boot_1.0.bb, recipes-bsp/imx-mkimage/imx-mkimage_git.inc
Update recipes to NXP BSP version 6.6.23-2.0.0.
This commit introduces the 'imx95' target.
=> imx-mkimage: Update 6.6.3-1.0.0 to 6.6.23-2.0.0

recipes-bsp/imx-oei/imx-oei_1.0.0.bb
OEI stands for "Optional Executable Image", it was relased for NXP BSP 6.6.23-2.0.0. The OEI Firmware is required for the i.MX 95 SoC.
=> recipes-bsp: introduce imx-oei recipe

recipes-multimedia/imx-codec/imx-codec_4.9.0.bb, recipes-multimedia/imx-dsp/imx-dsp-codec-ext_2.1.8.bb, recipes-multimedia/imx-dsp/imx-dsp_2.1.8.bb, recipes-multimedia/imx-parser/imx-parser_4.9.0.bb, recipes-multimedia/imx-vpuwrap/imx-vpuwrap/0001-vpu_wrapper_hantro_VCencoder-add-sys-time.h-for-gett.patch, recipes-multimedia/imx-vpuwrap/imx-vpuwrap_git.bb
Update the following recipes to NXP BSP 6.6.23-2.0.0:
- imx-codec 4.9.0
- imx-dsp 2.1.8
- imx-parser 4.9.0
- imx-vpuwrap (branch MM_04.09.00_2405_L6.6.y)
=> recipes-multimedia: imx-*: Update 6.6.3-1.0.0 to 6.6.23-2.0.0

recipes-multimedia/libimxvpuapi/libimxvpuapi2_2.3.0.bb
After bumping gstreamer1.0-plugins-imx build is failing. Here is a snippet of the build error:
| ../git/ext/vpu/gstimxvpuenc.c:473:20: error: 'ImxVpuApiEncOpenParams' has no member named 'fixed_intra_quantization'
|         open_params->fixed_intra_quantization =
imx_vpu_enc->fixed_intra_quantization;
|                    ^~
Fix it by updating libimxvpuapi2 to the current HEAD of its repository.
=> libimxvpuapi2: Bump revision to 8639837a246f

recipes-bsp/imx-mkimage/imx-boot_1.0.bb
These fixes were first introduced accidentally on `scarthgap`, #1869. Cherry-pick to `master`.
=> imx-boot: inherit from uboot-config rather than uboot-sign

recipes-extended/jailhouse/jailhouse-imx_git.bb
Update to the new NXP BSP 6.6.23-2.0.0.
Related-to: #1861
=> jailhouse-imx: Update 6.6.3-1.0.0 to 6.6.23-2.0.0

recipes-graphics/wayland/weston-init.bbappend
The modification of the weston.ini command line necessary for RDP support is missing. The problem is the weston.ini template contains `@bindir@`, while the sed operation for the modification contains `${bindir}`.
Fix the problem by moving the replacement of `@bindir@` to the top of the function `do_install:append()`.
=> weston-init: Fix RDP support

recipes-graphics/wayland/weston-init.bbappend
The modification of the weston.ini command line necessary for RDP support is missing. The problem is the weston.ini template contains `@bindir@`, while the sed operation for the modification contains `${bindir}`.
Fix the problem by moving the replacement of `@bindir@` to the top of the function `do_install:append()`.
(cherry picked from commit 1963104c4ad7367686c910c70a07cbc7df3cd6c5)
=> [scarthgap] weston-init: Fix RDP support

conf/machine/include/imx-base.inc
12.0.3.imx is gone from metadata
=> imx-base: Bump weston P_V to 12.0.4.imx

recipes-bsp/firmware-imx/firmware-ele-imx_0.1.2.bb
This aligns with the current version available on meta-imx layer.
Related-to: #1861
=> firmware-ele-imx: Bump to version 0.1.2

recipes-bsp/imx-seco/imx-seco-libs_git.bb
Update imx-seco-libs to latest 6.6.23-2.0.0 BSP release.
=> imx-seco-libs: Update to latest from NXP 6.6.23-2.0.0

recipes-bsp/imx-secure-enclave/imx-secure-enclave_git.bb
This library allows the use of the EdgeLock secure Enclave (ELE) from Linux userspace.
Moreover, this library is a build dependency of i.MX Security Middleware Library.
_Note. This recipe has been also tested on Scarthgap and can be cherry pick on the Scarthgap branch to fix the missing build dependency with SMW._
=> imx-secure-enclave: add the lf-6.6.3-1.0.0 recipe

recipes-security/optee-imx/optee-client-fslc.inc
Fixes regression introduced by 79fd80f1 ("optee: Upgrade optee recipes from 4.0.0.imx to 4.2.0.imx").
Please backport to scarthgap as well.
=> Fix OP-TEE libteec version

classes/imx-boot-container.bbclass
Assign weak init value for `IMX_BOOT_CONTAINER_FIRMWARE_SOC` to be able override it for future i.MX SoCs.
=> imx-boot-container: Assign weak init value for `IMX_BOOT_CONTAINER_FIRMWARE_SOC`

recipes-bsp/u-boot/u-boot-fslc-common_2024.07.inc
This commit changes the u-boot-fslc source revision to 5b4d66dd. This new revison fix a issue with imx8mq bootloader.
=> u-boot-fslc: Bump to revison 5b4d66dd

conf/machine/include/imx-base.inc
4.2.0.imx was merged via [1]
Therefore match the version settings
[1] https://github.com/Freescale/meta-freescale/pull/1906
=> imx-base: Bump optee P_V to 4.2.0.imx

recipes-multimedia/tinycompress/tinycompress_1.1.6.bb
In some network-environments download with git-protocol is not possible. By switching to https the sources are accessable.
=> tinycompress: use https-protocol to download sources

dynamic-layers/arm-toolchain/recipes-bsp/imx-oei/imx-oei_1.0.0.bb
The recipe build changes depending on the `OEI_BOARD` value, which is machine-specific.
This should also be backported to scarthgap branch
=> imx-oei: use `MACHINE_ARCH` as `PACKAGE_ARCH`

recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad/0001-autovideoconvert-add-imxvideoconvert_g2d.patch, recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_1.24.0.imx.bb
Add patch to enable imxvideoconvert on autovideoconvert. By default, imxvideoconvert_g2d is not included as a potential filter, resulting in poor video playback performance when autovideoconvert is used.
Add imxvideoconvert_g2d to improve performance by utilizing hardware acceleration.
=> gstreamer1.0-plugins-bad: Add imxvideoconvert_g2d to autovideoconvert

classes/imx-boot-container.bbclass, classes/uuu_bootloader_tag.bbclass, conf/machine/include/imx-base.inc, recipes-bsp/imx-mkimage/imx-boot_1.0.bb, recipes-bsp/u-boot/u-boot-fslc_2024.07.bb, recipes-bsp/u-boot/u-boot-imx_2024.04.bb, wic/imx-imx-boot-bootpart.wks.in, wic/imx-imx-boot.wks.in, wic/imx-uboot-bootpart.wks.in, wic/imx-uboot-spl-bootpart.wks.in, wic/imx-uboot-spl.wks.in, wic/imx-uboot.wks
The introduction of the UUU-tagged bootloader causes problems for the non-wic case, as reported here [1] and here [2].
[1] https://github.com/Freescale/meta-freescale/pull/1762
[2] https://github.com/nxp-imx/mfgtools/issues/416
This PR is an attempt to improve the original feature by limiting the use of the tagged file to the wic case, while restoring the default file back to the untagged version. This does effectively revert [1] as no longer needed.
=> Restore default bootloader to untagged version

recipes-kernel/kernel-modules/kernel-module-isp-vvcam_4.2.2.24.2.bb
Update to the new NXP BSP 6.6.23-2.0.0.
=> kernel-module-isp-vvcam: Update 6.6.3-1.0.0 to 6.6.23-2.0.0

recipes-kernel/linux/linux-fslc-imx_6.6.bb
Update the recipe (with comments) to stable tag up to v6.6.51.
=> linux-fslc-imx: Update 6.6-2.0.x-imx up to v6.6.51

recipes-kernel/cryptodev/cryptodev-module_%.bbappend, recipes-kernel/cryptodev/files/fix-build-for-Linux-6.7-rc1.patch
Fix build for Linux 6.7-rc1: https://github.com/cryptodev-linux/cryptodev-linux/commit/5e7121e45ff283d30097da381fd7e97c4bb61364
Since Linux 6.7-rc1, no ahash algorithms set a nonzero alignmask, and therefore `crypto_ahash_alignmask` has been removed.
See also:
- https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=0f8660c82b79af595b056f6b9f4f227edeb88574
- https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=c626910f3f1bbce6ad18bc613d895d2a089ed95e
=> cryptodev-module: Add patch fix for prepare kernel v6.11.0 in scarthgap

recipes-kernel/linux/linux-fslc-lts_6.1.bb, recipes-kernel/linux/linux-fslc-lts_6.6.bb, recipes-kernel/linux/linux-fslc_6.11.bb
- Update linux-fslc: 6.6.50 -> 6.11.0
=> [master] linux-fslc: 6.6.50 -> 6.11.0

dynamic-layers/multimedia-layer/recipes-multimedia/pipewire/pipewire_%.bbappend
Add libcamera plugins back for i.MX 95. 
Also need merge back to branch scarthgap.
=> pipewire: Add libcamera back to PACKAGECONFIG for i.MX 95

recipes-bsp/u-boot/u-boot-imx-common_2024.04.inc
Update the u-boot-imx to the tag lf-6.6.36-2.1.0, that is used in the NXP BSP LF6.6.36_2.1.0. This commit adds the following changes:
- de16f4f1722 configs: ls1088ardb: enable CONFIG_PHY_AQUANTIA
- 291d018424c MA-22821 Adjust the fastboot offset used for avb verification
- aefc41754b1 Pull request #135: MA-22768 Android: Enable NEON instruction acceleration as default on i.MX 95
- dfabeeba1bf LFU-785 arm: dts: fsl-ls1088a: Enable USB nodes
- f1b36b56740 MA-22768 Android: Enable NEON instruction acceleration as default on i.MX 95
- 127c4143ced MA-22751-2 Android: Enable kaslr function on all android platforms
- bbaa7cd97bc MA-22751-1 Enable kaslr function on all android platforms
- 5c751212a6a Pull request #130: Feature/MA-22726 add rng driver for ele
- 796b36cef2b LF-13165 imx91_evk/qsb: …
=> u-boot-imx: Update to lf-6.6.36-2.1.0

wic/imx-imx-boot-bootpart.wks.in
For i.MX 9 a typical kernel is 35 MB. With gcov, that increases to 75 MB
or more. Bump the /boot partition size accordingly.
=> imx-imx-boot-bootpart.wks.in: Increase /boot partition 64 MiB -> 256 MiB

dynamic-layers/multimedia-layer/recipes-multimedia/pipewire/pipewire_%.bbappend
Add gstreamer back to PACKAGECONFIG.
Also need backport to branch scarthgap.
=> pipewire: Exclude gstreamer from PACKAGECONFIG list for i.MX 6, 7, 8 and 93

recipes-bsp/imx-atf/imx-atf_2.10.bb
Distro's which use ld-is-lld end up with LD=<HOST_PREFIX>ld.lld and remove_options_tail() does not handle such cases
=> imx-atf: Redefine LD using HOST_PREFIX

recipes-graphics/mesa/mesa-etnaviv-env_0.1.bb
Prevent the following warning by setting S to an existing directory. (no real problem was seen but the warning)
| WARNING: mesa-etnaviv-env-0.1-r0 do_unpack: mesa-etnaviv-env:
|     the directory ${WORKDIR}/${BP} (.../mesa-etnaviv-env/0.1/mesa-etnaviv-env-0.1)
|     pointed to by the S variable doesn't exist - please set S within
|     the recipe to point to where source has been unpacked to
=> mesa-etnaviv-env: prevent warning

recipes-kernel/kernel-modules/kernel-module-isp-vvcam_4.2.2.24.2.bb
I see this also on scarthgap so I propose if it is accepted to also backport to scarthgap.
=> kernel-module-isp-vvcam: prevent build warning

conf/machine/imx93-11x11-lpddr4x-evk.conf
Use updated kernel device tree for imx93-11x11 board.
=> imx93-11x11: Fix KERNEL_DEVICETREE

recipes-security/optee-imx/optee-client_4.2.0.imx.bb, recipes-security/optee-imx/optee-os_4.2.0.imx.bb, recipes-security/optee-imx/optee-test_4.2.0.imx.bb
Upgrade optee-client, optee-os and optee-test to new NXP BSP LF6.6.36_2.1.0.
Related-to: #1953
=> recipes-security: optee-imx: optee-*: Upgrade BSP to LF6.6.36_2.1.0

recipes-security/optee-imx/optee-os-fslc.inc
Fix the QA Error:
ERROR: optee-os-4.2.0.imx-r0 do_package_qa: QA Issue: File /usr/include/optee/export-user_ta_arm64/lib/libutils.a in package optee-os-staticdev contains reference to TMPDIR [buildpaths] ERROR: optee-os-4.2.0.imx-r0 do_package_qa: QA Issue: File /usr/include/optee/export-user_ta_arm64/lib/libdl.a in package optee-os-staticdev contains reference to TMPDIR [buildpaths] ERROR: optee-os-4.2.0.imx-r0 do_package_qa: QA Issue: File /usr/include/optee/export-user_ta_arm64/lib/libmbedtls.a in package optee-os-staticdev contains reference to TMPDIR [buildpaths] ERROR: optee-os-4.2.0.imx-r0 do_package_qa: QA Issue: File /usr/include/optee/export-user_ta_arm64/lib/libutee.a in package optee-os-staticdev contains reference to TMPDIR [buildpaths] ERROR: optee-os-4.2.0.imx-r0 …
=> optee-os: work-around buildpaths QA error of staticdev

classes/use-imx-security-controller-firmware.bbclass, conf/machine/imx95-19x19-verdin.conf, conf/machine/include/imx-base.inc, conf/machine/include/imx95-evk.inc, dynamic-layers/arm-toolchain/recipes-bsp/imx-system-manager/imx-system-manager.inc, dynamic-layers/arm-toolchain/recipes-bsp/imx-system-manager/imx-system-manager_1.0.0.bb, recipes-kernel/linux/linux-imx-headers_6.6.bb, recipes-kernel/linux/linux-imx_6.6.bb, recipes-security/optee-imx/optee-os-fslc-imx.inc
Update the recipes to support i.MX 95 based boards.
The [i.MX 95 Verdin Evaluation Kit](https://www.nxp.com/webapp/connect/displayPartnerProfile.sp?partnerId=4900&offeringId=48065) is a kit developed together with NXP. Port the machine from meta-imx.
@flora2086 Should I keep you as the maintainer here or do you prefere if I put myself in?
The SoC features a ARM Mali GPU. I'm still working to port the mali-imx recipe providing the drivers. So any recipe depending on virtual/egl and friends will throw an error during building for an i.MX 95 based machine.
Note that the new machine depends on imx-system-manager and imx-oei which both depend on meta-arm-toolchain. This is not yet reflected anywhere. (layer.conf, repo manifest, fsl-community-bsp-base)
The image builds and boots to a login …
=> Add first i.MX 95 based machine

recipes-kernel/linux/linux-fslc-imx_6.6.bb
It includes the following commit:
a10c64e35a24 tty: vt: conmakehash: cope with abs_srctree no longer in env
=> linx-fslc-imx: Update the kernel recipe

dynamic-layers/arm-toolchain/recipes-bsp/imx-system-manager/imx-system-manager.inc
The recipe build changes depending on the `SYSTEM_MANAGER_CONFIG` value, which is machine-specific.
=> imx-system-manager: use `MACHINE_ARCH` as `PACKAGE_ARCH`

recipes-bsp/imx-mkimage/imx-boot_1.0.bb
The fix made in commit 2db7047ba40e
("imx-boot: Fix 8M multi-config build problems")
broke builds not using U-Boot multi-config, as the link created ends up being a simple recursive link when UBOOT_DTB_NAME_EXTRA is the same as UBOOT_DTB_NAME.
It fails with something like this:
```
| ./../scripts/dtb_check.sh imx8mq-evk.dtb evk.dtb imx8mq-var-dart-dt8mcustomboard.dtb
|  Can't find u-boot DTB file, please copy from u-boot
```
caused by a symlink like this:
```
lrwxrwxrwx 1 1000 1000 35 Oct 29 21:32 imx8mq-var-dart-dt8mcustomboard.dtb -> imx8mq-var-dart-dt8mcustomboard.dtb
```
Fixes: 2db7047ba40e ("imx-boot: Fix 8M multi-config build problems")
=> imx-boot: Fix 8M non multi-config build problem

recipes-bsp/imx-mkimage/imx-mkimage_git.inc, recipes-extended/jailhouse/jailhouse-imx_git.bb, recipes-fsl/mcore-demos/README, recipes-fsl/mcore-demos/imx-m7-demos_2.16.001.bb
=> Upgrade mcore-demos, jailhouse-imx and imx-mkimage to LF6.6.36_2.1.0

recipes-kernel/linux/linux-fslc-imx_6.6.bb
Update the kernel version based on branch 6.6-2.1.x-imx to include the patch for Olimex iMX8MP-SOM-4GB-IND and iMX8MP-SOM-EVB-IND.
=> linux-fslc-imx: 6.6: Update

recipes-bsp/libimxdmabuffer/libimxdmabuffer_1.1.3.bb
PACKAGECONFIG[dwl] injects a direct dependency on imx-vpu-hantro which in itself is only compatible with (mx8mq-nxp-bsp|mx8mm-nxp-bsp|mx8mp-nxp-bsp)
When configuring a mx8mn based machine (e.g. imx8mn EVK) the imx-vpu-hantro is skipped as not compatible, but a world build fails with
ERROR: Nothing PROVIDES 'imx-vpu-hantro'
(but /build/meta-freescale/recipes-bsp/libimxdmabuffer/libimxdmabuffer_1.1.2.bb DEPENDS on or otherwise requires it) imx-vpu-hantro was skipped: incompatible with machine imx8mn-ddr4-evk (not in COMPATIBLE_MACHINE) imx-vpu-hantro was skipped: incompatible with machine imx8mn-ddr4-evk (not in COMPATIBLE_MACHINE) ERROR: Required build target 'meta-world-pkgdata' has no buildable providers. Missing or unbuildable dependency chain was: ['meta-world-pkgdata', …
=> libimxdmabuffer: be explicit about dwl compatibility

recipes-kernel/linux/linux-fslc-imx_6.6.bb
It also updates the stable kernel tags up to version v6.6.69, and include some LmP commits
=> linux-fslc-imx: Use 6.6-2.2.0.x from NXP BSP LF6.6.52_2.2.0

dynamic-layers/openembedded-layer/recipes-benchmark/glmark2/glmark2_%.bbappend
Since i.MX 8, DRM is supported by default by the i.MX GPU. Simplify the DRM config logic by reversing the default, making it clear that it is i.MX 6 and 7 that do not support DRM.
=> glmark: Simplify logic for DRM config

conf/machine/include/imx-base.inc
When using `fitImage` as kernel image type the `fitImage` already contains the device tree blob files. So, it's not necessary to add them to the image boot files.
=> imx-base: Avoid unnecessary device tree blob files

conf/machine/imx8mp-lpddr4-evk.conf, conf/machine/imx8qm-mek.conf, conf/machine/imx8qxp-mek.conf, conf/machine/imx8ulp-lpddr4-evk.conf, conf/machine/imx93-9x9-lpddr4-qsb.conf, conf/machine/include/imx8x-mek.inc, recipes-extended/jailhouse/jailhouse-imx_git.bb, recipes-kernel/linux/linux-imx-headers_6.6.bb, recipes-kernel/linux/linux-imx_6.6.bb
Base on L6.6.52-2.2.0 release:
1,Upgrade Jailhouse to L6.6.52_2.0.0
2,Upstream machine dtbs
=> Update kernel and jailhouse to L6.6.52_2.0.0

recipes-bsp/qe-ucode/qe-ucode_git.bb
According to the commit c89d7843943f("Move License File from NXP-Binary-EULA to LICENSE") of repo https://github.com/nxp-qoriq/qoriq-qe-ucode. NXP-Binary-EULA is renamed to LICENSE, so replace NXP-Binary-EULA with LICENSE in recipe file.
=> qe-ucode: replace NXP-Binary-EULA with LICENSE to calculate checksum

classes/use-imx-security-controller-firmware.bbclass, conf/machine/include/imx-base.inc
This adds the basis support for i.MX91 based platforms. This adds the necessary SoC-specific variable overwrites in `imx-base.inc` and `use-imx-security-controller-firmware.bbclass`
=> Basic i.MX91 platform support

scripts/generate-license-file
I was wondering why a bot decided to force-push a commit to a PR of mine. It turns out the script responsible for generating the LICENSE file is not deterministic, so depending on random file system layout we can end up regenerating the LICENSE without any actual change. For example:
$ diff -u <(git show baf20676~1:LICENSE | sort) <(git show baf20676:LICENSE | sort)
shows that baf20676 didn't provide any change at all in the actual contents, yet
$ git show --stat baf20676
commit baf20676bcd2b454577449dbf7b0346d7080b880
Author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
Date:   Wed Jan 22 21:42:44 2025 +0000
Auto-update LICENSE file with current recipe licenses
LICENSE | 256 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++------------------------------- …
=> scripts: avoid pointless LICENSE churn

conf/layer.conf
Due to commit 1e3228f1 (imx-atf: Adjust for compiler virtual renames in oe-core), which was required due to oe-core commit 4ccc3bc, this is no longer compatible with styhead.
=> drop styhead compatibility

recipes-bsp/firmware-imx/firmware-ele-imx_1.3.0.bb
There is no need to limit this to NXP BSPs. This should also be backported to scartgap
=> firmware-ele-imx: Use generic-bsp compatible

recipes-kernel/linux/linux-fslc-imx_6.6.bb
Move to stable kernel version 6.6.74 and fix the NXP tag.
=> linux-fslc-imx: Update 6.6-2.2.x to stable v6.6.74

conf/machine/include/imx-base.inc
It allows a  correct kernel load address when using FIT image with i.MX93. The value 0x80400000 has been retrieved from imx93_11x11_evk_defconfig in uboot-imx.
See issue #2100.
=> Set default UBOOT_ENTRYPOINT for mx93-generic-bsp

recipes-kernel/linux/linux-fslc-imx_6.6.bb
Port some patches from 6.6-2.1.x to 6.6-2.2.x and update the recipe documentation to include them.
=> linux-fslc-imx: Forward port patches into 6.6-2.2.x

recipes-graphics/imx-gpu-viv/imx-gpu-viv-6.inc
The recipe is missing PROVIDES virtual/libgles3 for i.MX 6 and 7 GPU.
=> imx-gpu-viv: Add missing PROVIDES virtual/libgles3

recipes-bsp/imx-secure-enclave/imx-secure-enclave_git.bb
bump the recipe to the LF6.6.52_2.2.0
=> imx-secure-enclave: Bump to lf-6.6.52_2.2.0

wic/imx-imx-boot-bootpart.wks.in
Using --size in the imx-imx-boot-bootpart.wks.in to set size of /boot partition does not result in a 256MiB partition as expected but in a ~332MiB one.  Indeed, --size ensures --extra-space (default 10MiB) is added to actual data size and furthermore applies --overhead-factor (default 1.3) to the wanted size. This is exactly the case here as 256
* 1.3 = 332.8.
Use --fixed-size instead to force the /boot partition to be exactly 256MiB just as it is indicated in the comments of this file. Consequently, the `do_image_wic` task will also fail if data copied in this partition are too large at creation.
---
A [comment indicating the situation ](https://github.com/Freescale/meta-freescale/pull/1962#discussion_r1799936635) was also added to the previous commit on this file.
=> imx-imx-boot-bootpart.wks.in: Set fixed size for /boot partition

recipes-bsp/imx-atf/imx-atf_2.10.bb
```
- 1b27ee3ed Pull request #96: MA-23026 Fix bug: failed boot on LS platforms due caam driver
- 02b06d177 MA-23026 Fix bug: failed boot on LS platforms due caam driver
- afd50b207 LF-13734 fix(imx95): add missing license header
- 0efc2fff8 Pull request #95: MA-23009 Fix i.MX 8Q boot failed when trusty disabled
- 0728e974a MA-23009 Fix i.MX 8Q boot failed when trusty disabled
- f590c74e5 Pull request #94: MA-23007 Fix bug, i.MX 8MN ATF failed to build
- e9823459d MA-23007 Fix i.MX 8MN build break
- a53124bcd Pull request #92: ATF RNG
- 5b66f7321 MA-21916 Enable caam driver for i.MX
- 55f8854fc MA-21915 Make the CAAM driver compatible with i.MX devices
- 1d6489907 MA-22997 Fix bug: 8q failed to print any logs in ATF
- dfda4210e Pull request #88: Lf v2.10 LF-13160
- …
```
=> imx-atf: Bum to match 6.6.52-2.2.0

recipes-bsp/u-boot/u-boot-imx-common_2024.04.inc
- 6c4545203d1 LF-13928 update key for capsule
- a6fbbc4830b LF-13892 imx8mp_evk: Fix kernel boot failure with DDR ECC enabled
- b2f3a82bb62 LFU-815 imx91: Update iMX9101 PN support to latest config
- dd06e11a237 LFU-813-3 imx95_15x15_evk: Turn on PCA9632 LED for LVDS backlight
- 3215ce8075b LFU-813-2 imx95_19x19_evk: Enable backlight for LVDS
- 063caa4957a LFU-813-1 gpio: adp5585: Reset alternate function pins to GPIO
- ca6436fb7e4 LFU-812 arm: dts: imx95: Assign PLL VCO as the parent of PLL
- 0688aa50da0 MA-23021 secretkeeper: return earlier if not initialized
- 0ee139a17eb MA-23003-2 android: populate the SecretKeeper identity
- e3b6dacd0ef MA-23003-1 trusty: add SecretKeeper client
- f63ddd9cb11 LFU-808-3 power: regulator: correct the LDO_SNVS name
- 5726a995b80 …
=> u-boot-imx: Bump to 6.6.52-2.2.0

recipes-bsp/qe-ucode/qe-ucode_git.bb
According to the commit c89d7843943f("Move License File from NXP-Binary-EULA to LICENSE") of repo https://github.com/nxp-qoriq/qoriq-qe-ucode. NXP-Binary-EULA is renamed to LICENSE, so replace NXP-Binary-EULA with LICENSE in recipe file.
=> qe-ucode: replace NXP-Binary-EULA with LICENSE to calculate checksum  (cherry-picked from master)

LICENSE, recipes-bsp/firmware-imx/firmware-nxp-wifi_1.1.bb
The upstream kernel Wi-Fi driver expects the sdiouart8997_combo_v4 and sdiouartiw416_combo_v0 binaries to be located under firmware/mrvl [1], different from the out-of-tree driver, which places them under firmware/nxp. Create symbolic links to deploy these binaries in the correct location for the upstream driver.
Due to this change, bump the recipe version to 1.1.
[1] https://github.com/torvalds/linux/blob/master/drivers/net/wireless/marvell/mwifiex/sdio.h#L31
=> firmware-nxp-wifi: create symbolic links to firmware/mrvl folder

recipes-multimedia/libimxvpuapi/libimxvpuapi2_2.3.1.bb
Fix build error of gstreamer-imx on Scarthgap. Applying patch 7926ba9bb65762002e2c0506b7e4bd4d950323a6 from Styhead.
=> libimxvpuapi2: Upgrade to version 2.3.1 to fix build of gstreamer-imx

recipes-kernel/linux/linux-fslc-imx_6.6.bb
- 5ff4cf4d61e11 Merge pull request #713 from angolini/fix_imx93
- e587f8fe42f16 firmware: se_fw: remove info_list from ro section
- a0609cb5220a7 Merge pull request #712 from angolini/push_one
- 0f638960dcffd media: Kconfig: fix double VIDEO_DEV
- 226bfffe04bcb Merge pull request #709 from fs-csenatore/6.6-2.2.x-imx
- 198242c057e00 drivers:clk:imx:clk-imx8mp-audiomix: remove duplicated CLK_GATE_PARENT definition
- 427223e3206dd Merge pull request #707 from iceaway/revert_u-serial_patch
- 4f5936d7391f8 Revert "usb: gadget: u_serial: Disable ep before setting port to null to fix the crash caused by port being null"
=> linux-fslc-imx: Update with some bugfixes patches

recipes-multimedia/imx-vpuwrap/imx-vpuwrap/0001-vpu_wrapper_hantro_encoder-fix-missing-include.patch, recipes-multimedia/imx-vpuwrap/imx-vpuwrap_git.bb
Add missing include file. Otherwise with latest master we see:  
| ../git/vpu_wrapper_hantro_encoder.c:953:3: error: implicit declaration of function 'gettimeofday' [-Wimplicit-function-declaration]
|   953 |   gettimeofday (&pObj->tvEnd, NULL);
@thochstein Can you report internally?
=> imx-vpuwrap: fix build error

recipes-fsl/mcore-demos/README, recipes-fsl/mcore-demos/imx-m4-demos_1.0.1.bb, recipes-fsl/mcore-demos/imx-m7-demos_24.12.00.bb, recipes-fsl/mcore-demos/imx-mcore-demos.inc
imx95 mocre: 2.16.001 -> 24.12.00
Install elf binary to /usr/lib/firmware/
=> mcore-demos: Upgrade to 6.6.52_2.2.0

recipes-fsl/mcore-demos/imx-mcore-demos.inc
The demo extension is overridable so the new install behavior needs to use the variable.
Fixes #2056.
=> imx-mcore-demos: Fix 7ULP install

recipes-fsl/mcore-demos/imx-mcore-demos.inc
For 7D there are no .elf files and there is a build break:
```
| install: cannot stat '.../imx7d-sabresd-m4-freertos-1.0.1/*.elf': No such file or directory
```
Fixes #2056.
=> imx-mcore-demos: Fix 7D

conf/machine/imx8qm-mek.conf, conf/machine/include/imx8x-mek.inc
On Walnascar, 8QM and 8QXP MEK fail to boot. One difference in the log compared with Styhead is the getty on ttyAMA0 instead of ttyLP0 and a failure:
```
[ TIME ] Timed out waiting for device /dev/ttyAMA0.
```
It seems SERIAL_CONSOLES for these two boards has been wrong all along but masked until recently:
https://git.yoctoproject.org/poky/commit/meta/recipes-core/systemd?id=d1eaffbd6bde845c3fcd81660b694e1ea1f46ab2
=> imx8qm-mek,imx8qxp-mek: Fix SERIAL_CONSOLES

recipes-bsp/imx-uuc/imx-uuc_git.bb
The do_configure task is failing:
```
ERROR: imx-uuc-0.5.1+git-r1 do_configure: no configure script found at ./configure
```
It appears to be due to this OE-Core change:
autotools: require that a configure script exists
There's no point inheriting autotools if you're not actually going to
run a configure script, so make a missing configure script fatal.
https://github.com/openembedded/openembedded-core/commit/6d327a39befae44a88a812bdf4acde800dcee57b
imx-uuc doesn't need autotools, just a simple do_install implementation.
=> imx-uuc: Don't inherit autotools

recipes-bsp/imx-mkimage/imx-mkimage_git.inc
71b8c18 Add flash_all_ap target for non-Linux ap image.
b8f5454 For iMX95, change verdin M7 image name.
d97f0eb For iMX95, change 15x15 M7 image name.
0576197 M7 image names changed again.
=> imx-mkimage: Upgrade to NXP BSP 6.6.52_2.2.0

conf/machine/include/imx-base.inc, dynamic-layers/arm-toolchain/recipes-bsp/imx-oei/imx-oei_1.0.0.bb, recipes-bsp/imx-mkimage/imx-boot_1.0.bb
Some hardware vendors provide a customized Optional Executable Image (OEI) with changes specific to their boards (e.g. Toradex SMARC i.MX95).
Add a virtual provider to avoid conflicts between the OEI recipes from other layers. This follows the pattern used for the related imx-system-manager.
=> imx-oei: provide virtual/imx-oei

recipes-bsp/imx-atf/imx-atf_2.10.bb
- 1b27ee3ed Pull request #96: MA-23026 Fix bug: failed boot on LS platforms due caam driver
- 02b06d177 MA-23026 Fix bug: failed boot on LS platforms due caam driver
- afd50b207 LF-13734 fix(imx95): add missing license header
- 0efc2fff8 Pull request #95: MA-23009 Fix i.MX 8Q boot failed when trusty disabled
- 0728e974a MA-23009 Fix i.MX 8Q boot failed when trusty disabled
- f590c74e5 Pull request #94: MA-23007 Fix bug, i.MX 8MN ATF failed to build
- e9823459d MA-23007 Fix i.MX 8MN build break
- a53124bcd Pull request #92: ATF RNG
- 5b66f7321 MA-21916 Enable caam driver for i.MX
- 55f8854fc MA-21915 Make the CAAM driver compatible with i.MX devices
- 1d6489907 MA-22997 Fix bug: 8q failed to print any logs in ATF
- dfda4210e Pull request #88: Lf v2.10 LF-13160
- 8b770b71f …
=> [scarthgap] imx-atf: Bump to match 6.6.52-2.2.0

conf/machine/include/imx-base.inc
mx8mq uses 0x30860000 as the base address for boot uart base.
=> imx-base: mx8mq: fix SOC_ATF_BOOT_UART_BASE value

recipes-kernel/kernel-modules/kernel-module-nxp-wlan/wlan_src_driver_patch_release_lf-6.6.52-2.2.0.patch, recipes-kernel/kernel-modules/kernel-module-nxp-wlan_git.bb
NXP released a patch for the MXM driver that is supposed to be applied on top of the checked out branch. Among other things, this patch adds a "MODULE_DEVICE_TABLE" which means the SDIO device driver is probed at runtime, which will not happen without this patch.
Link: https://www.nxp.com/webapp/Download?colCode=Wireless-Patch-Release-IW612-W8997-W8801-v0.1&appType=license
---
Note that on this page, the incremental release listed in the row for "6.6.52-2.2.0" is _not_ the same (it's the older one intended for 6.6.32) as the wireless patch you can download further down from the "Downloads" section. That last one is the (correct) one included here.
=> kernel-module-nxp-wlan: Apply wireless patch

recipes-kernel/kernel-modules/kernel-module-nxp-wlan/wlan_src_driver_patch_release_lf-6.6.52-2.2.0.patch
Add Upstream-Status to patch.
Fixes:
```
ERROR: kernel-module-nxp-wlan-git-r0 do_patch: QA Issue: Missing Upstream-Status in patch
/home/leon/poky-olimex-imx8mp/meta-freescale/recipes-kernel/kernel-modules/kernel-module-nxp-wlan/wlan_src_driver_patch_release_lf-6.6.52-2.2.0.patch
Please add according to https://docs.yoctoproject.org/contributor-guide/recipe-style-guide.html#patch-upstream-status . [patch-status]
ERROR: kernel-module-nxp-wlan-git-r0 do_patch: Fatal QA errors were found, failing task.
ERROR: Logfile of failure stored in: /home/leon/poky-olimex-imx8mp/build/tmp/work/olimex_imx8mp_evb-poky-linux/kernel-module-nxp-wlan/git/temp/log.do_patch.1878769
ERROR: Task (/home/leon/poky-olimex-imx8mp/meta-freescale/recipes-kernel/kernel-modules/kernel-module-nxp-wlan_git.bb:do_patch) …
```
=> kernel-module-nxp-wlan: Add Upstream-Status

recipes-graphics/mesa/mesa.bbappend
mesa is updated in oe-core to 25.0.2. That version dropped the configure option kmsro and unconditionally adds the code [1].
oe-core currently still has the packageconfig for it, however enabling results in a built time error. A fix is on the ML [2].
| ERROR: mesa-2_25.0.2-r0 do_recipe_qa: QA Issue: mesa: invalid PACKAGECONFIG(s): kmsro [invalid-packageconfig]
[1] https://gitlab.freedesktop.org/mesa/mesa/-/commit/70813c1c13b99cb029c8fa3537163650bdd17b6d
[2] https://lore.kernel.org/all/20250412-mesa-25-fixes-v1-1-791840391271@oss.qualcomm.com/
=> mesa: bbappend: drop kmsro packageconfig

recipes-bsp/isp-imx/isp-imx_4.2.2.24.4.bb
Latest master meta-oe updated tinyxml2 to version 11.0.0. isp-imx packages a prebuilt library dynamically linked against tinyxml2.so.10 which is no longer provided, thus:
| ERROR: isp-imx-4.2.2.24.4-r0 do_package_qa: QA Issue: /usr/lib/libcam_device.so contained in package 
| isp-imx requires libtinyxml2.so.10()(64bit), but no providers found in RDEPENDS:isp-imx? [file-rdeps]
Fix the build by updating the dynamic section to require tinyxml2.so.11.
Note that I don't have a system to runtime test if that still works. The tinyxml2 API doesn't look like it changed from 10 to 11.
Note that the tinyxml2 version bump is only in meta-openembedded master. Styhead is providing tinxml2 10.0.0.
=> isp-imx: fix build against updated tinyxml2

recipes-bsp/imx-mkimage/imx-boot_1.0.bb
For the iMX95 it can be necessary to use a different DDR FW version than the one selected by default by the mkimage build. You might need newer FW binaries while still supporting an older NXP BSP.
Pass LPDDR_FW_VERSION to make if it is set, otherwise do nothing such that the Makefile selects its default value just like before.
When using a different FW version without setting LPDDR_FW_VERSION accordingly you will get a build error similar to the below:
```
| DEBUG: Executing shell function do_compile
| NOTE: UBOOT_CONFIG = sd, UBOOT_DTB_NAME =
| NOTE: i.MX 95 boot binary build
| NOTE: i.MX 93 boot binary build
| NOTE: Copy ddr_firmware: lpddr4x_dmem_v202409.bin from $BUILD_PATH/deploy/images/verdin-imx95 -> $BUILD_PATH/tmp/work/verdin_imx95-tdx-linux/imx-boot/1.0/git/iMX95
[...]
| …
```
=> imx-boot: add LPDDR_FW_VERSION to mkimage arguments for iMX95

dynamic-layers/openembedded-layer/recipes-devtools/cst/imx-cst_3.4.0.bb
meta-oe includes imx-cst only in styhead and above branches, but not in scarthgap. Revert the removal in order to provide imx-cst for scarthgap as well.
This reverts commit 448312c35ca20d40ebfc515317246f6c227cdcf9.
=> Restore imx-cst in scarthgap again

recipes-bsp/alsa-state/alsa-state/imx-mainline-bsp/asound.conf, recipes-bsp/alsa-state/alsa-state/imx-nxp-bsp/asound.conf
Change the default sample rate as used with ALSA to 48000 instead of
44100. Most newer content, videos, and web-based content uses 48 kHz sampling rate, especially with modern codecs like Opus.
Normally applications request ALSA to use a PCM sample rate which matches the input content when starting playback. However, more complex applications such as Chromium will internally resample audio to match the default output. This can result in high CPU usage for resampling, so having ALSA's default rate match the majority of content is preferred.
See also #2217.
=> asound.conf: default sample rate to 48000

recipes-multimedia/alsa/alsa-lib/0001-add-conf-for-multichannel-support-in-imx.patch, recipes-multimedia/alsa/alsa-lib/0005-add-ak4458-conf-for-multichannel-support.patch, recipes-multimedia/alsa/alsa-lib/0006-add-conf-for-iMX-XCVR-sound-card.patch, recipes-multimedia/alsa/alsa-lib/0007-add-conf-for-imx-cs42448-sound-card.patch
This PR makes the alsa-lib patches compatible with 1.2.13 (walnascar) and 1.2.14 (latest master).
Feel free to close if branching off walnascar looks like the better solution.
=> alsa-lib: rework patches to apply on 1.2.13 and 1.2.14

conf/machine/include/qoriq-base.inc, recipes-bsp/alsa-state/alsa-state.bbappend, recipes-bsp/alsa-state/alsa-state/qoriq-generic-bsp, recipes-bsp/alsa-state/alsa-state/qoriq-mainline-bsp, recipes-bsp/alsa-state/alsa-state/qoriq-nxp-bsp
This asound.conf can be used for both i.MX and Layerscale platforms. But the latter don't have `imx-<default>-bsp` in their overrides. Use the common `use-<default>-bsp` instead.
=> alsa-state: Use i:MX-specific configuration to support QorIQ platforms

recipes-kernel/kernel-modules/kernel-module-nxp-wlan/mlinux-moal_main-lower-PRINTM_MMSG-log-level-to-KERN_INFO.patch, recipes-kernel/kernel-modules/kernel-module-nxp-wlan_git.bb
Add a patch to change the log level used in the mwifiex driver's PRINTM_MMSG macro from KERN_ALERT to KERN_INFO.
KERN_ALERT is meant for critical errors; using it for debug messages clutters logs. KERN_INFO is more appropriate for non-critical informational output.
=> kernel-module-nxp-wlan: add patch to lower PRINTM_MMSG() log level

recipes-kernel/kernel-modules/kernel-module-isp-vvcam_4.2.2.25.1.bb
This commit add the following source revisions:
78d717b MA-23208 Fix undeclared "vmalloc" build error in vvcam
2ac9f12 CL1041202 M865SW-1317: vvcam: isp framerate statistic is not accurate
ad07139 MA-21928-1 Fix update symbol list build error
f4d9818 CL982766 M865SW-1297: vvcam: Modify license for vvfocus headfile
aba15ee CL981700 M865SW-1272: vvcam: Add little endian support for raw10/raw12 capture in tuning tool
72c5955 CL950364 M865SW-1248: vvcam: ISP service random crash and can't be recovered.
4fabcb6 LF-12838: vvcam: Fix the os08a20 sensor capture failed issue
b5a4eaf LF-12820-3: vvcam: video: Fix build issue on rebase kernel next-20240618
c2cf5b7 LF-12820-2: vvcam: isp: Fix build issue on rebase kernel next-20240618
e470f21 LF-12820-1: vvcam: dwe: Fix build issue on rebase kernel …
=> kernel-module-isp-vvcam: 4.2.2.24.2 -> 4.2.2.25.1

conf/machine/include/imx-base.inc, recipes-graphics/wayland/wayland-protocols_1.37.imx.bb, recipes-graphics/wayland/weston_14.0.1.imx.bb
Hi all,
Updated wayland protocol and weston to 1.37 and 14.01 based on LF6.12.3_1.1.0.  Tested with weston-* clients, works fine. The related libraries like xwayland and graphics libraries can be taken up in due course.
Regards,
Sathishkumar D
=> Wayland protocol and Weston: Updated to 1.37 and 14.0.1

conf/machine/imx95-19x19-verdin.conf
Fixes building the machine as the deployed DDR FW files now are not the ones expected by imx-mkimage.
=> imx95-19x19-verdin: follow update to nxp bsp 6.12.3_1.0.0

recipes-bsp/imx-test/imx-test_git.bb
This commit update source branch and add the following source revisions:
92a4973 MLK-26263 mxc_v4l2_capture: add verbose mode to output realtime status
4838c5a LF-14230: mxc_asrc_test: switch to upstreamed API
5eedc57 LF-14501: vpu: solve dqbuf return error
81bf1cc LF-14501: vpu : solve camera node enum fail
3ee0114 MLK-26240-10: mxc_v4l2_vpu_test: support to set colorimetry for encoder
3034abb MLK-26240-9: mxc_v4l2_vpu_test: drop incomplete avcc nalu
30f2b13 MLK-26240-8: mxc_v4l2_vpu_test: remove the buffer count check in waylandsink
be8275f MLK-26240-7: mxc_v4l2_vpu_test: support to handle YUV4MPEG2
92ca890 MLK-26240-6: mxc_v4l2_vpu_test: parser support to init format from the postfix
8c9a466 MLK-26240-5: mxc_v4l2_vpu_test: ofile support to append format postfix
05b0181 MLK-26240-4: …
=> imx-test: Update SRCBRANCH lf-6.6.3_1.0.0 -> lf-6.12.3_1.0.0

recipes-graphics/imx-gpu-viv/imx-gpu-viv-6.inc, recipes-graphics/imx-gpu-viv/imx-gpu-viv_6.4.11.p2.10-aarch32.bb, recipes-graphics/imx-gpu-viv/imx-gpu-viv_6.4.11.p2.10-aarch64.bb, recipes-graphics/imx-gpu-viv/imx-gpu-viv_6.4.11.p3.0-aarch32.bb, recipes-graphics/imx-gpu-viv/imx-gpu-viv_6.4.11.p3.0-aarch64.bb
This commit update the recipes imx-gpu-viv for aarch32 and aarch64.
=> imx-gpu-viv: 6.4.11.p2.10 -> 6.4.11.p3-0

recipes-bsp/imx-sc-firmware/imx-sc-firmware_1.18.0.bb
Some distros e.g. yoe uses LLD linker as default, it does not work with prebuilt baremetal toolchain used for imx-sc-firmware
=> imx-sc-firmware: Always use BFD linker

recipes-graphics/mesa/mesa-demos/0001-YOCIMX-8300-Fix-mesa-demos-build-break-on-GCC-14.patch, recipes-graphics/mesa/mesa-demos/0001-egl-clear-backgrounds-black.patch, recipes-graphics/mesa/mesa-demos/Replace-glWindowPos2iARB-calls-with-glWindowPos2i.patch, recipes-graphics/mesa/mesa-demos/fix-clear-build-break.patch, recipes-graphics/mesa/mesa-demos_%.bbappend
This commit fix the old patchs and add the following new patch:
0001-YOCIMX-8300-Fix-mesa-demos-build-break-on-GCC-14.patch
=> mesa-demos: Add new patch for mesa-demos application

recipes-multimedia/libimxvpuapi/libimxvpuapi2_2.3.1.bb, recipes-multimedia/libimxvpuapi/libimxvpuapi_git.bb
The usage of the host native can break the build in depends of the container version you run and even let you depend on host tools. Make the dependency on yocto package
=> recipes-multimedia: libimxvpuapi: Use python-native instead the host one

recipes-graphics/xwayland/xwayland_24.1.6.imx.bb
Current recipe is failing with the following error:
| ../xwayland-24.1.6/os/meson.build:66:8: ERROR: Problem encountered: secure-rpc requested, but neither libtirpc or libc RPC support were found
Fix it by adding libtirpc as dependency. This aligns with the xwayland recipe from oe-core layer [1].
[1] https://github.com/openembedded/openembedded-core/commit/6334fac0a0b0783298957e2ccbe3a27490f7da09
Fixes: 2a1583a69cf6 ("xwayland: 23.2.5.imx -> 24.1.6-imx")
=> xwayland: add missing libtirpc dependency

classes/imx-boot-container.bbclass
After commit commit 015483904c52 ("arm: imx8m: add OP-TEE node") in upstream U-Boot, Binman complains if building imx8mp_evk with CONFIG_OPTEE=y because tee.bin is missing:
Image 'image' is missing external blobs and is non-functional: tee-os
/binman/section/nxp-imx8mcst@1/fit/images/tee/tee-os (tee.bin):
See the documentation for your board. You may need to build Open Portable
Trusted Execution Environment (OP-TEE) and build with TEE=/path/to/tee.bin
Image 'image' has faked external blobs and is non-functional: tee.bin
Some images are invalid
make: *** [Makefile:1135: .binman_stamp] Error 103
This commit ensures that ${OPTEE_BOOT_IMAGE}, for example, tee.bin for imx8mp-evk, is copied to the build folder if the optee feature is enabled.
=> imx-boot-container: copy ${OPTEE_BOOT_IMAGE} to ${B}

dynamic-layers/arm-toolchain/recipes-bsp/imx-system-manager/imx-system-manager.inc
Change V=y to V=1 for proper verbose output in iMX System Manager builds.
=> imx-system-manager: fix EXTRA_OEMAKE verbose parameter

recipes-kernel/kernel-modules/kernel-module-nxp-wlan/mxm_wifiex_fix_build_error_for_64-bit_division.patch, recipes-kernel/kernel-modules/kernel-module-nxp-wlan/mxm_wifiex_fix_build_error_for_udelay.patch, recipes-kernel/kernel-modules/kernel-module-nxp-wlan_git.bb
This fixes bug errors on scarthgap. On master it's already integrated (as master uses the newer release where the backports were copied from)
The backported commits are:
https://github.com/nxp-imx/mwifiex/commit/fd7dd188a1ad7eb8bc110d30815e087362f91d72
https://github.com/nxp-imx/mwifiex/commit/f45013f26a7045e882e4a0ac99ae126571fa60af
=> [SCARTHGAP] kernel-module-nxp-wlan: Fix build error

recipes-multimedia/gstreamer/imx-gst1.0-plugin/0001-gplay2-fix-termio.h-no-longer-existing.patch, recipes-multimedia/gstreamer/imx-gst1.0-plugin_git.bb
OE-core updated to glibc 2.42. This version no longer provides termio.h.
Fixes
| ...tools/gplay2/gplay2.c:29:10: fatal error: termio.h: No such file or directory
=> imx-gst1.0-plugin: fix build against glibc 2.42

recipes-bsp/imx-uuc/imx-uuc_git.bb
As NXP moves imx-uuc.git to project github.com/nxp-imx, the original github.com/NXPmicro/imx-uuc.git will be redircting to this new location.
=> imx-uuc: Update upsteam URI to nxp-imx

conf/machine/imx95-19x19-verdin.conf, conf/machine/include/imx-base.inc, dynamic-layers/arm-toolchain/recipes-bsp/imx-oei/imx-oei_1.0.0.bb
This is part of issue #2326
Took the changes from `meta-imx` to update to BSP 6.6.52-2.2.1, but with one notable difference in `imx95-a1-19x19-verdin.conf`:
Add the "imx95-19x19-verdin" machine override such that all
conditional overrides for the base machine are also executed for this A1
machine.
In practice this override was only used in `imx-boot_1.0.bb` for
MKIMAGE_EXTRA_ARGS. meta-imx added a `imx95-a1-19x19-verdin` override
there that does the same as the `imx95-19x19-verdin` override, this
commit solves it differently by adding the `imx95-19x19-verdin` override
to the A1 machine.
=> [SCARTHGAP] Update imx-oei to NXP BSP LF6.6.52-2.2.1, support B0 silicon

recipes-graphics/imx-g2d/imx-gpu-g2d_6.4.11.p2.12.bb, recipes-graphics/imx-gpu-viv/imx-gpu-viv_6.4.11.p2.10-aarch32.bb, recipes-graphics/imx-gpu-viv/imx-gpu-viv_6.4.11.p2.10-aarch64.bb, recipes-graphics/imx-gpu-viv/imx-gpu-viv_6.4.11.p2.12-aarch32.bb, recipes-graphics/imx-gpu-viv/imx-gpu-viv_6.4.11.p2.12-aarch64.bb
This is part of #2326
Did a quick test on a Verdin iMX8MP and did not spot any obvious regressions around the GPU
=> [SCARTHGAP] bump imx-gpu-viv/imx-gpu-g2d to align with NXP BSP LF6.6.52-2.2.1

recipes-bsp/firmware-imx/firmware-nxp-wifi_1.1.bb
Upgrade to 6.12.20-2.1.0 release
- Add new firmware for AW693-PCIE and IW610-USB
=> firmware-nxp-wifi: Update for LF-6.12.20_2.1.0

recipes-extended/jailhouse/files/0001-YOCIMX-9281-1-Fix-gcc15-errors.patch, recipes-extended/jailhouse/files/0002-YOCIMX-9281-2-hypervisor-arm64-fix-strh-usage.patch, recipes-extended/jailhouse/jailhouse-imx_git.bb
This commit add the following source revisions:
a68ba027 LF-14423 driver/pci: unbind device before remove overlay
a41801ca only allow root cell to use Trusted SMC
e4a40952 only allow root cell to use SIP
ba9cf440 driver/pci: explicitly invoke pci_host_common_remove
=> jailhouse-imx: Update branch from lf-6.6.52 -> lf-6.12.3

recipes-bsp/atf/qoriq-atf_2.12.bb, recipes-dpaa2/dce/dce_git.bb, recipes-extended/odp/odp.inc
${WORKDIR}/git or  ${UNPACKDIR}/git no longer supported in whinlatter
=> global recipes: Fix whinlatter updates for source code lacation

recipes-devtools/uuu/uuu-bin_1.5.233.bb, recipes-devtools/uuu/uuu_git.bb
Upgrade uuu to latest release, which introduces support for container format v2 required on newer SoCs such as i.MX943 and i.MX95 B0.
This version adds support for macOS on ARM. As a result, the former executable uuu_mac has been renamed to uuu_mac_x86, and a new uuu_mac_arm binary is provided.
=> [master] uuu: upgrade 1.5.165 -> 1.5.233
